= Lenovo
:toc:
:toclevels: 1

== B50-70 20384 (b50-70-20384.bin)

[horizontal]
File path:: `lenovo/b50-70-20384.bin`
Product name:: 20384
Product version:: Lenovo B50-70
Product family:: IDEAPAD
Firmware vendor:: LENOVO
Firmware version:: 9DCN22WW(V2.03)
Release date:: 2014-08-21
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `7` | Cache information | 4  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 8  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`
a| `11` | OEM strings | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `15` | System event log | 1  a| `0x0029`
a| `16` | Physical memory array | 1  a| `0x002A`
a| `17` | Memory device | 4  a| `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `18` | 32-bit memory error information | 3  a| `0x002F`, `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 2  a| `0x0033`, `0x0034`
a| `21` | Built-in pointing device | 1  a| `0x0035`
a| `22` | Portable battery | 1  a| `0x0036`
a| `24` | Hardware security | 1  a| `0x0037`
a| `26` | Voltage probe | 1  a| `0x0038`
a| `27` | Cooling device | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `39` | System power supply | 1  a| `0x003B`
a| `40` | Additional information | 1  a| `0x003C`
a| `41` | Onboard devices extended information | 1  a| `0x003D`
a| `127` | End of table | 1  a| `0x0043`
a| `128` | OEM-specific | 1  a| `0x003E`
a| `133` | OEM-specific | 1  a| `0x003F`
a| `136` | OEM-specific | 1  a| `0x0040`
a| `221` | Intel firmware version information | 2  a| `0x0041`, `0x0042`
|===
== B590 (b590.bin)

[horizontal]
File path:: `lenovo/b590.bin`
Product name:: INVALID
Product version:: Lenovo
Product family:: Lenovo
Firmware vendor:: LENOVO
Firmware version:: H5ET85WW(1.23)
Release date:: 2014-04-15
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0005`
a| `7` | Cache information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 8  a| `0x0010`, `0x0011`, `0x0014`, `0x0017`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `9` | System slots | 2  a| `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0035`
a| `16` | Physical memory array | 1  a| `0x000C`
a| `17` | Memory device | 2  a| `0x000D`, `0x000E`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x000F`
a| `21` | Built-in pointing device | 2  a| `0x002F`, `0x0030`
a| `22` | Portable battery | 2  a| `0x002C`, `0x002D`
a| `24` | Hardware security | 1  a| `0x0036`
a| `126` | Inactive | 15  a| `0x0012`, `0x0013`, `0x0015`, `0x0016`, `0x0018`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0028`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x000A`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x000B`, `0x0031`
a| `132` | OEM-specific | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x0033`
a| `134` | Lenovo date record | 1  a| `0x0004`
a| `135` | Lenovo ThinkPad device presence detection | 3  a| `0x0032`, `0x0034`, `0x0038`
a| `140` | Lenovo ThinkPad embedded controller program | 1  a| `0x0039`
|===
== IdeaPad 330S-15IKB 81F5 (ideapad-330s-15ikb-81f5.bin)

[horizontal]
File path:: `lenovo/ideapad-330s-15ikb-81f5.bin`
Product name:: 81F5
Product version:: Lenovo ideapad 330S-15IKB
Product family:: ideapad 330S-15IKB
Firmware vendor:: LENOVO
Firmware version:: 7SCN36WW
Release date:: 2019-10-09
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 17  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `9` | System slots | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `11` | OEM strings | 1  a| `0x001E`
a| `12` | System configuration options | 1  a| `0x001F`
a| `13` | Firmware language information | 1  a| `0x0020`
a| `14` | Group associations | 3  a| `0x0021`, `0x0022`, `0x0023`
a| `15` | System event log | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 2  a| `0x0026`, `0x0027`
a| `19` | Memory array mapped address | 1  a| `0x0028`
a| `20` | Memory device mapped address | 2  a| `0x0029`, `0x002A`
a| `21` | Built-in pointing device | 1  a| `0x002B`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x002D`
a| `26` | Voltage probe | 1  a| `0x002E`
a| `27` | Cooling device | 1  a| `0x002F`
a| `28` | Temperature probe | 1  a| `0x0030`
a| `32` | System boot information | 1  a| `0x0031`
a| `39` | System power supply | 1  a| `0x0032`
a| `40` | Additional information | 1  a| `0x0033`
a| `41` | Onboard devices extended information | 1  a| `0x0034`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0035`
a| `129` | OEM-specific | 1  a| `0x0036`
a| `130` | Intel Active Management Technology information | 1  a| `0x0037`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0038`
a| `133` | OEM-specific | 1  a| `0x0039`
a| `136` | OEM-specific | 1  a| `0x003A`
a| `200` | Lenovo machine type model | 1  a| `0x003B`
a| `219` | Intel Management Engine interface information | 1  a| `0x003C`
a| `221` | Intel firmware version information | 4  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0041`
a| `248` | OEM-specific | 1  a| `0x0042`
|===
== IdeaPad G580 20150 (ideapad-g580-20150.bin)

[horizontal]
File path:: `lenovo/ideapad-g580-20150.bin`
Product name:: 20150
Product version:: Lenovo G580
Product family:: IDEAPAD
Firmware vendor:: LENOVO
Firmware version:: 5ECN96WW(V9.01)
Release date:: 2013-03-14
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 2  a| `0x0006`, `0x0007`
a| `7` | Cache information | 4  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `8` | Port connector information | 16  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 8  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `11` | OEM strings | 1  a| `0x0024`
a| `12` | System configuration options | 1  a| `0x0025`
a| `13` | Firmware language information | 1  a| `0x0026`
a| `15` | System event log | 1  a| `0x0027`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 2  a| `0x0029`, `0x002A`
a| `18` | 32-bit memory error information | 3  a| `0x002B`, `0x002C`, `0x002D`
a| `19` | Memory array mapped address | 1  a| `0x002E`
a| `20` | Memory device mapped address | 2  a| `0x002F`, `0x0030`
a| `21` | Built-in pointing device | 1  a| `0x0031`
a| `22` | Portable battery | 1  a| `0x0032`
a| `26` | Voltage probe | 1  a| `0x0033`
a| `27` | Cooling device | 1  a| `0x0034`
a| `32` | System boot information | 1  a| `0x0035`
a| `39` | System power supply | 1  a| `0x0036`
a| `40` | Additional information | 1  a| `0x0037`
a| `41` | Onboard devices extended information | 1  a| `0x0038`
a| `127` | End of table | 1  a| `0x003C`
a| `128` | OEM-specific | 1  a| `0x0039`
a| `133` | OEM-specific | 1  a| `0x003A`
a| `136` | OEM-specific | 1  a| `0x003B`
|===
== IdeaPad L340-15IRH Gaming 81LK [2] (ideapad-l340-15irh-gaming-81lk-2.bin)

[horizontal]
File path:: `lenovo/ideapad-l340-15irh-gaming-81lk-2.bin`
Product name:: 81LK
Product version:: IdeaPad L340-15IRH Gaming
Product family:: IdeaPad L340-15IRH Gaming
Firmware vendor:: LENOVO
Firmware version:: BGCN36WW
Release date:: 2022-05-24
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 17  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `9` | System slots | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `11` | OEM strings | 2  a| `0x001E`, `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0021`
a| `14` | Group associations | 3  a| `0x0022`, `0x0023`, `0x0024`
a| `15` | System event log | 1  a| `0x0025`
a| `16` | Physical memory array | 1  a| `0x0026`
a| `17` | Memory device | 1  a| `0x0027`
a| `19` | Memory array mapped address | 1  a| `0x0028`
a| `20` | Memory device mapped address | 1  a| `0x0029`
a| `21` | Built-in pointing device | 1  a| `0x002A`
a| `22` | Portable battery | 1  a| `0x002B`
a| `24` | Hardware security | 1  a| `0x002C`
a| `26` | Voltage probe | 1  a| `0x002D`
a| `27` | Cooling device | 1  a| `0x002E`
a| `28` | Temperature probe | 1  a| `0x002F`
a| `32` | System boot information | 1  a| `0x0030`
a| `39` | System power supply | 1  a| `0x0031`
a| `40` | Additional information | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 1  a| `0x0033`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0034`
a| `129` | OEM-specific | 1  a| `0x0035`
a| `130` | Intel Active Management Technology information | 1  a| `0x0036`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x0038`
a| `136` | OEM-specific | 1  a| `0x0039`
a| `200` | Lenovo machine type model | 1  a| `0x003A`
a| `219` | Intel Management Engine interface information | 1  a| `0x003B`
a| `221` | Intel firmware version information | 5  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0041`
a| `248` | OEM-specific | 1  a| `0x0042`
|===
== IdeaPad L340-15IRH Gaming 81LK [1] (ideapad-l340-15irh-gaming-81lk.bin)

[horizontal]
File path:: `lenovo/ideapad-l340-15irh-gaming-81lk.bin`
Product name:: 81LK
Product version:: IdeaPad L340-15IRH Gaming
Product family:: IdeaPad L340-15IRH Gaming
Firmware vendor:: LENOVO
Firmware version:: BGCN28WW
Release date:: 2019-12-27
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 17  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `9` | System slots | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `11` | OEM strings | 1  a| `0x001E`
a| `12` | System configuration options | 1  a| `0x001F`
a| `13` | Firmware language information | 1  a| `0x0020`
a| `14` | Group associations | 3  a| `0x0021`, `0x0022`, `0x0023`
a| `15` | System event log | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 1  a| `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 1  a| `0x0028`
a| `21` | Built-in pointing device | 1  a| `0x0029`
a| `22` | Portable battery | 1  a| `0x002A`
a| `24` | Hardware security | 1  a| `0x002B`
a| `26` | Voltage probe | 1  a| `0x002C`
a| `27` | Cooling device | 1  a| `0x002D`
a| `28` | Temperature probe | 1  a| `0x002E`
a| `32` | System boot information | 1  a| `0x002F`
a| `39` | System power supply | 1  a| `0x0030`
a| `40` | Additional information | 1  a| `0x0031`
a| `41` | Onboard devices extended information | 1  a| `0x0032`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0033`
a| `129` | OEM-specific | 1  a| `0x0034`
a| `130` | Intel Active Management Technology information | 1  a| `0x0035`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0036`
a| `133` | OEM-specific | 1  a| `0x0037`
a| `136` | OEM-specific | 1  a| `0x0038`
a| `200` | Lenovo machine type model | 1  a| `0x0039`
a| `219` | Intel Management Engine interface information | 1  a| `0x003A`
a| `221` | Intel firmware version information | 5  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0040`
a| `248` | OEM-specific | 1  a| `0x0041`
|===
== IdeaPad Slim 5 14IRL8 (ideapad-slim-5-14irl8.bin)

[horizontal]
File path:: `lenovo/ideapad-slim-5-14irl8.bin`
Product name:: 82XD
Product version:: IdeaPad Slim 5 14IRL8
Product family:: IdeaPad Slim 5 14IRL8
Firmware vendor:: LENOVO
Firmware version:: LACN29WW
Release date:: 2023-09-01
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 17  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 5  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `11` | OEM strings | 1  a| `0x0023`
a| `12` | System configuration options | 1  a| `0x0024`
a| `13` | Firmware language information | 1  a| `0x0025`
a| `14` | Group associations | 2  a| `0x0026`, `0x004D`
a| `15` | System event log | 1  a| `0x0027`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 2  a| `0x0029`, `0x002A`
a| `19` | Memory array mapped address | 1  a| `0x002B`
a| `20` | Memory device mapped address | 8  a| `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`
a| `21` | Built-in pointing device | 1  a| `0x0034`
a| `22` | Portable battery | 1  a| `0x0035`
a| `24` | Hardware security | 1  a| `0x0036`
a| `26` | Voltage probe | 1  a| `0x0037`
a| `27` | Cooling device | 1  a| `0x0038`
a| `28` | Temperature probe | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `39` | System power supply | 1  a| `0x003B`
a| `40` | Additional information | 1  a| `0x003C`
a| `41` | Onboard devices extended information | 1  a| `0x003D`
a| `43` | TPM device | 1  a| `0x003E`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x003F`
a| `129` | OEM-specific | 1  a| `0x0040`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0041`
a| `133` | OEM-specific | 1  a| `0x0042`
a| `136` | OEM-specific | 1  a| `0x0043`
a| `200` | Lenovo machine type model | 1  a| `0x0044`
a| `219` | Intel Management Engine interface information | 1  a| `0x0045`
a| `221` | Intel firmware version information | 6  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`
a| `248` | OEM-specific | 1  a| `0x004C`
|===
== IdeaPad Z565 20066 (ideapad-z565-20066.bin)

[horizontal]
File path:: `lenovo/ideapad-z565-20066.bin`
Product name:: 20066
Product version:: IdeaPad Z565
Product family:: Type1Family
Firmware vendor:: LENOVO
Firmware version:: 36CN23WW(V2.09)
Release date:: 2010-12-01
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0020`
a| `5` | Memory controller information | 1  a| `0x002E`
a| `6` | Memory module information | 2  a| `0x0026`, `0x002A`
a| `7` | Cache information | 2  a| `0x0021`, `0x0022`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 5  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `16` | Physical memory array | 1  a| `0x0023`
a| `17` | Memory device | 2  a| `0x0024`, `0x0028`
a| `18` | 32-bit memory error information | 3  a| `0x0025`, `0x0029`, `0x002C`
a| `19` | Memory array mapped address | 1  a| `0x002D`
a| `20` | Memory device mapped address | 2  a| `0x0027`, `0x002B`
a| `21` | Built-in pointing device | 1  a| `0x000B`
a| `32` | System boot information | 1  a| `0x000C`
a| `40` | Additional information | 1  a| `0x001E`
a| `41` | Onboard devices extended information | 1  a| `0x001F`
a| `127` | End of table | 1  a| `0x0030`
a| `129` | OEM-specific | 1  a| `0x000D`
a| `133` | OEM-specific | 1  a| `0x002F`
|===
== Legion 5 15IMH05H 81Y6 (legion-5-15imh05h-81y6.bin)

[horizontal]
File path:: `lenovo/legion-5-15imh05h-81y6.bin`
Product name:: 81Y6
Product version:: Lenovo Legion 5 15IMH05H
Product family:: Legion 5 15IMH05H
Firmware vendor:: LENOVO
Firmware version:: EFCN52WW
Release date:: 2021-07-27
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 17  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `9` | System slots | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `11` | OEM strings | 1  a| `0x001E`
a| `12` | System configuration options | 1  a| `0x001F`
a| `13` | Firmware language information | 1  a| `0x0020`
a| `14` | Group associations | 2  a| `0x0021`, `0x0022`
a| `15` | System event log | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 2  a| `0x0025`, `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x0029`
a| `21` | Built-in pointing device | 1  a| `0x002A`
a| `22` | Portable battery | 1  a| `0x002B`
a| `24` | Hardware security | 1  a| `0x002C`
a| `26` | Voltage probe | 1  a| `0x002D`
a| `27` | Cooling device | 1  a| `0x002E`
a| `28` | Temperature probe | 1  a| `0x002F`
a| `32` | System boot information | 1  a| `0x0030`
a| `39` | System power supply | 1  a| `0x0031`
a| `40` | Additional information | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 1  a| `0x0033`
a| `43` | TPM device | 1  a| `0x0034`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0035`
a| `129` | OEM-specific | 1  a| `0x0036`
a| `130` | Intel Active Management Technology information | 1  a| `0x0037`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0038`
a| `133` | OEM-specific | 1  a| `0x0039`
a| `136` | OEM-specific | 1  a| `0x003A`
a| `200` | Lenovo machine type model | 1  a| `0x003B`
a| `219` | Intel Management Engine interface information | 1  a| `0x003C`
a| `221` | Intel firmware version information | 6  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0043`
a| `248` | OEM-specific | 1  a| `0x0044`
|===
== ThinkBook 15 G2 ITL 20VE (thinkbook-15-g2-itl-20ve.bin)

[horizontal]
File path:: `lenovo/thinkbook-15-g2-itl-20ve.bin`
Product name:: 20VE
Product version:: ThinkBook 15 G2 ITL
Product family:: ThinkBook 15 G2 ITL
Firmware vendor:: LENOVO
Firmware version:: F8CN46WW(V2.09)
Release date:: 2021-12-24
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 4  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `8` | Port connector information | 17  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `9` | System slots | 5  a| `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0021`
a| `14` | Group associations | 2  a| `0x0022`, `0x0044`
a| `15` | System event log | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 2  a| `0x0025`, `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x0029`
a| `21` | Built-in pointing device | 1  a| `0x002A`
a| `22` | Portable battery | 1  a| `0x002B`
a| `24` | Hardware security | 1  a| `0x002C`
a| `26` | Voltage probe | 1  a| `0x002D`
a| `27` | Cooling device | 1  a| `0x002E`
a| `28` | Temperature probe | 1  a| `0x002F`
a| `32` | System boot information | 1  a| `0x0030`
a| `39` | System power supply | 1  a| `0x0031`
a| `40` | Additional information | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 1  a| `0x0033`
a| `43` | TPM device | 1  a| `0x0034`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0035`
a| `129` | OEM-specific | 1  a| `0x0036`
a| `130` | Intel Active Management Technology information | 1  a| `0x0037`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0038`
a| `133` | OEM-specific | 1  a| `0x0039`
a| `136` | OEM-specific | 1  a| `0x003A`
a| `200` | Lenovo machine type model | 1  a| `0x003B`
a| `219` | Intel Management Engine interface information | 1  a| `0x003C`
a| `221` | Intel firmware version information | 6  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`
a| `248` | OEM-specific | 1  a| `0x0043`
|===
== ThinkCentre M700 10HY (thinkcentre-m700-10hy.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m700-10hy.bin`
Product name:: 10HYS0UG00
Product version:: ThinkCentre M700
Product family:: ThinkCentre M700
Firmware vendor:: LENOVO
Firmware version:: FWKT9EA
Release date:: 2019-04-22
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004B`
a| `7` | Cache information | 4  a| `0x0047`, `0x0048`, `0x0049`, `0x004A`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 4  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `10` | Onboard devices information | 1  a| `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `15` | System event log | 1  a| `0x0050`
a| `16` | Physical memory array | 1  a| `0x004C`
a| `17` | Memory device | 2  a| `0x004D`, `0x004E`
a| `19` | Memory array mapped address | 1  a| `0x004F`
a| `20` | Memory device mapped address | 2  a| `0x0052`, `0x0053`
a| `24` | Hardware security | 1  a| `0x002D`
a| `26` | Voltage probe | 2  a| `0x0030`, `0x003F`
a| `27` | Cooling device | 3  a| `0x0036`, `0x0039`, `0x0041`
a| `28` | Temperature probe | 2  a| `0x0033`, `0x0040`
a| `29` | Electrical current probe | 2  a| `0x003C`, `0x0042`
a| `32` | System boot information | 1  a| `0x002E`
a| `34` | Management device | 1  a| `0x002F`
a| `35` | Management device component | 5  a| `0x0032`, `0x0035`, `0x0038`, `0x003B`, `0x003E`
a| `36` | Management device threshold data | 5  a| `0x0031`, `0x0034`, `0x0037`, `0x003A`, `0x003D`
a| `39` | System power supply | 1  a| `0x0043`
a| `41` | Onboard devices extended information | 3  a| `0x0044`, `0x0045`, `0x0046`
a| `127` | End of table | 1  a| `0x0000`
a| `130` | Intel Active Management Technology information | 1  a| `0x0054`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0055`
a| `133` | OEM-specific | 1  a| `0x0051`
a| `140` | Lenovo ThinkPad embedded controller program | 1  a| `0x005B`
a| `221` | Intel firmware version information | 5  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`
|===
== ThinkCentre M70s 11DB (thinkcentre-m70s-11db.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m70s-11db.bin`
Product name:: 11DBSA6W00
Product version:: ThinkCentre M70s
Product family:: ThinkCentre M70s
Firmware vendor:: LENOVO
Firmware version:: M2TKT56A
Release date:: 2023-09-06
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0053`
a| `7` | Cache information | 3  a| `0x0050`, `0x0051`, `0x0052`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x003C`
a| `17` | Memory device | 4  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `19` | Memory array mapped address | 1  a| `0x0041`
a| `20` | Memory device mapped address | 2  a| `0x0048`, `0x0049`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 8  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`
a| `43` | TPM device | 1  a| `0x003B`
a| `127` | End of table | 1  a| `0x0000`
a| `130` | Intel Active Management Technology information | 1  a| `0x0054`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0055`
a| `133` | OEM-specific | 1  a| `0x0047`
a| `221` | Intel firmware version information | 6  a| `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`
|===
== ThinkCentre M720q 10T8 (thinkcentre-m720q-10t8.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m720q-10t8.bin`
Product name:: 10T8SMC200
Product version:: ThinkCentre M720q
Product family:: ThinkCentre M720q
Firmware vendor:: LENOVO
Firmware version:: M1UKT78A
Release date:: 2025-12-04
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0048`
a| `7` | Cache information | 3  a| `0x0045`, `0x0046`, `0x0047`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0062`
a| `14` | Group associations | 2  a| `0x0061`, `0x0063`
a| `15` | System event log | 1  a| `0x003F`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 2  a| `0x003C`, `0x003D`
a| `19` | Memory array mapped address | 1  a| `0x003E`
a| `20` | Memory device mapped address | 2  a| `0x004E`, `0x004F`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 12  a| `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`
a| `43` | TPM device | 1  a| `0x0049`
a| `127` | End of table | 1  a| `0x0065`
a| `130` | Intel Active Management Technology information | 1  a| `0x0050`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0051`, `0x005F`
a| `133` | OEM-specific | 1  a| `0x004A`
a| `136` | OEM-specific | 1  a| `0x0060`
a| `219` | Intel Management Engine interface information | 1  a| `0x0064`
a| `221` | Intel firmware version information | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x005E`
|===
== ThinkCentre M720s 10ST (thinkcentre-m720s-10st.bin)

[horizontal]
File path:: `lenovo/thinkcentre-m720s-10st.bin`
Product name:: 10STS04K00
Product version:: ThinkCentre M720s
Product family:: ThinkCentre M720s
Firmware vendor:: LENOVO
Firmware version:: M1UKT59A
Release date:: 2020-07-07
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004A`
a| `7` | Cache information | 3  a| `0x0047`, `0x0048`, `0x0049`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0066`
a| `14` | Group associations | 2  a| `0x0065`, `0x0067`
a| `15` | System event log | 1  a| `0x0041`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 4  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `19` | Memory array mapped address | 1  a| `0x0040`
a| `20` | Memory device mapped address | 3  a| `0x0051`, `0x0052`, `0x0053`
a| `24` | Hardware security | 1  a| `0x0024`
a| `26` | Voltage probe | 2  a| `0x0027`, `0x0036`
a| `27` | Cooling device | 3  a| `0x002D`, `0x0030`, `0x0038`
a| `28` | Temperature probe | 2  a| `0x002A`, `0x0037`
a| `29` | Electrical current probe | 2  a| `0x0033`, `0x0039`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 1  a| `0x0026`
a| `35` | Management device component | 5  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`
a| `36` | Management device threshold data | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `39` | System power supply | 1  a| `0x003A`
a| `41` | Onboard devices extended information | 12  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`
a| `43` | TPM device | 1  a| `0x004B`
a| `127` | End of table | 1  a| `0x0069`
a| `130` | Intel Active Management Technology information | 1  a| `0x0054`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0055`, `0x0063`
a| `133` | OEM-specific | 1  a| `0x004C`
a| `136` | OEM-specific | 1  a| `0x0064`
a| `219` | Intel Management Engine interface information | 1  a| `0x0068`
a| `221` | Intel firmware version information | 6  a| `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0062`
|===
== ThinkPad E14 Gen 5 21JR (thinkpad-e14-gen-5-21jr.bin)

[horizontal]
File path:: `lenovo/thinkpad-e14-gen-5-21jr.bin`
Product name:: 21JR002WGE
Product version:: ThinkPad E14 Gen 5
Product family:: ThinkPad E14 Gen 5
Firmware vendor:: LENOVO
Firmware version:: R2CET46W(1.28)
Release date:: 2025-09-18
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000E`
a| `1` | System information | 1  a| `0x000F`
a| `2` | Baseboard or module information | 1  a| `0x0010`
a| `3` | System enclosure or chassis | 1  a| `0x0011`
a| `4` | Processor information | 1  a| `0x0006`
a| `7` | Cache information | 3  a| `0x0003`, `0x0004`, `0x0005`
a| `8` | Port connector information | 6  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x001C`, `0x0020`
a| `9` | System slots | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0024`
a| `15` | System event log | 1  a| `0x0030`
a| `16` | Physical memory array | 1  a| `0x0001`
a| `17` | Memory device | 2  a| `0x0008`, `0x000B`
a| `18` | 32-bit memory error information | 4  a| `0x0000`, `0x0007`, `0x000A`, `0x0029`
a| `19` | Memory array mapped address | 1  a| `0x0002`
a| `20` | Memory device mapped address | 2  a| `0x0009`, `0x000C`
a| `21` | Built-in pointing device | 2  a| `0x002A`, `0x002B`
a| `22` | Portable battery | 1  a| `0x0025`
a| `24` | Hardware security | 1  a| `0x002E`
a| `126` | Inactive | 11  a| `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001D`, `0x001E`, `0x001F`, `0x0021`, `0x0026`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x002C`
a| `132` | OEM-specific | 1  a| `0x002F`
a| `134` | Lenovo date record | 1  a| `0x000D`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0028`, `0x0036`
a| `136` | OEM-specific | 1  a| `0x002D`
a| `140` | Lenovo ThinkPad embedded controller program | 2  a| `0x0027`, `0x0037`
a| `141` | OEM-specific | 5  a| `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`
|===
== ThinkPad L15 Gen 1 20U4 (thinkpad-l15-gen-1-20u4.bin)

[horizontal]
File path:: `lenovo/thinkpad-l15-gen-1-20u4.bin`
Product name:: 20U4S4EQ00
Product version:: ThinkPad L15 Gen 1
Product family:: ThinkPad L15 Gen 1
Firmware vendor:: LENOVO
Firmware version:: R17ET31W (1.14 )
Release date:: 2021-08-13
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0011`
a| `1` | System information | 1  a| `0x0012`
a| `2` | Baseboard or module information | 1  a| `0x0013`
a| `3` | System enclosure or chassis | 1  a| `0x0014`
a| `4` | Processor information | 1  a| `0x0010`
a| `7` | Cache information | 3  a| `0x000D`, `0x000E`, `0x000F`
a| `8` | Port connector information | 7  a| `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x001E`, `0x0020`, `0x0024`
a| `9` | System slots | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `14` | Group associations | 2  a| `0x0001`, `0x0032`
a| `15` | System event log | 1  a| `0x0039`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0034`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0035`, `0x0036`
a| `22` | Portable battery | 1  a| `0x0029`
a| `24` | Hardware security | 1  a| `0x0030`
a| `126` | Inactive | 11  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0021`, `0x0022`, `0x0023`, `0x0025`, `0x002A`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x002E`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x002F`, `0x0037`
a| `132` | OEM-specific | 1  a| `0x0031`
a| `133` | OEM-specific | 1  a| `0x002C`
a| `134` | Lenovo date record | 1  a| `0x0002`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x002D`, `0x0043`
a| `136` | OEM-specific | 1  a| `0x0038`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x002B`, `0x003A`, `0x003B`, `0x0041`, `0x0042`
a| `141` | OEM-specific | 5  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `219` | Intel Management Engine interface information | 1  a| `0x0033`
a| `221` | Intel firmware version information | 6  a| `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad L420 7854 (thinkpad-l420-7854.bin)

[horizontal]
File path:: `lenovo/thinkpad-l420-7854.bin`
Product name:: 78544KM
Product version:: ThinkPad L420
Product family:: ThinkPad L420
Firmware vendor:: LENOVO
Firmware version:: 8GET46WW (1.23 )
Release date:: 2013-09-16
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 8  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`
a| `9` | System slots | 8  a| `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`
a| `10` | Onboard devices information | 1  a| `0x0018`
a| `11` | OEM strings | 1  a| `0x0019`
a| `15` | System event log | 1  a| `0x001A`
a| `16` | Physical memory array | 1  a| `0x001B`
a| `17` | Memory device | 4  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `18` | 32-bit memory error information | 2  a| `0x0020`, `0x0021`
a| `19` | Memory array mapped address | 1  a| `0x0022`
a| `20` | Memory device mapped address | 2  a| `0x0023`, `0x0024`
a| `21` | Built-in pointing device | 1  a| `0x0025`
a| `32` | System boot information | 1  a| `0x0026`
a| `127` | End of table | 1  a| `0x0030`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0027`
a| `133` | OEM-specific | 1  a| `0x0028`
a| `134` | Lenovo date record | 1  a| `0x0029`
a| `135` | Lenovo ThinkPad device presence detection | 5  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `200` | Lenovo machine type model | 1  a| `0x002F`
|===
== ThinkPad T14 Gen 2a 20XK (thinkpad-t14-g2a-20xk.bin)

[horizontal]
File path:: `lenovo/thinkpad-t14-g2a-20xk.bin`
Product name:: 20XKA001CD
Product version:: ThinkPad T14 Gen 2a
Product family:: ThinkPad T14 Gen 2a
Firmware vendor:: LENOVO
Firmware version:: R1MET62W (1.32 )
Release date:: 2025-06-26
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000E`
a| `1` | System information | 1  a| `0x000F`
a| `2` | Baseboard or module information | 1  a| `0x0010`
a| `3` | System enclosure or chassis | 1  a| `0x0011`
a| `4` | Processor information | 1  a| `0x0006`
a| `7` | Cache information | 3  a| `0x0003`, `0x0004`, `0x0005`
a| `8` | Port connector information | 15  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `9` | System slots | 6  a| `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`
a| `10` | Onboard devices information | 4  a| `0x0027`, `0x0028`, `0x0029`, `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0038`
a| `16` | Physical memory array | 1  a| `0x0001`
a| `17` | Memory device | 2  a| `0x0008`, `0x000B`
a| `18` | 32-bit memory error information | 4  a| `0x0000`, `0x0007`, `0x000A`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0002`
a| `20` | Memory device mapped address | 2  a| `0x0009`, `0x000C`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x0036`
a| `126` | Inactive | 1  a| `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0034`
a| `132` | OEM-specific | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x002E`
a| `134` | Lenovo date record | 1  a| `0x000D`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0030`, `0x0043`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x002F`, `0x003E`, `0x003F`, `0x0040`, `0x0041`
a| `141` | OEM-specific | 6  a| `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x0042`
|===
== ThinkPad T14 Gen 3 21AJ (thinkpad-t14-g3-21aj.bin)

[horizontal]
File path:: `lenovo/thinkpad-t14-g3-21aj.bin`
Product name:: 21AJS3EP26
Product version:: ThinkPad T14 Gen 3
Product family:: ThinkPad T14 Gen 3
Firmware vendor:: LENOVO
Firmware version:: N3MET26W (1.25 )
Release date:: 2025-09-28
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x001B`
a| `1` | System information | 1  a| `0x001C`
a| `2` | Baseboard or module information | 1  a| `0x001D`
a| `3` | System enclosure or chassis | 1  a| `0x001E`
a| `4` | Processor information | 1  a| `0x001A`
a| `7` | Cache information | 8  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `8` | Port connector information | 6  a| `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0029`, `0x002D`
a| `9` | System slots | 1  a| `0x002F`
a| `12` | System configuration options | 1  a| `0x0030`
a| `13` | Firmware language information | 1  a| `0x0031`
a| `14` | Group associations | 1  a| `0x003A`
a| `15` | System event log | 1  a| `0x0043`
a| `16` | Physical memory array | 1  a| `0x0001`
a| `17` | Memory device | 8  a| `0x0002`, `0x0003`, `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `18` | 32-bit memory error information | 1  a| `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x000A`
a| `21` | Built-in pointing device | 2  a| `0x003F`, `0x0040`
a| `22` | Portable battery | 1  a| `0x0032`
a| `24` | Hardware security | 1  a| `0x003C`
a| `43` | TPM device | 1  a| `0x000B`
a| `126` | Inactive | 11  a| `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x002A`, `0x002B`, `0x002C`, `0x002E`, `0x0033`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0037`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0038`, `0x0041`
a| `132` | OEM-specific | 1  a| `0x003D`
a| `133` | OEM-specific | 2  a| `0x0034`, `0x0035`
a| `134` | Lenovo date record | 1  a| `0x0000`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0036`, `0x004B`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0039`, `0x0044`, `0x0045`, `0x004C`, `0x004D`
a| `141` | OEM-specific | 6  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004E`
a| `219` | Intel Management Engine interface information | 1  a| `0x003B`
a| `221` | Intel firmware version information | 6  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`
|===
== ThinkPad T14 Gen 1 20S1 (thinkpad-t14-gen-1-20s1.bin)

[horizontal]
File path:: `lenovo/thinkpad-t14-gen-1-20s1.bin`
Product name:: 20S1SDTK00
Product version:: ThinkPad T14 Gen 1
Product family:: ThinkPad T14 Gen 1
Firmware vendor:: LENOVO
Firmware version:: N2XET44W (1.34 )
Release date:: 2025-10-27
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0011`
a| `1` | System information | 1  a| `0x0012`
a| `2` | Baseboard or module information | 1  a| `0x0013`
a| `3` | System enclosure or chassis | 1  a| `0x0014`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 7  a| `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x001E`, `0x0020`, `0x0024`
a| `9` | System slots | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `14` | Group associations | 2  a| `0x0001`, `0x0032`
a| `15` | System event log | 1  a| `0x0039`
a| `16` | Physical memory array | 1  a| `0x0002`
a| `17` | Memory device | 2  a| `0x0003`, `0x0004`
a| `18` | 32-bit memory error information | 1  a| `0x0034`
a| `19` | Memory array mapped address | 1  a| `0x0005`
a| `21` | Built-in pointing device | 2  a| `0x0035`, `0x0036`
a| `22` | Portable battery | 1  a| `0x0029`
a| `24` | Hardware security | 1  a| `0x0030`
a| `126` | Inactive | 11  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0021`, `0x0022`, `0x0023`, `0x0025`, `0x002A`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x002E`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x002F`, `0x0037`
a| `132` | OEM-specific | 1  a| `0x0031`
a| `133` | OEM-specific | 1  a| `0x002C`
a| `134` | Lenovo date record | 1  a| `0x0010`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x002D`, `0x0044`
a| `136` | OEM-specific | 1  a| `0x0038`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x002B`, `0x003F`, `0x0040`, `0x0041`, `0x0042`
a| `141` | OEM-specific | 6  a| `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x0043`
a| `219` | Intel Management Engine interface information | 1  a| `0x0033`
a| `221` | Intel firmware version information | 6  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad T430 2347 (thinkpad-t430-2347.bin)

[horizontal]
File path:: `lenovo/thinkpad-t430-2347.bin`
Product name:: 2347A49
Product version:: ThinkPad T430
Product family:: ThinkPad T430
Firmware vendor:: LENOVO
Firmware version:: G1ET45WW (1.20 )
Release date:: 2012-08-07
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000E`
a| `1` | System information | 1  a| `0x000F`
a| `2` | Baseboard or module information | 1  a| `0x0010`
a| `3` | System enclosure or chassis | 1  a| `0x0011`
a| `4` | Processor information | 1  a| `0x0001`
a| `7` | Cache information | 4  a| `0x0002`, `0x0003`, `0x0004`, `0x0005`
a| `8` | Port connector information | 8  a| `0x0012`, `0x0013`, `0x0016`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `9` | System slots | 2  a| `0x0028`, `0x0029`
a| `10` | Onboard devices information | 1  a| `0x002B`
a| `12` | System configuration options | 1  a| `0x002C`
a| `13` | Firmware language information | 1  a| `0x002D`
a| `15` | System event log | 1  a| `0x0039`
a| `16` | Physical memory array | 1  a| `0x0007`
a| `17` | Memory device | 2  a| `0x0008`, `0x0009`
a| `18` | 32-bit memory error information | 1  a| `0x0030`
a| `19` | Memory array mapped address | 1  a| `0x000C`
a| `20` | Memory device mapped address | 2  a| `0x000A`, `0x000B`
a| `21` | Built-in pointing device | 2  a| `0x0031`, `0x0032`
a| `22` | Portable battery | 1  a| `0x002E`
a| `24` | Hardware security | 1  a| `0x003F`
a| `126` | Inactive | 16  a| `0x0014`, `0x0015`, `0x0017`, `0x0018`, `0x001A`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x002A`, `0x002F`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x0006`
a| `130` | Intel Active Management Technology information | 1  a| `0x0035`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0033`, `0x0036`
a| `132` | OEM-specific | 1  a| `0x0040`
a| `133` | OEM-specific | 1  a| `0x0038`
a| `134` | Lenovo date record | 2  a| `0x0000`, `0x000D`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0037`, `0x0041`
a| `136` | OEM-specific | 1  a| `0x0034`
a| `140` | Lenovo ThinkPad embedded controller program | 7  a| `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x0042`, `0x0043`
|===
== ThinkPad T480s 20L8 (thinkpad-t480s-20l8.bin)

[horizontal]
File path:: `lenovo/thinkpad-t480s-20l8.bin`
Product name:: 20L8S07A14
Product version:: ThinkPad T480s
Product family:: ThinkPad T480s
Firmware vendor:: LENOVO
Firmware version:: N22ET52W (1.29 )
Release date:: 2019-01-16
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000B`
a| `1` | System information | 1  a| `0x000C`
a| `2` | Baseboard or module information | 1  a| `0x000D`
a| `3` | System enclosure or chassis | 1  a| `0x000E`
a| `4` | Processor information | 1  a| `0x000A`
a| `7` | Cache information | 3  a| `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 7  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0018`, `0x001A`, `0x001E`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `14` | Group associations | 2  a| `0x0001`, `0x003C`
a| `15` | System event log | 1  a| `0x002E`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0024`
a| `24` | Hardware security | 1  a| `0x002F`
a| `126` | Inactive | 11  a| `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0025`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0028`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0029`, `0x0034`
a| `132` | OEM-specific | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x0026`
a| `134` | Lenovo date record | 1  a| `0x0002`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0027`, `0x003B`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `219` | Intel Management Engine interface information | 1  a| `0x003D`
a| `221` | Intel firmware version information | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad T490 20N2 (thinkpad-t490-20n2.bin)

[horizontal]
File path:: `lenovo/thinkpad-t490-20n2.bin`
Product name:: 20N2CTO1WW
Product version:: ThinkPad T490
Product family:: ThinkPad T490
Firmware vendor:: LENOVO
Firmware version:: N2IET92W (1.70 )
Release date:: 2020-09-21
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0011`
a| `1` | System information | 1  a| `0x0012`
a| `2` | Baseboard or module information | 1  a| `0x0013`
a| `3` | System enclosure or chassis | 1  a| `0x0014`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 7  a| `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x001E`, `0x0021`, `0x0026`
a| `9` | System slots | 2  a| `0x0028`, `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `14` | Group associations | 2  a| `0x0001`, `0x003E`
a| `15` | System event log | 1  a| `0x003A`
a| `16` | Physical memory array | 1  a| `0x0002`
a| `17` | Memory device | 2  a| `0x0003`, `0x0004`
a| `18` | 32-bit memory error information | 1  a| `0x0035`
a| `19` | Memory array mapped address | 1  a| `0x0005`
a| `21` | Built-in pointing device | 2  a| `0x0036`, `0x0037`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x0033`
a| `126` | Inactive | 13  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0020`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0027`, `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0031`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0032`, `0x0038`
a| `132` | OEM-specific | 1  a| `0x0034`
a| `133` | OEM-specific | 1  a| `0x002F`
a| `134` | Lenovo date record | 1  a| `0x0010`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0030`, `0x0043`
a| `136` | OEM-specific | 1  a| `0x0039`
a| `140` | Lenovo ThinkPad embedded controller program | 6  a| `0x002E`, `0x003B`, `0x003C`, `0x003D`, `0x0040`, `0x0041`
a| `141` | OEM-specific | 1  a| `0x0042`
a| `219` | Intel Management Engine interface information | 1  a| `0x003F`
a| `221` | Intel firmware version information | 6  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad T490 20N3 (thinkpad-t490-20n3.bin)

[horizontal]
File path:: `lenovo/thinkpad-t490-20n3.bin`
Product name:: 20N3000KGE
Product version:: ThinkPad T490
Product family:: ThinkPad T490
Firmware vendor:: LENOVO
Firmware version:: N2IETA1W (1.79 )
Release date:: 2023-01-16
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0011`
a| `1` | System information | 1  a| `0x0012`
a| `2` | Baseboard or module information | 1  a| `0x0013`
a| `3` | System enclosure or chassis | 1  a| `0x0014`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 7  a| `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x001E`, `0x0021`, `0x0026`
a| `9` | System slots | 2  a| `0x0028`, `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `14` | Group associations | 2  a| `0x0001`, `0x003D`
a| `15` | System event log | 1  a| `0x003A`
a| `16` | Physical memory array | 1  a| `0x0002`
a| `17` | Memory device | 2  a| `0x0003`, `0x0004`
a| `18` | 32-bit memory error information | 1  a| `0x0035`
a| `19` | Memory array mapped address | 1  a| `0x0005`
a| `21` | Built-in pointing device | 2  a| `0x0036`, `0x0037`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x0033`
a| `126` | Inactive | 13  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0020`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0027`, `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0031`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0032`, `0x0038`
a| `132` | OEM-specific | 1  a| `0x0034`
a| `133` | OEM-specific | 1  a| `0x002F`
a| `134` | Lenovo date record | 1  a| `0x0010`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0030`, `0x0042`
a| `136` | OEM-specific | 1  a| `0x0039`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x002E`, `0x003B`, `0x003C`, `0x003F`, `0x0040`
a| `141` | OEM-specific | 1  a| `0x0041`
a| `219` | Intel Management Engine interface information | 1  a| `0x003E`
a| `221` | Intel firmware version information | 6  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad T61p 6460-6XG (thinkpad-t61p-6460-6xg.bin)

[horizontal]
File path:: `lenovo/thinkpad-t61p-6460-6xg.bin`
Product name:: 64606XG
Product version:: ThinkPad T61p
Product family:: ThinkPad T61p
Firmware vendor:: LENOVO
Firmware version:: 7LET56WW (1.26 )
Release date:: 2007-10-18
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0006`
a| `5` | Memory controller information | 1  a| `0x0007`
a| `6` | Memory module information | 2  a| `0x0008`, `0x0009`
a| `7` | Cache information | 3  a| `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 9  a| `0x000D`, `0x000E`, `0x000F`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x001F`
a| `9` | System slots | 3  a| `0x0020`, `0x0021`, `0x0024`
a| `10` | Onboard devices information | 1  a| `0x0027`
a| `11` | OEM strings | 1  a| `0x0028`
a| `13` | Firmware language information | 1  a| `0x0029`
a| `15` | System event log | 1  a| `0x002A`
a| `16` | Physical memory array | 1  a| `0x002B`
a| `17` | Memory device | 2  a| `0x002C`, `0x002D`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x002F`
a| `20` | Memory device mapped address | 2  a| `0x0030`, `0x0031`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0034`
a| `24` | Hardware security | 1  a| `0x0036`
a| `32` | System boot information | 1  a| `0x0037`
a| `126` | Inactive | 17  a| `0x0004`, `0x0005`, `0x0010`, `0x0011`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x0022`, `0x0023`, `0x0025`, `0x0026`, `0x0035`
a| `127` | End of table | 1  a| `0x0048`
a| `129` | OEM-specific | 1  a| `0x0046`
a| `130` | Intel Active Management Technology information | 1  a| `0x0047`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0038`, `0x0039`
a| `132` | OEM-specific | 1  a| `0x003A`
a| `133` | OEM-specific | 1  a| `0x003B`
a| `134` | Lenovo date record | 2  a| `0x003C`, `0x003D`
a| `135` | Lenovo ThinkPad device presence detection | 4  a| `0x003E`, `0x003F`, `0x0040`, `0x0041`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `137` | OEM-specific | 1  a| `0x0043`
a| `138` | OEM-specific | 1  a| `0x0044`
a| `139` | OEM-specific | 1  a| `0x0045`
|===
== ThinkPad W510 4319 (thinkpad-w510-4319.bin)

[horizontal]
File path:: `lenovo/thinkpad-w510-4319.bin`
Product name:: 431924G
Product version:: ThinkPad W510
Product family:: ThinkPad W510
Firmware vendor:: LENOVO
Firmware version:: 6NET84WW (1.45 )
Release date:: 2012-10-03
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0006`
a| `5` | Memory controller information | 1  a| `0x0007`
a| `6` | Memory module information | 4  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 10  a| `0x000F`, `0x0010`, `0x0013`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x0023`
a| `9` | System slots | 3  a| `0x0025`, `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0028`
a| `11` | OEM strings | 1  a| `0x0029`
a| `13` | Firmware language information | 1  a| `0x002A`
a| `15` | System event log | 1  a| `0x002B`
a| `16` | Physical memory array | 1  a| `0x002C`
a| `17` | Memory device | 4  a| `0x002D`, `0x002E`, `0x002F`, `0x0030`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 2  a| `0x0033`, `0x0034`
a| `21` | Built-in pointing device | 2  a| `0x0035`, `0x0036`
a| `22` | Portable battery | 1  a| `0x0037`
a| `24` | Hardware security | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `126` | Inactive | 15  a| `0x0004`, `0x0005`, `0x0011`, `0x0012`, `0x0014`, `0x0015`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0024`, `0x0038`
a| `127` | End of table | 1  a| `0x0051`
a| `129` | OEM-specific | 1  a| `0x004E`
a| `130` | Intel Active Management Technology information | 1  a| `0x004F`
a| `131` | Lenovo ThinkVantage Technologies enablement | 3  a| `0x003B`, `0x003C`, `0x0050`
a| `132` | OEM-specific | 1  a| `0x003D`
a| `133` | OEM-specific | 1  a| `0x003E`
a| `134` | Lenovo date record | 2  a| `0x003F`, `0x0040`
a| `135` | Lenovo ThinkPad device presence detection | 5  a| `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`
a| `136` | OEM-specific | 1  a| `0x0046`
a| `140` | Lenovo ThinkPad embedded controller program | 7  a| `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`
|===
== ThinkPad X1 Tablet Gen 3 20KK (thinkpad-x1-tablet-gen-3-20kk.bin)

[horizontal]
File path:: `lenovo/thinkpad-x1-tablet-gen-3-20kk.bin`
Product name:: 20KKS70000
Product version:: ThinkPad X1 Tablet Gen 3
Product family:: ThinkPad X1 Tablet Gen 3
Firmware vendor:: LENOVO
Firmware version:: N1ZET95W(1.51 )
Release date:: 2024-11-15
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000B`
a| `1` | System information | 1  a| `0x000C`
a| `2` | Baseboard or module information | 1  a| `0x000D`
a| `3` | System enclosure or chassis | 1  a| `0x000E`
a| `4` | Processor information | 1  a| `0x000A`
a| `7` | Cache information | 3  a| `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 7  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0018`, `0x001A`, `0x001E`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `14` | Group associations | 2  a| `0x0001`, `0x003C`
a| `15` | System event log | 1  a| `0x002E`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0024`
a| `24` | Hardware security | 1  a| `0x002F`
a| `126` | Inactive | 11  a| `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0025`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0028`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0029`, `0x0034`
a| `132` | OEM-specific | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x0026`
a| `134` | Lenovo date record | 1  a| `0x0002`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0027`, `0x003B`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `219` | Intel Management Engine interface information | 1  a| `0x003D`
a| `221` | Intel firmware version information | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad X131e 3367 (thinkpad-x131e-3367.bin)

[horizontal]
File path:: `lenovo/thinkpad-x131e-3367.bin`
Product name:: 3367A15
Product version:: ThinkPad X131e
Product family:: ThinkPad X131e
Firmware vendor:: LENOVO
Firmware version:: G8ETB4WW (3.01 )
Release date:: 2019-09-11
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000C`
a| `1` | System information | 1  a| `0x000D`
a| `2` | Baseboard or module information | 1  a| `0x000E`
a| `3` | System enclosure or chassis | 1  a| `0x000F`
a| `4` | Processor information | 1  a| `0x0001`
a| `7` | Cache information | 4  a| `0x0002`, `0x0003`, `0x0004`, `0x0005`
a| `8` | Port connector information | 11  a| `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`
a| `9` | System slots | 1  a| `0x001B`
a| `10` | Onboard devices information | 1  a| `0x001C`
a| `12` | System configuration options | 1  a| `0x001D`
a| `13` | Firmware language information | 1  a| `0x001E`
a| `15` | System event log | 1  a| `0x002B`
a| `16` | Physical memory array | 1  a| `0x0007`
a| `17` | Memory device | 2  a| `0x0008`, `0x0009`
a| `18` | 32-bit memory error information | 1  a| `0x0023`
a| `19` | Memory array mapped address | 1  a| `0x000A`
a| `21` | Built-in pointing device | 2  a| `0x0024`, `0x0025`
a| `22` | Portable battery | 1  a| `0x001F`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x0006`
a| `130` | Intel Active Management Technology information | 1  a| `0x0027`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0020`, `0x0028`
a| `133` | OEM-specific | 1  a| `0x0029`
a| `134` | Lenovo date record | 2  a| `0x0000`, `0x000B`
a| `135` | Lenovo ThinkPad device presence detection | 3  a| `0x0021`, `0x002A`, `0x002C`
a| `136` | OEM-specific | 1  a| `0x0026`
a| `140` | Lenovo ThinkPad embedded controller program | 2  a| `0x002D`, `0x002E`
a| `200` | Lenovo machine type model | 1  a| `0x0022`
|===
== ThinkPad X220 4290LE6 (thinkpad-x220-4290le6.bin)

[horizontal]
File path:: `lenovo/thinkpad-x220-4290le6.bin`
Product name:: 4290LE6
Product version:: ThinkPad X220
Product family:: ThinkPad X220
Firmware vendor:: LENOVO
Firmware version:: 8DET76WW (1.46 )
Release date:: 2018-06-21
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000D`
a| `1` | System information | 1  a| `0x000E`
a| `2` | Baseboard or module information | 1  a| `0x000F`
a| `3` | System enclosure or chassis | 1  a| `0x0010`
a| `4` | Processor information | 1  a| `0x0001`
a| `7` | Cache information | 3  a| `0x0002`, `0x0003`, `0x0004`
a| `8` | Port connector information | 8  a| `0x0011`, `0x0012`, `0x0015`, `0x0018`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 2  a| `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0029`
a| `12` | System configuration options | 1  a| `0x002A`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `15` | System event log | 1  a| `0x0036`
a| `16` | Physical memory array | 1  a| `0x0005`
a| `17` | Memory device | 2  a| `0x0006`, `0x0007`
a| `18` | 32-bit memory error information | 1  a| `0x002E`
a| `19` | Memory array mapped address | 1  a| `0x0008`
a| `21` | Built-in pointing device | 2  a| `0x002F`, `0x0030`
a| `22` | Portable battery | 1  a| `0x002C`
a| `24` | Hardware security | 1  a| `0x003C`
a| `126` | Inactive | 15  a| `0x0013`, `0x0014`, `0x0016`, `0x0017`, `0x0019`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0028`, `0x002D`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x0009`
a| `130` | Intel Active Management Technology information | 1  a| `0x000A`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x000B`, `0x0031`
a| `132` | OEM-specific | 1  a| `0x003D`
a| `133` | OEM-specific | 1  a| `0x0035`
a| `134` | Lenovo date record | 2  a| `0x0000`, `0x000C`
a| `135` | Lenovo ThinkPad device presence detection | 3  a| `0x0033`, `0x0034`, `0x003E`
a| `136` | OEM-specific | 1  a| `0x0032`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`
|===
== ThinkPad X240 20AM (thinkpad-x240-20am.bin)

[horizontal]
File path:: `lenovo/thinkpad-x240-20am.bin`
Product name:: 20AMS1JB0B
Product version:: ThinkPad X240
Product family:: ThinkPad X240
Firmware vendor:: LENOVO
Firmware version:: GIET69WW (2.19 )
Release date:: 2014-02-06
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x002F`
a| `1` | System information | 1  a| `0x000B`
a| `2` | Baseboard or module information | 1  a| `0x000C`
a| `3` | System enclosure or chassis | 1  a| `0x000D`
a| `4` | Processor information | 1  a| `0x0000`
a| `7` | Cache information | 4  a| `0x0001`, `0x0002`, `0x0003`, `0x0004`
a| `8` | Port connector information | 6  a| `0x000E`, `0x000F`, `0x0016`, `0x0017`, `0x0018`, `0x001B`
a| `9` | System slots | 2  a| `0x001D`, `0x001F`
a| `10` | Onboard devices information | 1  a| `0x0020`
a| `12` | System configuration options | 1  a| `0x0021`
a| `13` | Firmware language information | 1  a| `0x0022`
a| `15` | System event log | 1  a| `0x0030`
a| `16` | Physical memory array | 1  a| `0x0005`
a| `17` | Memory device | 1  a| `0x0006`
a| `18` | 32-bit memory error information | 1  a| `0x0025`
a| `19` | Memory array mapped address | 1  a| `0x0007`
a| `21` | Built-in pointing device | 2  a| `0x0026`, `0x0027`
a| `22` | Portable battery | 2  a| `0x0023`, `0x0024`
a| `24` | Hardware security | 1  a| `0x0037`
a| `126` | Inactive | 10  a| `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0019`, `0x001A`, `0x001C`, `0x001E`
a| `127` | End of table | 1  a| `0xFEFF`
a| `129` | OEM-specific | 1  a| `0x0008`
a| `130` | Intel Active Management Technology information | 1  a| `0x002B`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0028`, `0x002C`
a| `132` | OEM-specific | 1  a| `0x0038`
a| `133` | OEM-specific | 1  a| `0x002D`
a| `134` | Lenovo date record | 2  a| `0x0009`, `0x002A`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x002E`, `0x0039`
a| `136` | OEM-specific | 1  a| `0x0029`
a| `140` | Lenovo ThinkPad embedded controller program | 8  a| `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x003A`, `0x003B`
|===
== ThinkPad X280 20KE (thinkpad-x280-20ke.bin)

[horizontal]
File path:: `lenovo/thinkpad-x280-20ke.bin`
Product name:: 20KES35900
Product version:: ThinkPad X280
Product family:: ThinkPad X280
Firmware vendor:: LENOVO
Firmware version:: N20ET64W (1.49 )
Release date:: 2022-11-21
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000B`
a| `1` | System information | 1  a| `0x000C`
a| `2` | Baseboard or module information | 1  a| `0x000D`
a| `3` | System enclosure or chassis | 1  a| `0x000E`
a| `4` | Processor information | 1  a| `0x000A`
a| `7` | Cache information | 3  a| `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 7  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0018`, `0x001A`, `0x001E`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `14` | Group associations | 2  a| `0x0001`, `0x0039`
a| `15` | System event log | 1  a| `0x002E`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0024`
a| `24` | Hardware security | 1  a| `0x002F`
a| `126` | Inactive | 11  a| `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0025`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0028`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0029`, `0x0034`
a| `132` | OEM-specific | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x0026`
a| `134` | Lenovo date record | 1  a| `0x0002`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0027`, `0x003B`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0036`, `0x0037`, `0x0038`, `0x003C`, `0x003D`
a| `219` | Intel Management Engine interface information | 1  a| `0x003A`
a| `221` | Intel firmware version information | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== ThinkPad X280 20KF (thinkpad-x280-20kf.bin)

[horizontal]
File path:: `lenovo/thinkpad-x280-20kf.bin`
Product name:: 20KFCTO1WW
Product version:: ThinkPad X280
Product family:: ThinkPad X280
Firmware vendor:: LENOVO
Firmware version:: N20ET56W (1.41 )
Release date:: 2020-10-08
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000B`
a| `1` | System information | 1  a| `0x000C`
a| `2` | Baseboard or module information | 1  a| `0x000D`
a| `3` | System enclosure or chassis | 1  a| `0x000E`
a| `4` | Processor information | 1  a| `0x000A`
a| `7` | Cache information | 3  a| `0x0007`, `0x0008`, `0x0009`
a| `8` | Port connector information | 7  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0018`, `0x001A`, `0x001E`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `14` | Group associations | 2  a| `0x0001`, `0x0039`
a| `15` | System event log | 1  a| `0x002E`
a| `16` | Physical memory array | 1  a| `0x0003`
a| `17` | Memory device | 2  a| `0x0004`, `0x0005`
a| `18` | 32-bit memory error information | 1  a| `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0006`
a| `21` | Built-in pointing device | 2  a| `0x0032`, `0x0033`
a| `22` | Portable battery | 1  a| `0x0024`
a| `24` | Hardware security | 1  a| `0x002F`
a| `126` | Inactive | 11  a| `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0019`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0025`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x0028`
a| `131` | Lenovo ThinkVantage Technologies enablement | 2  a| `0x0029`, `0x0034`
a| `132` | OEM-specific | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x0026`
a| `134` | Lenovo date record | 1  a| `0x0002`
a| `135` | Lenovo ThinkPad device presence detection | 2  a| `0x0027`, `0x003B`
a| `136` | OEM-specific | 1  a| `0x0035`
a| `140` | Lenovo ThinkPad embedded controller program | 5  a| `0x0036`, `0x0037`, `0x0038`, `0x003C`, `0x003D`
a| `219` | Intel Management Engine interface information | 1  a| `0x003A`
a| `221` | Intel firmware version information | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
|===
== V130-15IKB 81HN (v130-15ikb-81hn.bin)

[horizontal]
File path:: `lenovo/v130-15ikb-81hn.bin`
Product name:: 81HN
Product version:: Lenovo V130-15IKB
Product family:: V130-15IKB
Firmware vendor:: LENOVO
Firmware version:: 8VCN26WW
Release date:: 2020-06-09
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000A`
a| `1` | System information | 1  a| `0x000B`
a| `2` | Baseboard or module information | 1  a| `0x000C`
a| `3` | System enclosure or chassis | 1  a| `0x000D`
a| `4` | Processor information | 1  a| `0x0009`
a| `7` | Cache information | 3  a| `0x0006`, `0x0007`, `0x0008`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 6  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `10` | Onboard devices information | 2  a| `0x0024`, `0x0025`
a| `11` | OEM strings | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `14` | Group associations | 2  a| `0x0001`, `0x0036`
a| `15` | System event log | 1  a| `0x0035`
a| `16` | Physical memory array | 1  a| `0x0002`
a| `17` | Memory device | 2  a| `0x0003`, `0x0004`
a| `19` | Memory array mapped address | 1  a| `0x0005`
a| `22` | Portable battery | 1  a| `0x0029`
a| `24` | Hardware security | 1  a| `0x002D`
a| `32` | System boot information | 1  a| `0x002A`
a| `127` | End of table | 1  a| `0xFEFF`
a| `130` | Intel Active Management Technology information | 1  a| `0x002F`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0030`
a| `133` | OEM-specific | 1  a| `0x002C`
a| `200` | Lenovo machine type model | 1  a| `0x002B`
a| `219` | Intel Management Engine interface information | 1  a| `0x0037`
a| `221` | Intel firmware version information | 4  a| `0x0031`, `0x0032`, `0x0033`, `0x0034`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
a| `248` | OEM-specific | 1  a| `0x002E`
|===
== Yoga 530-14IKB 81EK (yoga-530-14ikb-81ek.bin)

[horizontal]
File path:: `lenovo/yoga-530-14ikb-81ek.bin`
Product name:: 81EK
Product version:: Lenovo YOGA 530-14IKB
Product family:: YOGA 530-14IKB
Firmware vendor:: LENOVO
Firmware version:: 7QCN46WW
Release date:: 2020-11-26
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 17  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `9` | System slots | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `11` | OEM strings | 1  a| `0x001E`
a| `12` | System configuration options | 1  a| `0x001F`
a| `13` | Firmware language information | 1  a| `0x0020`
a| `14` | Group associations | 3  a| `0x0021`, `0x0022`, `0x0023`
a| `15` | System event log | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 1  a| `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x0029`
a| `21` | Built-in pointing device | 1  a| `0x002A`
a| `22` | Portable battery | 1  a| `0x002B`
a| `24` | Hardware security | 1  a| `0x002C`
a| `26` | Voltage probe | 1  a| `0x002D`
a| `27` | Cooling device | 1  a| `0x002E`
a| `28` | Temperature probe | 1  a| `0x002F`
a| `32` | System boot information | 1  a| `0x0030`
a| `39` | System power supply | 1  a| `0x0031`
a| `40` | Additional information | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 1  a| `0x0033`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0034`
a| `129` | OEM-specific | 1  a| `0x0035`
a| `130` | Intel Active Management Technology information | 1  a| `0x0036`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0037`
a| `133` | OEM-specific | 1  a| `0x0038`
a| `136` | OEM-specific | 1  a| `0x0039`
a| `200` | Lenovo machine type model | 1  a| `0x003A`
a| `219` | Intel Management Engine interface information | 1  a| `0x003B`
a| `221` | Intel firmware version information | 4  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0040`
a| `248` | OEM-specific | 1  a| `0x0041`
|===
== Yoga C640-13IML 81UE (yoga-c640-13iml-81ue.bin)

[horizontal]
File path:: `lenovo/yoga-c640-13iml-81ue.bin`
Product name:: 81UE
Product version:: Lenovo YOGA C640-13IML
Product family:: YOGA C640-13IML
Firmware vendor:: LENOVO
Firmware version:: CHCN25WW
Release date:: 2020-11-20
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x000F`
a| `1` | System information | 1  a| `0x0010`
a| `2` | Baseboard or module information | 1  a| `0x0011`
a| `3` | System enclosure or chassis | 1  a| `0x0012`
a| `4` | Processor information | 1  a| `0x000E`
a| `7` | Cache information | 3  a| `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 41  a| `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `9` | System slots | 7  a| `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`
a| `12` | System configuration options | 1  a| `0x0015`
a| `13` | Firmware language information | 1  a| `0x0014`
a| `14` | Group associations | 3  a| `0x0001`, `0x0054`, `0x0056`
a| `15` | System event log | 1  a| `0x0055`
a| `16` | Physical memory array | 1  a| `0x0002`
a| `17` | Memory device | 2  a| `0x0003`, `0x0004`
a| `19` | Memory array mapped address | 1  a| `0x0005`
a| `24` | Hardware security | 2  a| `0x0053`, `0x0050`
a| `27` | Cooling device | 2  a| `0x0040`, `0x0041`
a| `32` | System boot information | 1  a| `0x0013`
a| `39` | System power supply | 1  a| `0x0042`
a| `41` | Onboard devices extended information | 4  a| `0x0043`, `0x0044`, `0x0045`, `0x0046`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x0052`
a| `133` | OEM-specific | 1  a| `0x004F`
a| `136` | OEM-specific | 1  a| `0x003F`
a| `200` | Lenovo machine type model | 1  a| `0x004E`
a| `219` | Intel Management Engine interface information | 1  a| `0x0057`
a| `221` | Intel firmware version information | 5  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0000`
a| `248` | OEM-specific | 1  a| `0x0051`
|===
== Yoga Slim 7 14IIL05 82A1 (yoga-slim-7-14iil05-82a1.bin)

[horizontal]
File path:: `lenovo/yoga-slim-7-14iil05-82a1.bin`
Product name:: 82A1
Product version:: Yoga Slim 7 14IIL05
Product family:: Yoga Slim 7 14IIL05
Firmware vendor:: LENOVO
Firmware version:: DHCN34WW
Release date:: 2022-05-19
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 4  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `8` | Port connector information | 17  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `9` | System slots | 5  a| `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0021`
a| `14` | Group associations | 3  a| `0x0022`, `0x0023`, `0x0024`
a| `15` | System event log | 1  a| `0x0025`
a| `16` | Physical memory array | 1  a| `0x0026`
a| `17` | Memory device | 2  a| `0x0027`, `0x0028`
a| `19` | Memory array mapped address | 1  a| `0x0029`
a| `20` | Memory device mapped address | 2  a| `0x002A`, `0x002B`
a| `21` | Built-in pointing device | 1  a| `0x002C`
a| `22` | Portable battery | 1  a| `0x002D`
a| `24` | Hardware security | 1  a| `0x002E`
a| `26` | Voltage probe | 1  a| `0x002F`
a| `27` | Cooling device | 1  a| `0x0030`
a| `28` | Temperature probe | 1  a| `0x0031`
a| `32` | System boot information | 1  a| `0x0032`
a| `39` | System power supply | 1  a| `0x0033`
a| `40` | Additional information | 1  a| `0x0034`
a| `41` | Onboard devices extended information | 1  a| `0x0035`
a| `43` | TPM device | 1  a| `0x0036`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0037`
a| `129` | OEM-specific | 1  a| `0x0038`
a| `130` | Intel Active Management Technology information | 1  a| `0x0039`
a| `131` | Lenovo ThinkVantage Technologies enablement | 1  a| `0x003A`
a| `133` | OEM-specific | 1  a| `0x003B`
a| `136` | OEM-specific | 1  a| `0x003C`
a| `200` | Lenovo machine type model | 1  a| `0x003D`
a| `219` | Intel Management Engine interface information | 1  a| `0x003E`
a| `221` | Intel firmware version information | 5  a| `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0044`
a| `248` | OEM-specific | 1  a| `0x0045`
|===
