= SuperMicro
:toc:
:toclevels: 1

== H8QG6 (h8qg6.bin)

[horizontal]
File path:: `supermicro/h8qg6.bin`
Product name:: H8QG6
Product version:: 1234567890
Product family:: Server
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3.00
Release date:: 2012-09-04
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 4  a| `0x0004`, `0x0008`, `0x000C`, `0x0010`
a| `7` | Cache information | 12  a| `0x0005`, `0x0006`, `0x0007`, `0x0009`, `0x000A`, `0x000B`, `0x000D`, `0x000E`, `0x000F`, `0x0011`, `0x0012`, `0x0013`
a| `9` | System slots | 5  a| `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`
a| `11` | OEM strings | 1  a| `0x0019`
a| `15` | System event log | 1  a| `0x001A`
a| `16` | Physical memory array | 1  a| `0x001B`
a| `17` | Memory device | 32  a| `0x001D`, `0x001F`, `0x0021`, `0x0023`, `0x0025`, `0x0027`, `0x0029`, `0x002B`, `0x002D`, `0x002F`, `0x0031`, `0x0033`, `0x0035`, `0x0037`, `0x0039`, `0x003B`, `0x003D`, `0x003F`, `0x0041`, `0x0043`, `0x0045`, `0x0047`, `0x0049`, `0x004B`, `0x004D`, `0x004F`, `0x0051`, `0x0053`, `0x0055`, `0x0057`, `0x0059`, `0x005B`
a| `19` | Memory array mapped address | 1  a| `0x001C`
a| `20` | Memory device mapped address | 32  a| `0x001E`, `0x0020`, `0x0022`, `0x0024`, `0x0026`, `0x0028`, `0x002A`, `0x002C`, `0x002E`, `0x0030`, `0x0032`, `0x0034`, `0x0036`, `0x0038`, `0x003A`, `0x003C`, `0x003E`, `0x0040`, `0x0042`, `0x0044`, `0x0046`, `0x0048`, `0x004A`, `0x004C`, `0x004E`, `0x0050`, `0x0052`, `0x0054`, `0x0056`, `0x0058`, `0x005A`, `0x005C`
a| `32` | System boot information | 1  a| `0x005D`
a| `38` | IPMI device information | 1  a| `0x005E`
a| `127` | End of table | 1  a| `0x005F`
|===
== H8QM8 (h8qm8.bin)

[horizontal]
File path:: `supermicro/h8qm8.bin`
Product name:: H8QM8
Product version:: 1234567890
Product family:: To Be Filled By O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 080014
Release date:: 2009-05-14
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 4  a| `0x0004`, `0x0008`, `0x000C`, `0x0010`
a| `7` | Cache information | 12  a| `0x0005`, `0x0006`, `0x0007`, `0x0009`, `0x000A`, `0x000B`, `0x000D`, `0x000E`, `0x000F`, `0x0011`, `0x0012`, `0x0013`
a| `8` | Port connector information | 3  a| `0x0014`, `0x0015`, `0x0016`
a| `127` | End of table | 1  a| `0x0017`
|===
== SYS-1027R-WRF (sys-1027r-wrf.bin)

[horizontal]
File path:: `supermicro/sys-1027r-wrf.bin`
Product name:: SYS-1027R-WRF
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3.0c
Release date:: 2014-03-24
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x0004`, `0x0008`
a| `7` | Cache information | 6  a| `0x0005`, `0x0006`, `0x0007`, `0x0009`, `0x000A`, `0x000B`
a| `8` | Port connector information | 24  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 2  a| `0x0026`, `0x002A`
a| `10` | Onboard devices information | 1  a| `0x0038`
a| `11` | OEM strings | 1  a| `0x0039`
a| `12` | System configuration options | 1  a| `0x003A`
a| `13` | Firmware language information | 1  a| `0x00B9`
a| `15` | System event log | 1  a| `0x009A`
a| `16` | Physical memory array | 2  a| `0x003B`, `0x004D`
a| `17` | Memory device | 16  a| `0x003D`, `0x003F`, `0x0041`, `0x0043`, `0x0045`, `0x0047`, `0x0049`, `0x004B`, `0x004F`, `0x0051`, `0x0053`, `0x0055`, `0x0057`, `0x0059`, `0x005B`, `0x005D`
a| `19` | Memory array mapped address | 2  a| `0x003C`, `0x004E`
a| `20` | Memory device mapped address | 16  a| `0x003E`, `0x0040`, `0x0042`, `0x0044`, `0x0046`, `0x0048`, `0x004A`, `0x004C`, `0x0050`, `0x0052`, `0x0054`, `0x0056`, `0x0058`, `0x005A`, `0x005C`, `0x005E`
a| `26` | Voltage probe | 4  a| `0x0061`, `0x0071`, `0x0074`, `0x0089`
a| `27` | Cooling device | 5  a| `0x0067`, `0x006A`, `0x007A`, `0x0080`, `0x008B`
a| `28` | Temperature probe | 4  a| `0x0064`, `0x0077`, `0x007D`, `0x008A`
a| `29` | Electrical current probe | 4  a| `0x006D`, `0x0083`, `0x0086`, `0x008C`
a| `32` | System boot information | 1  a| `0x005F`
a| `34` | Management device | 2  a| `0x0060`, `0x0070`
a| `35` | Management device component | 13  a| `0x0063`, `0x0066`, `0x0069`, `0x006C`, `0x006F`, `0x0073`, `0x0076`, `0x0079`, `0x007C`, `0x007F`, `0x0082`, `0x0085`, `0x0088`
a| `36` | Management device threshold data | 13  a| `0x0062`, `0x0065`, `0x0068`, `0x006B`, `0x006E`, `0x0072`, `0x0075`, `0x0078`, `0x007B`, `0x007E`, `0x0081`, `0x0084`, `0x0087`
a| `38` | IPMI device information | 1  a| `0x0091`
a| `39` | System power supply | 1  a| `0x008D`
a| `41` | Onboard devices extended information | 3  a| `0x008E`, `0x008F`, `0x0090`
a| `126` | Inactive | 18  a| `0x0024`, `0x0025`, `0x0027`, `0x0028`, `0x0029`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`
a| `127` | End of table | 1  a| `0x00BA`
|===
== SYS-5019S-L (sys-5019s-l.bin)

[horizontal]
File path:: `supermicro/sys-5019s-l.bin`
Product name:: SYS-5019S-L
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2.7
Release date:: 2021-12-06
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002C`
a| `7` | Cache information | 4  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 3  a| `0x001D`, `0x001E`, `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `15` | System event log | 1  a| `0x0033`
a| `16` | Physical memory array | 1  a| `0x002D`
a| `17` | Memory device | 4  a| `0x002E`, `0x002F`, `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 1  a| `0x0034`
a| `32` | System boot information | 1  a| `0x0021`
a| `38` | IPMI device information | 1  a| `0x0027`
a| `39` | System power supply | 2  a| `0x0022`, `0x0023`
a| `40` | Additional information | 4  a| `0x0038`, `0x0039`, `0x003A`, `0x003B`
a| `41` | Onboard devices extended information | 3  a| `0x0024`, `0x0025`, `0x0026`
a| `127` | End of table | 1  a| `0x003D`
a| `136` | OEM-specific | 1  a| `0x003C`
a| `221` | Intel firmware version information | 3  a| `0x0035`, `0x0036`, `0x0037`
|===
== SYS-5019-M (sys-5019s-m.bin)

[horizontal]
File path:: `supermicro/sys-5019s-m.bin`
Product name:: SYS-5019S-M
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2.5
Release date:: 2020-11-26
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002D`
a| `7` | Cache information | 4  a| `0x0029`, `0x002A`, `0x002B`, `0x002C`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 3  a| `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `15` | System event log | 1  a| `0x0034`
a| `16` | Physical memory array | 1  a| `0x002E`
a| `17` | Memory device | 4  a| `0x002F`, `0x0030`, `0x0031`, `0x0032`
a| `19` | Memory array mapped address | 1  a| `0x0033`
a| `20` | Memory device mapped address | 4  a| `0x0035`, `0x0036`, `0x0037`, `0x0038`
a| `32` | System boot information | 1  a| `0x0020`
a| `38` | IPMI device information | 1  a| `0x0028`
a| `39` | System power supply | 2  a| `0x0021`, `0x0022`
a| `40` | Additional information | 8  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`
a| `41` | Onboard devices extended information | 3  a| `0x0023`, `0x0024`, `0x0025`
a| `127` | End of table | 1  a| `0x0045`
a| `136` | OEM-specific | 1  a| `0x0044`
a| `221` | Intel firmware version information | 3  a| `0x0039`, `0x003A`, `0x003B`
|===
== X10DAL-i (x10dal-i.bin)

[horizontal]
File path:: `supermicro/x10dal-i.bin`
Product name:: Super Server
Product version:: 0123456789
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2.0
Release date:: 2015-12-18
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x005F`, `0x0063`
a| `7` | Cache information | 6  a| `0x005C`, `0x005D`, `0x005E`, `0x0060`, `0x0061`, `0x0062`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0064`
a| `15` | System event log | 1  a| `0x005B`
a| `16` | Physical memory array | 2  a| `0x004F`, `0x0054`
a| `17` | Memory device | 8  a| `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0055`, `0x0056`, `0x0057`, `0x0058`
a| `19` | Memory array mapped address | 1  a| `0x0059`
a| `20` | Memory device mapped address | 1  a| `0x005A`
a| `26` | Voltage probe | 3  a| `0x0025`, `0x0035`, `0x0038`
a| `27` | Cooling device | 4  a| `0x002B`, `0x002E`, `0x003E`, `0x0044`
a| `28` | Temperature probe | 3  a| `0x0028`, `0x003B`, `0x0041`
a| `29` | Electrical current probe | 3  a| `0x0031`, `0x0047`, `0x004A`
a| `32` | System boot information | 1  a| `0x0023`
a| `34` | Management device | 2  a| `0x0024`, `0x0034`
a| `35` | Management device component | 13  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`, `0x0037`, `0x003A`, `0x003D`, `0x0040`, `0x0043`, `0x0046`, `0x0049`, `0x004C`
a| `36` | Management device threshold data | 13  a| `0x0026`, `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0036`, `0x0039`, `0x003C`, `0x003F`, `0x0042`, `0x0045`, `0x0048`, `0x004B`
a| `41` | Onboard devices extended information | 2  a| `0x004D`, `0x004E`
a| `127` | End of table | 1  a| `0x0065`
|===
== X10DDW-I (x10ddw-i.bin)

[horizontal]
File path:: `supermicro/x10ddw-i.bin`
Product name:: X10DDW-i
Product version:: 123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3.4
Release date:: 2021-10-18
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x0082`, `0x0086`
a| `7` | Cache information | 6  a| `0x007F`, `0x0080`, `0x0081`, `0x0083`, `0x0084`, `0x0085`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 6  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`
a| `10` | Onboard devices information | 1  a| `0x0022`
a| `11` | OEM strings | 1  a| `0x0023`
a| `12` | System configuration options | 1  a| `0x0024`
a| `13` | Firmware language information | 1  a| `0x0087`
a| `15` | System event log | 1  a| `0x005C`
a| `16` | Physical memory array | 4  a| `0x005D`, `0x0065`, `0x006D`, `0x0075`
a| `17` | Memory device | 16  a| `0x005F`, `0x0061`, `0x0062`, `0x0064`, `0x0067`, `0x0069`, `0x006A`, `0x006C`, `0x006F`, `0x0071`, `0x0072`, `0x0074`, `0x0077`, `0x0079`, `0x007A`, `0x007C`
a| `19` | Memory array mapped address | 4  a| `0x005E`, `0x0066`, `0x006E`, `0x0076`
a| `20` | Memory device mapped address | 8  a| `0x0060`, `0x0063`, `0x0068`, `0x006B`, `0x0070`, `0x0073`, `0x0078`, `0x007B`
a| `26` | Voltage probe | 4  a| `0x0027`, `0x0037`, `0x003A`, `0x004F`
a| `27` | Cooling device | 5  a| `0x002D`, `0x0030`, `0x0040`, `0x0046`, `0x0051`
a| `28` | Temperature probe | 4  a| `0x002A`, `0x003D`, `0x0043`, `0x0050`
a| `29` | Electrical current probe | 4  a| `0x0033`, `0x0049`, `0x004C`, `0x0052`
a| `32` | System boot information | 1  a| `0x0025`
a| `34` | Management device | 2  a| `0x0026`, `0x0036`
a| `35` | Management device component | 13  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`, `0x0039`, `0x003C`, `0x003F`, `0x0042`, `0x0045`, `0x0048`, `0x004B`, `0x004E`
a| `36` | Management device threshold data | 13  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`, `0x0038`, `0x003B`, `0x003E`, `0x0041`, `0x0044`, `0x0047`, `0x004A`, `0x004D`
a| `38` | IPMI device information | 1  a| `0x0057`
a| `39` | System power supply | 2  a| `0x007D`, `0x007E`
a| `41` | Onboard devices extended information | 3  a| `0x0054`, `0x0055`, `0x0056`
a| `127` | End of table | 1  a| `0x0088`
|===
== X10SLL-F (x10sll-f.bin)

[horizontal]
File path:: `supermicro/x10sll-f.bin`
Product name:: SYS-5018D-MF
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3.2
Release date:: 2018-05-14
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0045`
a| `7` | Cache information | 3  a| `0x0046`, `0x0047`, `0x0048`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 3  a| `0x001C`, `0x001D`, `0x001E`
a| `11` | OEM strings | 1  a| `0x001F`
a| `12` | System configuration options | 1  a| `0x0020`
a| `13` | Firmware language information | 1  a| `0x0061`
a| `15` | System event log | 1  a| `0x0054`
a| `16` | Physical memory array | 1  a| `0x004A`
a| `17` | Memory device | 4  a| `0x004B`, `0x004C`, `0x004D`, `0x004E`
a| `19` | Memory array mapped address | 1  a| `0x004F`
a| `20` | Memory device mapped address | 4  a| `0x0050`, `0x0051`, `0x0052`, `0x0053`
a| `26` | Voltage probe | 2  a| `0x002D`, `0x003C`
a| `27` | Cooling device | 3  a| `0x0033`, `0x0036`, `0x003E`
a| `28` | Temperature probe | 2  a| `0x0030`, `0x003D`
a| `29` | Electrical current probe | 2  a| `0x0039`, `0x003F`
a| `32` | System boot information | 1  a| `0x002B`
a| `34` | Management device | 1  a| `0x002C`
a| `35` | Management device component | 5  a| `0x002F`, `0x0032`, `0x0035`, `0x0038`, `0x003B`
a| `36` | Management device threshold data | 5  a| `0x002E`, `0x0031`, `0x0034`, `0x0037`, `0x003A`
a| `38` | IPMI device information | 1  a| `0x0044`
a| `39` | System power supply | 1  a| `0x0040`
a| `41` | Onboard devices extended information | 3  a| `0x0041`, `0x0042`, `0x0043`
a| `127` | End of table | 1  a| `0x0062`
a| `136` | OEM-specific | 1  a| `0x0060`
|===
== X11SSL-F (x11ssl-f.bin)

[horizontal]
File path:: `supermicro/x11ssl-f.bin`
Product name:: SYS-5019S-L
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2.2a
Release date:: 2019-05-24
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002C`
a| `7` | Cache information | 4  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 3  a| `0x001D`, `0x001E`, `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `15` | System event log | 1  a| `0x0033`
a| `16` | Physical memory array | 1  a| `0x002D`
a| `17` | Memory device | 4  a| `0x002E`, `0x002F`, `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 4  a| `0x0034`, `0x0035`, `0x0036`, `0x0037`
a| `32` | System boot information | 1  a| `0x0021`
a| `38` | IPMI device information | 1  a| `0x0027`
a| `39` | System power supply | 2  a| `0x0022`, `0x0023`
a| `40` | Additional information | 4  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `41` | Onboard devices extended information | 3  a| `0x0024`, `0x0025`, `0x0026`
a| `127` | End of table | 1  a| `0x0040`
a| `136` | OEM-specific | 1  a| `0x003F`
a| `221` | Intel firmware version information | 3  a| `0x0038`, `0x0039`, `0x003A`
|===
== X9DBL-iF (x9dbl-if.bin)

[horizontal]
File path:: `supermicro/x9dbl-if.bin`
Product name:: X9DBL-3F/X9DBL-iF
Product version:: 0123456789
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3.00
Release date:: 2013-12-06
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x0004`, `0x0008`
a| `7` | Cache information | 6  a| `0x0005`, `0x0006`, `0x0007`, `0x0009`, `0x000A`, `0x000B`
a| `8` | Port connector information | 24  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 3  a| `0x0024`, `0x0027`, `0x0029`
a| `10` | Onboard devices information | 1  a| `0x002A`
a| `11` | OEM strings | 1  a| `0x002B`
a| `12` | System configuration options | 1  a| `0x002C`
a| `13` | Firmware language information | 1  a| `0x0081`
a| `15` | System event log | 1  a| `0x0078`
a| `16` | Physical memory array | 2  a| `0x002D`, `0x0035`
a| `17` | Memory device | 6  a| `0x002F`, `0x0031`, `0x0033`, `0x0037`, `0x0039`, `0x003B`
a| `19` | Memory array mapped address | 2  a| `0x002E`, `0x0036`
a| `20` | Memory device mapped address | 6  a| `0x0030`, `0x0032`, `0x0034`, `0x0038`, `0x003A`, `0x003C`
a| `26` | Voltage probe | 4  a| `0x003F`, `0x004F`, `0x0052`, `0x0067`
a| `27` | Cooling device | 5  a| `0x0045`, `0x0048`, `0x0058`, `0x005E`, `0x0069`
a| `28` | Temperature probe | 4  a| `0x0042`, `0x0055`, `0x005B`, `0x0068`
a| `29` | Electrical current probe | 4  a| `0x004B`, `0x0061`, `0x0064`, `0x006A`
a| `32` | System boot information | 1  a| `0x003D`
a| `34` | Management device | 2  a| `0x003E`, `0x004E`
a| `35` | Management device component | 13  a| `0x0041`, `0x0044`, `0x0047`, `0x004A`, `0x004D`, `0x0051`, `0x0054`, `0x0057`, `0x005A`, `0x005D`, `0x0060`, `0x0063`, `0x0066`
a| `36` | Management device threshold data | 13  a| `0x0040`, `0x0043`, `0x0046`, `0x0049`, `0x004C`, `0x0050`, `0x0053`, `0x0056`, `0x0059`, `0x005C`, `0x005F`, `0x0062`, `0x0065`
a| `38` | IPMI device information | 1  a| `0x006F`
a| `39` | System power supply | 1  a| `0x006B`
a| `41` | Onboard devices extended information | 3  a| `0x006C`, `0x006D`, `0x006E`
a| `126` | Inactive | 3  a| `0x0025`, `0x0026`, `0x0028`
a| `127` | End of table | 1  a| `0x0082`
|===
