= Acer
:toc:
:toclevels: 1

== Aspire 3680 (aspire-3680.bin)

[horizontal]
File path:: `acer/aspire-3680.bin`
Product name:: Aspire 3680
Product version:: Not Applicable
Product family:: None
Firmware vendor:: Acer
Firmware version:: v1.3216
Release date:: 1906-10-27
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 2  a| `0x0005`, `0x0006`
a| `8` | Port connector information | 4  a| `0x0007`, `0x0008`, `0x0009`, `0x000A`
a| `9` | System slots | 1  a| `0x000B`
a| `10` | Onboard devices information | 1  a| `0x000C`
a| `11` | OEM strings | 1  a| `0x000D`
a| `12` | System configuration options | 1  a| `0x000E`
a| `15` | System event log | 1  a| `0x000F`
a| `16` | Physical memory array | 1  a| `0x0010`
a| `17` | Memory device | 2  a| `0x0011`, `0x0012`
a| `19` | Memory array mapped address | 1  a| `0x0013`
a| `20` | Memory device mapped address | 2  a| `0x0014`, `0x0015`
a| `23` | System reset | 1  a| `0x0016`
a| `24` | Hardware security | 1  a| `0x0017`
a| `25` | System power controls | 1  a| `0x0018`
a| `26` | Voltage probe | 1  a| `0x0019`
a| `27` | Cooling device | 1  a| `0x001A`
a| `28` | Temperature probe | 1  a| `0x001B`
a| `29` | Electrical current probe | 1  a| `0x001C`
a| `30` | Out-of-band remote access | 1  a| `0x001D`
a| `32` | System boot information | 1  a| `0x001E`
a| `127` | End of table | 1  a| `0x0021`
a| `129` | Intel ASF information | 1  a| `0x001F`
a| `136` | OEM-specific | 1  a| `0x0020`
|===
== Aspire 5720 (aspire-5720.bin)

[horizontal]
File path:: `acer/aspire-5720.bin`
Product name:: Aspire 5720
Product version:: V1.17
Product family:: None
Firmware vendor:: Acer
Firmware version:: V1.17
Release date:: 2007-09-14
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0020`
a| `6` | Memory module information | 2  a| `0x001A`, `0x001D`
a| `7` | Cache information | 3  a| `0x0021`, `0x0022`, `0x0023`
a| `8` | Port connector information | 8  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`
a| `9` | System slots | 6  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `10` | Onboard devices information | 2  a| `0x0012`, `0x0013`
a| `11` | OEM strings | 1  a| `0x0014`
a| `12` | System configuration options | 1  a| `0x0015`
a| `16` | Physical memory array | 1  a| `0x0018`
a| `17` | Memory device | 2  a| `0x0019`, `0x001C`
a| `19` | Memory array mapped address | 1  a| `0x001F`
a| `20` | Memory device mapped address | 2  a| `0x001B`, `0x001E`
a| `21` | Built-in pointing device | 1  a| `0x0016`
a| `22` | Portable battery | 1  a| `0x0017`
a| `127` | End of table | 1  a| `0x0024`
|===
== Aspire A515-51G (aspire-a515-51g.bin)

[horizontal]
File path:: `acer/aspire-a515-51g.bin`
Product name:: Aspire A515-51G
Product version:: V2.02
Product family:: Aspire 5
Firmware vendor:: Insyde Corp.
Firmware version:: V2.02
Release date:: 2019-01-03
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `10` | Onboard devices information | 1  a| `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `14` | Group associations | 2  a| `0x000B`, `0x000C`
a| `16` | Physical memory array | 1  a| `0x000D`
a| `17` | Memory device | 2  a| `0x000E`, `0x000F`
a| `19` | Memory array mapped address | 1  a| `0x0010`
a| `20` | Memory device mapped address | 2  a| `0x0011`, `0x0012`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0013`
a| `170` | Acer hotkey functions | 1  a| `0x0014`
a| `171` | Acer device list | 1  a| `0x0015`
a| `172` | OEM-specific | 1  a| `0x0016`
a| `219` | Intel Management Engine interface information | 1  a| `0x0017`
a| `221` | Intel firmware version information | 4  a| `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001C`
a| `248` | OEM-specific | 1  a| `0x001D`
|===
== Aspire A515-52 (aspire-a515-52.bin)

[horizontal]
File path:: `acer/aspire-a515-52.bin`
Product name:: Aspire A515-52
Product version:: V1.14
Product family:: Aspire 5
Firmware vendor:: Insyde Corp.
Firmware version:: V1.14
Release date:: 2019-05-24
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `10` | Onboard devices information | 1  a| `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `14` | Group associations | 3  a| `0x000B`, `0x000C`, `0x000D`
a| `16` | Physical memory array | 1  a| `0x000E`
a| `17` | Memory device | 2  a| `0x000F`, `0x0010`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 1  a| `0x0012`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0013`
a| `170` | Acer hotkey functions | 1  a| `0x0014`
a| `171` | Acer device list | 1  a| `0x0015`
a| `172` | OEM-specific | 1  a| `0x0016`
a| `219` | Intel Management Engine interface information | 1  a| `0x0017`
a| `221` | Intel firmware version information | 5  a| `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001D`
a| `248` | OEM-specific | 1  a| `0x001E`
|===
== Aspire A515-52G (aspire-a515-52g.bin)

[horizontal]
File path:: `acer/aspire-a515-52g.bin`
Product name:: Aspire A515-52G
Product version:: V1.16
Product family:: Aspire 5
Firmware vendor:: Insyde Corp.
Firmware version:: V1.16
Release date:: 2019-08-23
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `10` | Onboard devices information | 1  a| `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `14` | Group associations | 3  a| `0x000B`, `0x000C`, `0x000D`
a| `16` | Physical memory array | 1  a| `0x000E`
a| `17` | Memory device | 2  a| `0x000F`, `0x0010`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 2  a| `0x0012`, `0x0013`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0014`
a| `170` | Acer hotkey functions | 1  a| `0x0015`
a| `171` | Acer device list | 1  a| `0x0016`
a| `172` | OEM-specific | 1  a| `0x0017`
a| `219` | Intel Management Engine interface information | 1  a| `0x0018`
a| `221` | Intel firmware version information | 5  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001E`
a| `248` | OEM-specific | 1  a| `0x001F`
|===
== Nitro 5 AN515-31 (nitro-an515-31.bin)

[horizontal]
File path:: `acer/nitro-an515-31.bin`
Product name:: Nitro AN515-31
Product version:: V1.21
Product family:: Acer Nitro 5
Firmware vendor:: Insyde Corp.
Firmware version:: V1.21
Release date:: 2018-08-08
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `10` | Onboard devices information | 1  a| `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `14` | Group associations | 2  a| `0x000B`, `0x000C`
a| `16` | Physical memory array | 1  a| `0x000D`
a| `17` | Memory device | 2  a| `0x000E`, `0x000F`
a| `19` | Memory array mapped address | 1  a| `0x0010`
a| `20` | Memory device mapped address | 2  a| `0x0011`, `0x0012`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0013`
a| `170` | Acer hotkey functions | 1  a| `0x0014`
a| `171` | Acer device list | 1  a| `0x0015`
a| `172` | OEM-specific | 1  a| `0x0016`
a| `219` | Intel Management Engine interface information | 1  a| `0x0017`
a| `221` | Intel firmware version information | 4  a| `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001C`
a| `248` | OEM-specific | 1  a| `0x001D`
|===
== Nitro AN515-52 (nitro-an515-52.bin)

[horizontal]
File path:: `acer/nitro-an515-52.bin`
Product name:: Nitro AN515-52
Product version:: V1.26
Product family:: Nitro 5
Firmware vendor:: Insyde Corp.
Firmware version:: V1.26
Release date:: 2019-03-27
SMBIOS version:: 3.0.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `10` | Onboard devices information | 1  a| `0x0008`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `14` | Group associations | 3  a| `0x000B`, `0x000C`, `0x000D`
a| `16` | Physical memory array | 1  a| `0x000E`
a| `17` | Memory device | 2  a| `0x000F`, `0x0010`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 1  a| `0x0012`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0013`
a| `170` | Acer hotkey functions | 1  a| `0x0014`
a| `171` | Acer device list | 1  a| `0x0015`
a| `172` | OEM-specific | 1  a| `0x0016`
a| `219` | Intel Management Engine interface information | 1  a| `0x0017`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x0018`
a| `248` | OEM-specific | 1  a| `0x0019`
|===
== Predator G9-592 (predator-g9-592.bin)

[horizontal]
File path:: `acer/predator-g9-592.bin`
Product name:: Predator G9-592
Product version:: V1.08
Product family:: SKL
Firmware vendor:: Acer
Firmware version:: V1.08
Release date:: 2018-10-02
SMBIOS version:: 2.8

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 4  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`
a| `10` | Onboard devices information | 1  a| `0x0009`
a| `11` | OEM strings | 1  a| `0x000A`
a| `12` | System configuration options | 1  a| `0x000B`
a| `14` | Group associations | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `16` | Physical memory array | 1  a| `0x000F`
a| `17` | Memory device | 4  a| `0x0010`, `0x0011`, `0x0012`, `0x0013`
a| `19` | Memory array mapped address | 1  a| `0x0014`
a| `20` | Memory device mapped address | 2  a| `0x0015`, `0x0016`
a| `127` | End of table | 1  a| `0xFEFF`
a| `170` | Acer hotkey functions | 1  a| `0x0017`
a| `171` | Acer device list | 1  a| `0x0018`
a| `172` | OEM-specific | 1  a| `0x0019`
a| `219` | Intel Management Engine interface information | 1  a| `0x001A`
a| `221` | Intel firmware version information | 4  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001F`
a| `248` | OEM-specific | 1  a| `0x0020`
|===
