= ASUS
:toc:
:toclevels: 1

== C60M1-I (c60m1-i.bin)

[horizontal]
File path:: `asus/c60m1-i.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 0305
Release date:: 2012-08-07
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002E`
a| `7` | Cache information | 2  a| `0x002D`, `0x002C`
a| `8` | Port connector information | 23  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`
a| `9` | System slots | 1  a| `0x001B`
a| `10` | Onboard devices information | 4  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `12` | System configuration options | 1  a| `0x0021`
a| `13` | Firmware language information | 1  a| `0x002F`
a| `16` | Physical memory array | 1  a| `0x0022`
a| `17` | Memory device | 2  a| `0x0024`, `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0023`
a| `20` | Memory device mapped address | 1  a| `0x0027`
a| `32` | System boot information | 1  a| `0x0028`
a| `41` | Onboard devices extended information | 3  a| `0x0029`, `0x002A`, `0x002B`
a| `126` | Inactive | 1  a| `0x0025`
a| `127` | End of table | 1  a| `0x0030`
|===
== GL753VD (gl753vd.bin)

[horizontal]
File path:: `asus/gl753vd.bin`
Product name:: GL753VD
Product version:: 1.0
Product family:: ROG
Firmware vendor:: American Megatrends Inc.
Firmware version:: GL753VD.308
Release date:: 2019-04-29
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0046`
a| `7` | Cache information | 3  a| `0x0043`, `0x0044`, `0x0045`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0055`
a| `14` | Group associations | 2  a| `0x0054`, `0x0056`
a| `16` | Physical memory array | 1  a| `0x003D`
a| `17` | Memory device | 4  a| `0x003E`, `0x003F`, `0x0040`, `0x0041`
a| `19` | Memory array mapped address | 1  a| `0x0042`
a| `20` | Memory device mapped address | 1  a| `0x004B`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 3  a| `0x003A`, `0x003B`, `0x003C`
a| `127` | End of table | 1  a| `0x0058`
a| `130` | Intel Active Management Technology information | 1  a| `0x004C`
a| `131` | Intel vPro information | 1  a| `0x004D`
a| `136` | OEM-specific | 1  a| `0x0053`
a| `219` | Intel Management Engine interface information | 1  a| `0x0057`
a| `221` | Intel firmware version information | 5  a| `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`
|===
== K53U (k53u.bin)

[horizontal]
File path:: `asus/k53u.bin`
Product name:: K53U
Product version:: 1.0
Product family:: 
Firmware vendor:: American Megatrends Inc.
Firmware version:: 223
Release date:: 2012-04-10
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0036`
a| `7` | Cache information | 2  a| `0x002C`, `0x002D`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 3  a| `0x001C`, `0x001D`, `0x001E`
a| `10` | Onboard devices information | 1  a| `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `12` | System configuration options | 1  a| `0x0021`
a| `13` | Firmware language information | 1  a| `0x0037`
a| `16` | Physical memory array | 1  a| `0x0022`
a| `17` | Memory device | 2  a| `0x0024`, `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0023`
a| `20` | Memory device mapped address | 2  a| `0x0025`, `0x0027`
a| `32` | System boot information | 1  a| `0x0028`
a| `41` | Onboard devices extended information | 3  a| `0x0029`, `0x002A`, `0x002B`
a| `127` | End of table | 1  a| `0x0038`
|===
== M4A88TD-M/USB3 (m4a88td-m-usb3.bin)

[horizontal]
File path:: `asus/m4a88td-m-usb3.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To Be Filled By O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 1401
Release date:: 2012-01-06
SMBIOS version:: 2.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 33  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`
a| `9` | System slots | 4  a| `0x0029`, `0x002A`, `0x002B`, `0x002C`
a| `10` | Onboard devices information | 4  a| `0x002D`, `0x002E`, `0x002F`, `0x0030`
a| `11` | OEM strings | 1  a| `0x0031`
a| `13` | Firmware language information | 1  a| `0x0032`
a| `15` | System event log | 1  a| `0x0033`
a| `16` | Physical memory array | 1  a| `0x0034`
a| `17` | Memory device | 4  a| `0x0036`, `0x0038`, `0x003A`, `0x003C`
a| `19` | Memory array mapped address | 1  a| `0x0035`
a| `20` | Memory device mapped address | 4  a| `0x0037`, `0x0039`, `0x003B`, `0x003D`
a| `32` | System boot information | 1  a| `0x003E`
a| `127` | End of table | 1  a| `0x003F`
|===
== N551JX (n551jx.bin)

[horizontal]
File path:: `asus/n551jx.bin`
Product name:: N551JX
Product version:: 1.0
Product family:: N
Firmware vendor:: American Megatrends Inc.
Firmware version:: N551JX.209
Release date:: 2019-04-18
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0008`
a| `7` | Cache information | 3  a| `0x0009`, `0x000A`, `0x000B`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x0020`
a| `14` | Group associations | 1  a| `0x001F`
a| `16` | Physical memory array | 1  a| `0x000C`
a| `17` | Memory device | 4  a| `0x000D`, `0x000F`, `0x0010`, `0x0012`
a| `19` | Memory array mapped address | 1  a| `0x0013`
a| `20` | Memory device mapped address | 2  a| `0x000E`, `0x0011`
a| `32` | System boot information | 1  a| `0x0007`
a| `127` | End of table | 1  a| `0x0021`
a| `131` | Intel vPro information | 1  a| `0x001A`
a| `136` | OEM-specific | 1  a| `0x0019`
a| `221` | Intel firmware version information | 4  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`
|===
== PRIME B350-Plus (prime-b350-plus.bin)

[horizontal]
File path:: `asus/prime-b350-plus.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 5407
Release date:: 2019-12-31
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002B`
a| `7` | Cache information | 3  a| `0x0028`, `0x0029`, `0x002A`
a| `8` | Port connector information | 27  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `9` | System slots | 6  a| `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`
a| `10` | Onboard devices information | 1  a| `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `12` | System configuration options | 1  a| `0x0021`
a| `13` | Firmware language information | 1  a| `0x0036`
a| `16` | Physical memory array | 1  a| `0x0026`
a| `17` | Memory device | 4  a| `0x002D`, `0x002F`, `0x0032`, `0x0034`
a| `18` | 32-bit memory error information | 5  a| `0x0025`, `0x002C`, `0x002E`, `0x0031`, `0x0033`
a| `19` | Memory array mapped address | 1  a| `0x0027`
a| `20` | Memory device mapped address | 2  a| `0x0030`, `0x0035`
a| `32` | System boot information | 1  a| `0x0022`
a| `34` | Management device | 1  a| `0x0023`
a| `41` | Onboard devices extended information | 1  a| `0x0024`
a| `127` | End of table | 1  a| `0x003D`
|===
== PRIME H610M-R (prime-h610m-r.bin)

[horizontal]
File path:: `asus/prime-h610m-r.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 3601
Release date:: 2024-10-12
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0049`
a| `7` | Cache information | 4  a| `0x0045`, `0x0046`, `0x0047`, `0x0048`
a| `8` | Port connector information | 25  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `9` | System slots | 2  a| `0x001D`, `0x001E`
a| `10` | Onboard devices information | 1  a| `0x001F`
a| `11` | OEM strings | 1  a| `0x0020`
a| `12` | System configuration options | 1  a| `0x0021`
a| `13` | Firmware language information | 1  a| `0x005F`
a| `14` | Group associations | 2  a| `0x005B`, `0x005E`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 2  a| `0x003B`, `0x003C`
a| `19` | Memory array mapped address | 1  a| `0x003D`
a| `20` | Memory device mapped address | 2  a| `0x003E`, `0x003F`
a| `26` | Voltage probe | 2  a| `0x0024`, `0x0033`
a| `27` | Cooling device | 3  a| `0x002A`, `0x002D`, `0x0035`
a| `28` | Temperature probe | 2  a| `0x0027`, `0x0034`
a| `29` | Electrical current probe | 2  a| `0x0030`, `0x0036`
a| `32` | System boot information | 1  a| `0x0022`
a| `34` | Management device | 1  a| `0x0023`
a| `35` | Management device component | 5  a| `0x0026`, `0x0029`, `0x002C`, `0x002F`, `0x0032`
a| `36` | Management device threshold data | 5  a| `0x0025`, `0x0028`, `0x002B`, `0x002E`, `0x0031`
a| `39` | System power supply | 1  a| `0x0037`
a| `40` | Additional information | 1  a| `0x0038`
a| `41` | Onboard devices extended information | 12  a| `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`
a| `44` | Processor additional information | 1  a| `0x0039`
a| `60` | Unknown | 1  a| `0x004A`
a| `127` | End of table | 1  a| `0x0060`
a| `131` | Intel vPro information | 1  a| `0x004B`
a| `133` | OEM-specific | 1  a| `0x0059`
a| `136` | OEM-specific | 2  a| `0x005A`, `0x005D`
a| `219` | Intel Management Engine interface information | 1  a| `0x005C`
a| `221` | Intel firmware version information | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0058`
|===
== ROG STRIX Z690-A GAMING WIFI D4 (rog-strix-z690-a-gaming-wifi-d4.bin)

[horizontal]
File path:: `asus/rog-strix-z690-a-gaming-wifi-d4.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 1404
Release date:: 2022-04-01
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0061`
a| `7` | Cache information | 8  a| `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`
a| `8` | Port connector information | 41  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`
a| `9` | System slots | 3  a| `0x002D`, `0x002E`, `0x002F`
a| `10` | Onboard devices information | 1  a| `0x0030`
a| `11` | OEM strings | 1  a| `0x0031`
a| `12` | System configuration options | 1  a| `0x0032`
a| `13` | Firmware language information | 1  a| `0x0074`
a| `14` | Group associations | 2  a| `0x0077`, `0x007A`
a| `16` | Physical memory array | 1  a| `0x004B`
a| `17` | Memory device | 4  a| `0x004C`, `0x004D`, `0x004E`, `0x004F`
a| `19` | Memory array mapped address | 1  a| `0x0050`
a| `20` | Memory device mapped address | 2  a| `0x0052`, `0x0053`
a| `26` | Voltage probe | 2  a| `0x0035`, `0x0044`
a| `27` | Cooling device | 3  a| `0x003B`, `0x003E`, `0x0046`
a| `28` | Temperature probe | 2  a| `0x0038`, `0x0045`
a| `29` | Electrical current probe | 2  a| `0x0041`, `0x0047`
a| `32` | System boot information | 2  a| `0x0033`, `0x0073`
a| `34` | Management device | 1  a| `0x0034`
a| `35` | Management device component | 5  a| `0x0037`, `0x003A`, `0x003D`, `0x0040`, `0x0043`
a| `36` | Management device threshold data | 5  a| `0x0036`, `0x0039`, `0x003C`, `0x003F`, `0x0042`
a| `39` | System power supply | 1  a| `0x0048`
a| `40` | Additional information | 1  a| `0x0049`
a| `41` | Onboard devices extended information | 15  a| `0x0063`, `0x0064`, `0x0065`, `0x0066`, `0x0067`, `0x0068`, `0x0069`, `0x006A`, `0x006B`, `0x006C`, `0x006D`, `0x006E`, `0x006F`, `0x0070`, `0x0071`
a| `43` | TPM device | 1  a| `0x0051`
a| `44` | Processor additional information | 1  a| `0x004A`
a| `127` | End of table | 1  a| `0x007B`
a| `131` | Intel vPro information | 1  a| `0x0062`
a| `133` | OEM-specific | 1  a| `0x0075`
a| `136` | OEM-specific | 2  a| `0x0076`, `0x0079`
a| `219` | Intel Management Engine interface information | 1  a| `0x0078`
a| `221` | Intel firmware version information | 6  a| `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0072`
|===
== RS100-X7 (rs100-x7.bin)

[horizontal]
File path:: `asus/rs100-x7.bin`
Product name:: RS100-X7
Product version:: 
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 6702
Release date:: 2013-07-23
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0032`
a| `7` | Cache information | 3  a| `0x002E`, `0x002F`, `0x0030`
a| `8` | Port connector information | 29  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `9` | System slots | 6  a| `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`
a| `10` | Onboard devices information | 1  a| `0x0027`
a| `11` | OEM strings | 1  a| `0x0028`
a| `12` | System configuration options | 1  a| `0x0029`
a| `13` | Firmware language information | 1  a| `0x003C`
a| `15` | System event log | 1  a| `0x0033`
a| `16` | Physical memory array | 1  a| `0x0031`
a| `17` | Memory device | 4  a| `0x0034`, `0x0035`, `0x0037`, `0x0038`
a| `19` | Memory array mapped address | 1  a| `0x003A`
a| `20` | Memory device mapped address | 2  a| `0x0036`, `0x0039`
a| `32` | System boot information | 1  a| `0x002A`
a| `38` | IPMI device information | 1  a| `0x002D`
a| `41` | Onboard devices extended information | 2  a| `0x002B`, `0x002C`
a| `127` | End of table | 1  a| `0x003D`
|===
== RS300-E11-RS4 (rs300-e11-rs4.bin)

[horizontal]
File path:: `asus/rs300-e11-rs4.bin`
Product name:: RS300-E11-RS4
Product version:: Rev 1.xx
Product family:: Server
Firmware vendor:: American Megatrends Inc.
Firmware version:: 1301
Release date:: 2023-08-21
SMBIOS version:: 3.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004D`
a| `7` | Cache information | 4  a| `0x0049`, `0x004A`, `0x004B`, `0x004C`
a| `8` | Port connector information | 8  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `9` | System slots | 4  a| `0x0050`, `0x0051`, `0x0052`, `0x0053`
a| `10` | Onboard devices information | 1  a| `0x000C`
a| `11` | OEM strings | 1  a| `0x000D`
a| `12` | System configuration options | 1  a| `0x000E`
a| `13` | Firmware language information | 1  a| `0x0056`
a| `14` | Group associations | 1  a| `0x0059`
a| `15` | System event log | 1  a| `0x003E`
a| `16` | Physical memory array | 1  a| `0x0038`
a| `17` | Memory device | 4  a| `0x003F`, `0x0040`, `0x0041`, `0x0042`
a| `19` | Memory array mapped address | 1  a| `0x003D`
a| `20` | Memory device mapped address | 2  a| `0x0043`, `0x0044`
a| `26` | Voltage probe | 2  a| `0x0011`, `0x0020`
a| `27` | Cooling device | 3  a| `0x0017`, `0x001A`, `0x0022`
a| `28` | Temperature probe | 2  a| `0x0014`, `0x0021`
a| `29` | Electrical current probe | 2  a| `0x001D`, `0x0023`
a| `32` | System boot information | 2  a| `0x000F`, `0x0055`
a| `34` | Management device | 1  a| `0x0010`
a| `35` | Management device component | 5  a| `0x0013`, `0x0016`, `0x0019`, `0x001C`, `0x001F`
a| `36` | Management device threshold data | 5  a| `0x0012`, `0x0015`, `0x0018`, `0x001B`, `0x001E`
a| `38` | IPMI device information | 1  a| `0x0054`
a| `39` | System power supply | 1  a| `0x0024`
a| `40` | Additional information | 1  a| `0x002B`
a| `41` | Onboard devices extended information | 3  a| `0x0025`, `0x0026`, `0x0027`
a| `42` | Management controller host interface | 1  a| `0x002A`
a| `44` | Processor additional information | 1  a| `0x0028`
a| `127` | End of table | 1  a| `0x005A`
a| `136` | OEM-specific | 2  a| `0x0057`, `0x0058`
a| `221` | Intel firmware version information | 5  a| `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x004F`
|===
== RS300-E8-RS4 (rs300-e8-rs4.bin)

[horizontal]
File path:: `asus/rs300-e8-rs4.bin`
Product name:: RS300-E8-RS4
Product version:: Rev 1.xx
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2101
Release date:: 2018-04-20
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 34  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`
a| `9` | System slots | 7  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`
a| `10` | Onboard devices information | 1  a| `0x0031`
a| `11` | OEM strings | 1  a| `0x0032`
a| `12` | System configuration options | 1  a| `0x0033`
a| `13` | Firmware language information | 1  a| `0x005B`
a| `15` | System event log | 1  a| `0x0059`
a| `16` | Physical memory array | 1  a| `0x004F`
a| `17` | Memory device | 4  a| `0x004E`, `0x0051`, `0x0053`, `0x0055`
a| `19` | Memory array mapped address | 1  a| `0x0057`
a| `20` | Memory device mapped address | 4  a| `0x0050`, `0x0052`, `0x0054`, `0x0056`
a| `26` | Voltage probe | 2  a| `0x0036`, `0x0045`
a| `27` | Cooling device | 3  a| `0x003C`, `0x003F`, `0x0047`
a| `28` | Temperature probe | 2  a| `0x0039`, `0x0046`
a| `29` | Electrical current probe | 2  a| `0x0042`, `0x0048`
a| `32` | System boot information | 1  a| `0x0034`
a| `34` | Management device | 1  a| `0x0035`
a| `35` | Management device component | 5  a| `0x0038`, `0x003B`, `0x003E`, `0x0041`, `0x0044`
a| `36` | Management device threshold data | 5  a| `0x0037`, `0x003A`, `0x003D`, `0x0040`, `0x0043`
a| `38` | IPMI device information | 1  a| `0x004D`
a| `39` | System power supply | 1  a| `0x0049`
a| `41` | Onboard devices extended information | 3  a| `0x004A`, `0x004B`, `0x004C`
a| `127` | End of table | 1  a| `0x005D`
a| `136` | OEM-specific | 1  a| `0x005A`
|===
== RS520-E9-RS8 (rs520-e9-rs8.bin)

[horizontal]
File path:: `asus/rs520-e9-rs8.bin`
Product name:: RS520-E9-RS8
Product version:: Rev 1.xx
Product family:: Server
Firmware vendor:: American Megatrends Inc.
Firmware version:: 6401
Release date:: 2020-07-22
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x0042`, `0x0046`
a| `7` | Cache information | 6  a| `0x003F`, `0x0040`, `0x0041`, `0x0043`, `0x0044`, `0x0045`
a| `8` | Port connector information | 17  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`
a| `9` | System slots | 9  a| `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x004B`, `0x004C`, `0x004D`, `0x004E`
a| `10` | Onboard devices information | 1  a| `0x001A`
a| `11` | OEM strings | 1  a| `0x001B`
a| `12` | System configuration options | 1  a| `0x001C`
a| `13` | Firmware language information | 1  a| `0x004F`
a| `15` | System event log | 1  a| `0x0029`
a| `16` | Physical memory array | 1  a| `0x002A`
a| `17` | Memory device | 16  a| `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `19` | Memory array mapped address | 3  a| `0x003B`, `0x003C`, `0x003D`
a| `26` | Voltage probe | 1  a| `0x001E`
a| `27` | Cooling device | 1  a| `0x0020`
a| `28` | Temperature probe | 1  a| `0x001F`
a| `29` | Electrical current probe | 1  a| `0x0021`
a| `32` | System boot information | 1  a| `0x001D`
a| `38` | IPMI device information | 1  a| `0x0027`
a| `39` | System power supply | 1  a| `0x0022`
a| `40` | Additional information | 1  a| `0x0023`
a| `41` | Onboard devices extended information | 3  a| `0x0024`, `0x0025`, `0x0026`
a| `42` | Management controller host interface | 1  a| `0x0028`
a| `127` | End of table | 1  a| `0x0050`
a| `133` | OEM-specific | 1  a| `0x003E`
|===
== SABERTOOTH 990FX R2.0 (sabertooth-990fx-r2.0.bin)

[horizontal]
File path:: `asus/sabertooth-990fx-r2.0.bin`
Product name:: To be filled by O.E.M.
Product version:: To be filled by O.E.M.
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2501
Release date:: 2014-04-08
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 28  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 6  a| `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`
a| `10` | Onboard devices information | 1  a| `0x002A`
a| `11` | OEM strings | 1  a| `0x002B`
a| `12` | System configuration options | 1  a| `0x002C`
a| `13` | Firmware language information | 1  a| `0x003B`
a| `16` | Physical memory array | 1  a| `0x002D`
a| `17` | Memory device | 4  a| `0x002F`, `0x0031`, `0x0033`, `0x0035`
a| `19` | Memory array mapped address | 1  a| `0x002E`
a| `20` | Memory device mapped address | 4  a| `0x0030`, `0x0032`, `0x0034`, `0x0036`
a| `32` | System boot information | 1  a| `0x0037`
a| `41` | Onboard devices extended information | 3  a| `0x0038`, `0x0039`, `0x003A`
a| `127` | End of table | 1  a| `0x003D`
|===
== Strix 17 GL703GE (strix-17-gl703ge.bin)

[horizontal]
File path:: `asus/strix-17-gl703ge.bin`
Product name:: Strix 17 GL703GE
Product version:: 1.0
Product family:: Strix
Firmware vendor:: American Megatrends Inc.
Firmware version:: GL703GE.321
Release date:: 2021-01-15
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0048`
a| `7` | Cache information | 3  a| `0x0045`, `0x0046`, `0x0047`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0055`
a| `14` | Group associations | 2  a| `0x0067`, `0x0068`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 4  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x003F`
a| `20` | Memory device mapped address | 2  a| `0x0052`, `0x0053`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 15  a| `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`, `0x0062`, `0x0063`, `0x0064`
a| `127` | End of table | 1  a| `0x006A`
a| `131` | Intel vPro information | 1  a| `0x0054`
a| `136` | OEM-specific | 1  a| `0x0066`
a| `219` | Intel Management Engine interface information | 1  a| `0x0069`
a| `221` | Intel firmware version information | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0065`
|===
== TUF GAMING A620M-Plus WiFi (tuf-gaming-a620m-plus-wifi.bin)

[horizontal]
File path:: `asus/tuf-gaming-a620m-plus-wifi.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 1811
Release date:: 2023-10-07
SMBIOS version:: 3.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 27  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `9` | System slots | 5  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x0041`
a| `16` | Physical memory array | 1  a| `0x0012`
a| `17` | Memory device | 4  a| `0x0015`, `0x0017`, `0x001A`, `0x001C`
a| `18` | 32-bit memory error information | 5  a| `0x0011`, `0x0014`, `0x0016`, `0x0019`, `0x001B`
a| `19` | Memory array mapped address | 1  a| `0x0013`
a| `20` | Memory device mapped address | 2  a| `0x0018`, `0x001D`
a| `32` | System boot information | 1  a| `0x0007`
a| `34` | Management device | 1  a| `0x0008`
a| `40` | Additional information | 2  a| `0x0009`, `0x001E`
a| `41` | Onboard devices extended information | 1  a| `0x0040`
a| `43` | TPM device | 1  a| `0x000B`
a| `44` | Processor additional information | 2  a| `0x000A`, `0x0010`
a| `60` | Unknown | 1  a| `0x001F`
a| `127` | End of table | 1  a| `0x0042`
|===
== TUF GAMING B450-Pro (tuf-gaming-b450-pro.bin)

[horizontal]
File path:: `asus/tuf-gaming-b450-pro.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 4622
Release date:: 2024-09-29
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002F`
a| `7` | Cache information | 3  a| `0x002C`, `0x002D`, `0x002E`
a| `8` | Port connector information | 29  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `9` | System slots | 5  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x003A`
a| `16` | Physical memory array | 1  a| `0x002A`
a| `17` | Memory device | 4  a| `0x0031`, `0x0033`, `0x0036`, `0x0038`
a| `18` | 32-bit memory error information | 5  a| `0x0029`, `0x0030`, `0x0032`, `0x0035`, `0x0037`
a| `19` | Memory array mapped address | 1  a| `0x002B`
a| `20` | Memory device mapped address | 2  a| `0x0034`, `0x0039`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `41` | Onboard devices extended information | 1  a| `0x0026`
a| `43` | TPM device | 1  a| `0x0028`
a| `44` | Processor additional information | 1  a| `0x0027`
a| `127` | End of table | 1  a| `0x0040`
|===
== TUF GAMING B650-Plus (tuf-gaming-b650-plus.bin)

[horizontal]
File path:: `asus/tuf-gaming-b650-plus.bin`
Product name:: System Product Name
Product version:: System Version
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 2412
Release date:: 2024-01-26
SMBIOS version:: 3.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 33  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `9` | System slots | 7  a| `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x004A`
a| `16` | Physical memory array | 1  a| `0x0012`
a| `17` | Memory device | 4  a| `0x0015`, `0x0017`, `0x001A`, `0x001C`
a| `18` | 32-bit memory error information | 5  a| `0x0011`, `0x0014`, `0x0016`, `0x0019`, `0x001B`
a| `19` | Memory array mapped address | 1  a| `0x0013`
a| `20` | Memory device mapped address | 2  a| `0x0018`, `0x001D`
a| `32` | System boot information | 1  a| `0x0007`
a| `34` | Management device | 1  a| `0x0008`
a| `40` | Additional information | 2  a| `0x0009`, `0x001E`
a| `41` | Onboard devices extended information | 2  a| `0x0048`, `0x0049`
a| `43` | TPM device | 1  a| `0x000B`
a| `44` | Processor additional information | 2  a| `0x000A`, `0x0010`
a| `60` | Unknown | 1  a| `0x001F`
a| `127` | End of table | 1  a| `0x004B`
|===
== UX305LA (ux305la.bin)

[horizontal]
File path:: `asus/ux305la.bin`
Product name:: UX305LA
Product version:: 1.0
Product family:: UX
Firmware vendor:: American Megatrends Inc.
Firmware version:: UX305LA.206
Release date:: 2015-08-03
SMBIOS version:: 2.8

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0011`
a| `7` | Cache information | 4  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `13` | Firmware language information | 1  a| `0x001D`
a| `14` | Group associations | 1  a| `0x001F`
a| `16` | Physical memory array | 1  a| `0x0013`
a| `17` | Memory device | 2  a| `0x0014`, `0x0015`
a| `19` | Memory array mapped address | 1  a| `0x0016`
a| `20` | Memory device mapped address | 2  a| `0x0017`, `0x0018`
a| `32` | System boot information | 1  a| `0x000C`
a| `127` | End of table | 1  a| `0x0020`
a| `131` | Intel vPro information | 1  a| `0x001E`
a| `221` | Intel firmware version information | 5  a| `0x0012`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
|===
== X580VD (x580vd.bin)

[horizontal]
File path:: `asus/x580vd.bin`
Product name:: X580VD
Product version:: 1.0
Product family:: VivoBook
Firmware vendor:: American Megatrends Inc.
Firmware version:: X580VD.317
Release date:: 2019-04-16
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0011`
a| `7` | Cache information | 3  a| `0x000E`, `0x000F`, `0x0010`
a| `10` | Onboard devices information | 1  a| `0x0024`
a| `11` | OEM strings | 1  a| `0x0025`
a| `12` | System configuration options | 1  a| `0x0026`
a| `13` | Firmware language information | 1  a| `0x0031`
a| `14` | Group associations | 2  a| `0x0030`, `0x0032`
a| `16` | Physical memory array | 1  a| `0x0008`
a| `17` | Memory device | 4  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `19` | Memory array mapped address | 1  a| `0x000D`
a| `20` | Memory device mapped address | 1  a| `0x0027`
a| `32` | System boot information | 1  a| `0x0007`
a| `127` | End of table | 1  a| `0x0034`
a| `130` | Intel Active Management Technology information | 1  a| `0x0028`
a| `131` | Intel vPro information | 1  a| `0x0029`
a| `136` | OEM-specific | 1  a| `0x002F`
a| `219` | Intel Management Engine interface information | 1  a| `0x0033`
a| `221` | Intel firmware version information | 5  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`
|===
== X756UAM (x756uam.bin)

[horizontal]
File path:: `asus/x756uam.bin`
Product name:: X756UAM
Product version:: 1.0
Product family:: X
Firmware vendor:: American Megatrends Inc.
Firmware version:: X756UAM.310
Release date:: 2019-04-17
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0015`
a| `7` | Cache information | 4  a| `0x0011`, `0x0012`, `0x0013`, `0x0014`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `13` | Firmware language information | 1  a| `0x0027`
a| `14` | Group associations | 2  a| `0x0026`, `0x0028`
a| `16` | Physical memory array | 1  a| `0x0016`
a| `17` | Memory device | 4  a| `0x0017`, `0x0018`, `0x0019`, `0x001A`
a| `19` | Memory array mapped address | 1  a| `0x001B`
a| `20` | Memory device mapped address | 2  a| `0x001C`, `0x001D`
a| `32` | System boot information | 1  a| `0x0010`
a| `127` | End of table | 1  a| `0x002A`
a| `130` | Intel Active Management Technology information | 1  a| `0x001E`
a| `131` | Intel vPro information | 1  a| `0x001F`
a| `136` | OEM-specific | 1  a| `0x0025`
a| `219` | Intel Management Engine interface information | 1  a| `0x0029`
a| `221` | Intel firmware version information | 5  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`
|===
== Zenbook 14 UX425JA (zenbook-ux425ja.bin)

[horizontal]
File path:: `asus/zenbook-ux425ja.bin`
Product name:: ZenBook UX425JA_UX425JA
Product version:: 1.0
Product family:: ZenBook
Firmware vendor:: American Megatrends Inc.
Firmware version:: UX425JA.316
Release date:: 2025-02-17
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0056`
a| `7` | Cache information | 4  a| `0x0052`, `0x0053`, `0x0054`, `0x0055`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x006D`
a| `14` | Group associations | 2  a| `0x006A`, `0x006B`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 2  a| `0x0048`, `0x0049`
a| `19` | Memory array mapped address | 1  a| `0x003E`
a| `20` | Memory device mapped address | 2  a| `0x004A`, `0x004B`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 16  a| `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`, `0x0062`, `0x0063`, `0x0064`, `0x0065`, `0x0066`, `0x0067`
a| `43` | TPM device | 1  a| `0x003A`
a| `127` | End of table | 1  a| `0x006E`
a| `131` | Intel vPro information | 1  a| `0x0057`
a| `136` | OEM-specific | 1  a| `0x0069`
a| `219` | Intel Management Engine interface information | 1  a| `0x006C`
a| `221` | Intel firmware version information | 7  a| `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0068`
|===
