= NEC
:toc:
:toclevels: 1

== PC-LZ750LS (pc-lz750ls.bin)

[horizontal]
File path:: `nec/pc-lz750ls.bin`
Product name:: PC-LZ750LS
Product version:: 
Product family:: LaVie/VersaPro
Firmware vendor:: NEC
Firmware version:: /738A0600
Release date:: 2012-12-04
SMBIOS version:: 2.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 8  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`
a| `10` | Onboard devices information | 1  a| `0x0010`
a| `11` | OEM strings | 1  a| `0x0011`
a| `13` | Firmware language information | 1  a| `0x001E`
a| `16` | Physical memory array | 1  a| `0x0018`
a| `17` | Memory device | 1  a| `0x0017`
a| `19` | Memory array mapped address | 1  a| `0x001A`
a| `20` | Memory device mapped address | 1  a| `0x0019`
a| `21` | Built-in pointing device | 1  a| `0x0012`
a| `22` | Portable battery | 1  a| `0x0013`
a| `32` | System boot information | 1  a| `0x0014`
a| `39` | System power supply | 1  a| `0x0015`
a| `127` | End of table | 1  a| `0x0021`
a| `131` | Intel vPro information | 1  a| `0x001C`
a| `133` | OEM-specific | 1  a| `0x0016`
a| `136` | OEM-specific | 1  a| `0x001D`
|===
