= Foxconn
:toc:
:toclevels: 1

== M61PMV (m61pmv.bin)

[horizontal]
File path:: `foxconn/m61pmv.bin`
Product name:: M61PMV
Product version:: FAB 1.1
Product family:: 
Firmware vendor:: Phoenix Technologies, LTD
Firmware version:: P08
Release date:: 2009-12-04
SMBIOS version:: 2.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 2  a| `0x0006`, `0x0007`
a| `7` | Cache information | 2  a| `0x0008`, `0x0009`
a| `8` | Port connector information | 22  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 4  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `13` | Firmware language information | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 2  a| `0x0026`, `0x0027`
a| `19` | Memory array mapped address | 1  a| `0x0028`
a| `20` | Memory device mapped address | 2  a| `0x0029`, `0x002A`
a| `32` | System boot information | 1  a| `0x002B`
a| `127` | End of table | 1  a| `0x0030`
a| `188` | OEM-specific | 1  a| `0x002C`
a| `190` | OEM-specific | 1  a| `0x002D`
a| `192` | OEM-specific | 1  a| `0x002E`
a| `194` | OEM-specific | 1  a| `0x002F`
|===
