<?xml version="1.0" encoding="utf-8"?>
<!--
    OpenDMI: Cross-platform DMI/SMBIOS framework
    Copyright (c) 2025-2026, The OpenDMI contributors

    SPDX-License-Identifier: BSD-3-Clause
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dmi="http://opendmi.org/schemas/opendmi.xsd"
           targetNamespace="http://opendmi.org/schemas/opendmi.xsd"
           elementFormDefault="qualified">
    <xs:element name="dump" type="dmi:dumpType" />

    <xs:complexType name="dumpType">
        <xs:sequence>
            <xs:element name="entry" type="dmi:entryType" minOccurs="1" maxOccurs="1" />
            <xs:element name="entity" type="dmi:entityType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="created-at" type="xs:dateTime" use="optional" />
    </xs:complexType>

    <xs:complexType name="entryType">
        <xs:attribute name="smbios-version" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="entityType">
        <xs:attribute name="handle" type="xs:string" use="required" />
        <xs:attribute name="type" type="xs:unsignedInt" use="required" />
        <xs:attribute name="length" type="xs:unsignedInt" use="required" />
        <xs:attribute name="state" type="dmi:entityStateList" use="optional" />
    </xs:complexType>

    <xs:simpleType name="entityStateList">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="decoded" />
                    <xs:enumeration value="linked" />
                    <xs:enumeration value="valid" />
                    <xs:enumeration value="incomplete" />
                    <xs:enumeration value="partial" />
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>
</xs:schema>
