//
// OpenDMI: Cross-platform DMI/SMBIOS framework
// Copyright (c) 2025-2026, The OpenDMI contributors
//
// SPDX-License-Identifier: BSD-3-Clause
//
#include <config.h>

#include <string.h>
#include <locale.h>
#include <stdio.h>
#include <ctype.h>
#include <inttypes.h>

#include <opendmi/internal.h>
#include <opendmi/utils.h>
#include <opendmi/utils/name.h>
#include <opendmi/locale.h>

#ifdef ENABLE_ICU
#   include <unicode/uclean.h>
#   include <unicode/udata.h>
#   include <unicode/ures.h>
#   include <unicode/uloc.h>
#   include <unicode/ustring.h>
#   include <unicode/upluralrules.h>

/**
 * @internal
 * @brief Name of the resource package of the library, must match the name the
 * bundles are packaged with, see `add_resources()` in the build files.
 */
#define DMI_RESOURCE_PACKAGE "libopendmi"

/**
 * @internal
 * @brief Resource data of the library, generated by `pkgdata`.
 */
extern const char libopendmi_dat[];

/**
 * @internal
 * @brief String of a resource table, converted to UTF-8 on loading.
 */
typedef struct dmi_resource_string
{
    char *key;
    char *value;
} dmi_resource_string_t;

/**
 * @internal
 * @brief Table of a resource package, loaded on the first lookup.
 */
typedef struct dmi_resource_table
{
    char                  *name;
    dmi_resource_string_t *strings;
    size_t                 string_count;
} dmi_resource_table_t;

/**
 * @internal
 * @brief Opened resource package.
 */
struct dmi_resource
{
    char                 *package;
    UResourceBundle      *bundle;
    dmi_resource_table_t *tables;
    size_t                table_count;
    dmi_resource_t       *next;
};

// Locale is process-wide, and so is the list of opened packages, which are
// reopened when the locale changes
static const char     *dmi_locale_name;
static dmi_resource_t *dmi_resources;

// Resources of the library itself, opened on the first name lookup
static dmi_resource_t *dmi_library_resource;
static bool            dmi_library_failed;

static bool dmi_resource_reopen(dmi_resource_t *resource);
static void dmi_resource_release(dmi_resource_t *resource);
static const dmi_resource_table_t *dmi_resource_table(dmi_resource_t *resource, const char *name);
static bool dmi_resource_load(const dmi_resource_t *resource, dmi_resource_table_t *table);
static const char *dmi_resource_plural(dmi_resource_t *resource, const char *word, intmax_t number);
#endif // ENABLE_ICU

/**
 * @internal
 * @brief Name of the resource table holding the texts of values which have
 * no text of their own, e.g. unknown enumeration identifiers.
 */
#define DMI_VALUE_TABLE "value"

/**
 * @internal
 * @brief Name of the resource table holding the plural forms of words.
 */
#define DMI_PLURAL_TABLE "plural"

/**
 * @internal
 * @brief Text being built by `dmi_message_format`().
 */
typedef struct dmi_message_buffer
{
    char   *data;
    size_t  length;
    size_t  capacity;
} dmi_message_buffer_t;

static bool dmi_message_append(dmi_message_buffer_t *buffer, const char *text, size_t length);
static bool dmi_message_substitute(
        dmi_message_buffer_t    *buffer,
        dmi_resource_t          *resource,
        const dmi_message_arg_t *arg,
        const char              *word,
        size_t                   word_length);

void dmi_locale_init(void)
{
    // Messages of the system are taken from the locale of the environment,
    // while numbers are left as they are, so that machine-readable output
    // does not depend on the locale
    setlocale(LC_CTYPE, "");
#ifdef LC_MESSAGES
    setlocale(LC_MESSAGES, "");
#endif

    // Printable names are translated to the locale of the environment, and
    // are left in English if there is no translation for it
    dmi_set_locale(nullptr);
}

bool dmi_set_locale(const char *locale)
{
#ifdef ENABLE_ICU
    dmi_locale_name = locale;

    bool success = true;

    // Loaded strings belong to the previous locale, so they are dropped and
    // the packages are reopened
    for (dmi_resource_t *resource = dmi_resources; resource != nullptr; resource = resource->next) {
        dmi_resource_release(resource);

        if (not dmi_resource_reopen(resource))
            success = false;
    }

    return success;
#else
    dmi_unused(locale);

    return false;
#endif
}

const char *dmi_get_locale(void)
{
#ifdef ENABLE_ICU
    if (dmi_resources == nullptr)
        return dmi_locale_name;

    UErrorCode status = U_ZERO_ERROR;
    const char *name = ures_getLocaleByType(dmi_resources->bundle, ULOC_VALID_LOCALE, &status);

    return U_SUCCESS(status) ? name : nullptr;
#else
    return nullptr;
#endif
}

dmi_resource_t *dmi_resource_open(const char *package, const void *data)
{
#ifdef ENABLE_ICU
    if ((package == nullptr) or (data == nullptr))
        return nullptr;

    UErrorCode status = U_ZERO_ERROR;

    u_init(&status);
    if (U_FAILURE(status))
        return nullptr;

    // Package data is registered under its own name, which is also the path
    // the bundles are opened with
    udata_setAppData(package, data, &status);
    if (U_FAILURE(status))
        return nullptr;

    dmi_resource_t *resource = dmi_alloc(nullptr, sizeof(*resource));
    if (resource == nullptr)
        return nullptr;

    size_t size = strlen(package) + 1;

    resource->package = dmi_alloc(nullptr, size);
    if (resource->package == nullptr) {
        dmi_free(resource);
        return nullptr;
    }

    memcpy(resource->package, package, size);

    if (not dmi_resource_reopen(resource)) {
        dmi_free(resource->package);
        dmi_free(resource);

        return nullptr;
    }

    resource->next = dmi_resources;
    dmi_resources  = resource;

    return resource;
#else
    dmi_unused(package);
    dmi_unused(data);

    return nullptr;
#endif
}

const char *dmi_resource_string(dmi_resource_t *resource, const char *table, const char *key)
{
#ifdef ENABLE_ICU
    if ((resource == nullptr) or (table == nullptr) or (key == nullptr))
        return nullptr;

    const dmi_resource_table_t *strings = dmi_resource_table(resource, table);
    if (strings == nullptr)
        return nullptr;

    for (size_t i = 0; i < strings->string_count; i++) {
        if (strcmp(strings->strings[i].key, key) == 0)
            return strings->strings[i].value;
    }

    return nullptr;
#else
    dmi_unused(resource);
    dmi_unused(table);
    dmi_unused(key);

    return nullptr;
#endif
}

void dmi_resource_close(dmi_resource_t *resource)
{
#ifdef ENABLE_ICU
    if (resource == nullptr)
        return;

    for (dmi_resource_t **link = &dmi_resources; *link != nullptr; link = &(*link)->next) {
        if (*link == resource) {
            *link = resource->next;
            break;
        }
    }

    dmi_resource_release(resource);

    dmi_free(resource->package);
    dmi_free(resource);
#else
    dmi_unused(resource);
#endif
}

const char *dmi_value_text(const char *key, const char *fallback)
{
    const char *text = dmi_locale_string(DMI_VALUE_TABLE, key);

    if (text == nullptr)
        return fallback;

    return text;
}

const char *dmi_locale_string(const char *table, const char *key)
{
#ifdef ENABLE_ICU
    if ((table == nullptr) or (key == nullptr))
        return nullptr;

    // Resources of the library are opened on the first lookup
    if ((dmi_library_resource == nullptr) and not dmi_library_failed) {
        dmi_library_resource = dmi_resource_open(DMI_RESOURCE_PACKAGE, libopendmi_dat);
        dmi_library_failed   = (dmi_library_resource == nullptr);
    }

    return dmi_resource_string(dmi_library_resource, table, key);
#else
    dmi_unused(table);
    dmi_unused(key);

    return nullptr;
#endif
}

char *dmi_message_format(
        dmi_resource_t          *resource,
        const char              *pattern,
        const dmi_message_arg_t *args,
        size_t                   count)
{
    if (pattern == nullptr)
        return nullptr;

    dmi_message_buffer_t buffer = {};
    const char *text = pattern;

    while (*text != 0) {
        const char *brace = strchr(text, '{');

        if (brace == nullptr) {
            if (not dmi_message_append(&buffer, text, strlen(text)))
                goto failure;
            break;
        }

        if (not dmi_message_append(&buffer, text, (size_t)(brace - text)))
            goto failure;

        // Doubled brace stands for the brace itself
        if (brace[1] == '{') {
            if (not dmi_message_append(&buffer, "{", 1))
                goto failure;

            text = brace + 2;
            continue;
        }

        const char *end = strchr(brace, '}');
        if ((end == nullptr) or not isdigit((unsigned char)brace[1]))
            goto failure;

        size_t index = (size_t)(brace[1] - '0');

        // Plural form of a word follows the index of the argument selecting it
        const char *word        = nullptr;
        size_t      word_length = 0;

        if (brace[2] == ':') {
            word        = brace + 3;
            word_length = (size_t)(end - word);
        } else if (brace + 2 != end) {
            goto failure;
        }

        if (index >= count)
            goto failure;

        if (not dmi_message_substitute(&buffer, resource, &args[index], word, word_length))
            goto failure;

        text = end + 1;
    }

    if (not dmi_message_append(&buffer, "", 1))
        goto failure;

    return buffer.data;

failure:
    dmi_free(buffer.data);

    return nullptr;
}

char *dmi_resource_message(
        dmi_resource_t          *resource,
        const char              *table,
        const char              *key,
        const dmi_message_arg_t *args,
        size_t                   count)
{
    const char *pattern = dmi_resource_string(resource, table, key);
    if (pattern == nullptr)
        return nullptr;

    return dmi_message_format(resource, pattern, args, count);
}

//
// Append text to the message being built, growing the buffer by powers of two
// to keep the number of reallocations low.
//
static bool dmi_message_append(dmi_message_buffer_t *buffer, const char *text, size_t length)
{
    if (buffer->length + length > buffer->capacity) {
        size_t capacity = (buffer->capacity > 0) ? buffer->capacity : 64;

        while (capacity < buffer->length + length)
            capacity <<= 1;

        char *data = dmi_alloc(nullptr, capacity);
        if (data == nullptr)
            return false;

        if (buffer->length > 0)
            memcpy(data, buffer->data, buffer->length);

        dmi_free(buffer->data);

        buffer->data     = data;
        buffer->capacity = capacity;
    }

    memcpy(buffer->data + buffer->length, text, length);
    buffer->length += length;

    return true;
}

//
// Append the value of an argument, and the plural form of the word it selects,
// if the placeholder names one.
//
static bool dmi_message_substitute(
        dmi_message_buffer_t    *buffer,
        dmi_resource_t          *resource,
        const dmi_message_arg_t *arg,
        const char              *word,
        size_t                   word_length)
{
    char number[sizeof("-9223372036854775808")];
    const char *text;

    if (arg->type == DMI_MESSAGE_ARG_NUMBER) {
        if (snprintf(number, sizeof(number), "%" PRIdMAX, arg->number) < 0)
            return false;

        text = number;
    } else {
        text = (arg->text != nullptr) ? arg->text : "";
    }

    if (word == nullptr)
        return dmi_message_append(buffer, text, strlen(text));

    // Plural forms are selected by numbers only, and are left out if the
    // locale has no forms of the word
    if (arg->type != DMI_MESSAGE_ARG_NUMBER)
        return false;

    char name[64];
    if (word_length >= sizeof(name))
        return false;

    memcpy(name, word, word_length);
    name[word_length] = 0;

#ifdef ENABLE_ICU
    const char *form = dmi_resource_plural(resource, name, arg->number);
#else
    dmi_unused(resource);

    const char *form = nullptr;
#endif

    if (form == nullptr)
        return false;

    return dmi_message_append(buffer, form, strlen(form));
}

#ifdef ENABLE_ICU
//
// Open the bundle of the package for the current locale. Locales with no
// bundle of their own fall back to the root bundle of the package.
//
static bool dmi_resource_reopen(dmi_resource_t *resource)
{
    UErrorCode status = U_ZERO_ERROR;

    resource->bundle = ures_open(resource->package, dmi_locale_name, &status);
    if (U_FAILURE(status)) {
        resource->bundle = nullptr;
        return false;
    }

    return true;
}

//
// Release the bundle and the strings loaded from it, keeping the package
// name, so that the resource can be reopened.
//
static void dmi_resource_release(dmi_resource_t *resource)
{
    for (size_t i = 0; i < resource->table_count; i++) {
        dmi_resource_table_t *table = &resource->tables[i];

        for (size_t j = 0; j < table->string_count; j++) {
            dmi_free(table->strings[j].key);
            dmi_free(table->strings[j].value);
        }

        dmi_free(table->strings);
        dmi_free(table->name);
    }

    dmi_free(resource->tables);

    resource->tables      = nullptr;
    resource->table_count = 0;

    if (resource->bundle != nullptr) {
        ures_close(resource->bundle);
        resource->bundle = nullptr;
    }
}

//
// Find a loaded table of the package, loading it on the first lookup. Tables
// which are not in the package are cached with no strings.
//
static const dmi_resource_table_t *dmi_resource_table(dmi_resource_t *resource, const char *name)
{
    if (resource->bundle == nullptr)
        return nullptr;

    for (size_t i = 0; i < resource->table_count; i++) {
        if (strcmp(resource->tables[i].name, name) == 0)
            return &resource->tables[i];
    }

    dmi_resource_table_t *tables = dmi_alloc_array(nullptr, sizeof(*tables), resource->table_count + 1);
    if (tables == nullptr)
        return nullptr;

    if (resource->table_count > 0)
        memcpy(tables, resource->tables, resource->table_count * sizeof(*tables));

    dmi_free(resource->tables);
    resource->tables = tables;

    dmi_resource_table_t *table = &resource->tables[resource->table_count];
    size_t size = strlen(name) + 1;

    table->name = dmi_alloc(nullptr, size);
    if (table->name == nullptr)
        return nullptr;

    memcpy(table->name, name, size);
    resource->table_count++;

    if (not dmi_resource_load(resource, table)) {
        dmi_free(table->strings);

        table->strings      = nullptr;
        table->string_count = 0;
    }

    return table;
}

//
// Convert all strings of the table to UTF-8, so that they are kept as long as
// the package is open and the locale is not changed.
//
static bool dmi_resource_load(const dmi_resource_t *resource, dmi_resource_table_t *table)
{
    UErrorCode status = U_ZERO_ERROR;

    // Table name is a path, so that nested tables are reachable as well,
    // e.g. "processor/attributes"
    UResourceBundle *bundle = nullptr;

    for (const char *name = table->name; *name != 0;) {
        const char *separator = strchr(name, '/');
        size_t length = (separator != nullptr) ? (size_t)(separator - name) : strlen(name);

        char key[64];
        if (length >= sizeof(key))
            break;

        memcpy(key, name, length);
        key[length] = 0;

        UResourceBundle *nested = ures_getByKey(bundle ? bundle : resource->bundle, key, nullptr, &status);

        ures_close(bundle);
        bundle = nested;

        if (U_FAILURE(status))
            break;

        name += length;
        if (*name == '/')
            name++;
    }

    if (U_FAILURE(status) or (bundle == nullptr)) {
        ures_close(bundle);
        return false;
    }

    bool success = false;

    do {
        int32_t count = ures_getSize(bundle);
        if (count <= 0)
            break;

        table->strings = dmi_alloc_array(nullptr, sizeof(*table->strings), (size_t)count);
        if (table->strings == nullptr)
            break;

        for (int32_t i = 0; i < count; i++) {
            UResourceBundle *item = ures_getByIndex(bundle, i, nullptr, &status);
            if (U_FAILURE(status))
                break;

            int32_t length = 0;
            const UChar *value = ures_getString(item, &length, &status);
            const char  *key   = ures_getKey(item);

            if (U_SUCCESS(status) and (key != nullptr)) {
                // Keys belong to the bundle, and every UTF-16 code unit takes
                // at most 3 bytes in UTF-8
                size_t key_size = strlen(key) + 1;

                char *name = dmi_alloc(nullptr, key_size);
                char *text = dmi_alloc(nullptr, (size_t)length * 3 + 1);

                if ((name != nullptr) and (text != nullptr)) {
                    memcpy(name, key, key_size);
                    u_strToUTF8(text, length * 3 + 1, nullptr, value, length, &status);
                }

                if ((name != nullptr) and (text != nullptr) and U_SUCCESS(status)) {
                    table->strings[table->string_count].key   = name;
                    table->strings[table->string_count].value = text;
                    table->string_count++;
                } else {
                    dmi_free(name);
                    dmi_free(text);
                }
            }

            status = U_ZERO_ERROR;
            ures_close(item);
        }

        success = (table->string_count > 0);
    } while (false);

    ures_close(bundle);

    return success;
}

//
// Select the plural form of a word for a number, following the rules of the
// locale the resources are opened with.
//
static const char *dmi_resource_plural(dmi_resource_t *resource, const char *word, intmax_t number)
{
    if ((resource == nullptr) or (resource->bundle == nullptr))
        return nullptr;

    UErrorCode status = U_ZERO_ERROR;

    // Rules belong to the locale of the bundle rather than to the requested
    // one, since the forms come from the bundle as well. The root bundle
    // holds the text in English, while the rules of the root locale know the
    // "other" form only, so English rules are used for it.
    const char *locale = ures_getLocaleByType(resource->bundle, ULOC_VALID_LOCALE, &status);
    if (U_FAILURE(status))
        return nullptr;

    if ((locale == nullptr) or (strcmp(locale, "root") == 0))
        locale = "en";

    UPluralRules *rules = uplrules_open(locale, &status);
    if (U_FAILURE(status))
        return nullptr;

    UChar   keyword[32];
    int32_t length = uplrules_select(rules, (double)number, keyword, countof(keyword), &status);

    uplrules_close(rules);

    if (U_FAILURE(status))
        return nullptr;

    char form[32];

    u_strToUTF8(form, sizeof(form), nullptr, keyword, length, &status);
    if (U_FAILURE(status))
        return nullptr;

    char table[128];

    if (snprintf(table, sizeof(table), DMI_PLURAL_TABLE "/%s", word) >= (int)sizeof(table))
        return nullptr;

    const char *text = dmi_resource_string(resource, table, form);

    // Every locale has the "other" form, so it stands for the forms the
    // resources leave out
    if (text == nullptr)
        text = dmi_resource_string(resource, table, "other");

    return text;
}
#endif // ENABLE_ICU
