= Alldocube
:toc:
:toclevels: 1

== i1402A (i1402a.bin)

[horizontal]
File path:: `alldocube/i1402a.bin`
Product name:: i1402A
Product version:: Default string
Product family:: Notebook
Firmware vendor:: American Megatrends
Firmware version:: ODLF-BI-14-TU140SR410-SC60B-101-A
Release date:: 2020-09-21
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x003E`
a| `7` | Cache information | 3  a| `0x003B`, `0x003C`, `0x003D`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 2  a| `0x0048`, `0x0049`
a| `10` | Onboard devices information | 1  a| `0x001C`
a| `11` | OEM strings | 1  a| `0x001D`
a| `12` | System configuration options | 1  a| `0x001E`
a| `13` | Firmware language information | 1  a| `0x0043`
a| `14` | Group associations | 2  a| `0x004C`, `0x005F`
a| `16` | Physical memory array | 1  a| `0x0035`
a| `17` | Memory device | 4  a| `0x0036`, `0x0037`, `0x0038`, `0x0039`
a| `19` | Memory array mapped address | 1  a| `0x003A`
a| `20` | Memory device mapped address | 2  a| `0x003F`, `0x0040`
a| `26` | Voltage probe | 2  a| `0x0021`, `0x0030`
a| `27` | Cooling device | 3  a| `0x0027`, `0x002A`, `0x0032`
a| `28` | Temperature probe | 2  a| `0x0024`, `0x0031`
a| `29` | Electrical current probe | 2  a| `0x002D`, `0x0033`
a| `32` | System boot information | 1  a| `0x001F`
a| `34` | Management device | 1  a| `0x0020`
a| `35` | Management device component | 5  a| `0x0023`, `0x0026`, `0x0029`, `0x002C`, `0x002F`
a| `36` | Management device threshold data | 5  a| `0x0022`, `0x0025`, `0x0028`, `0x002B`, `0x002E`
a| `39` | System power supply | 1  a| `0x0034`
a| `41` | Onboard devices extended information | 18  a| `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`
a| `127` | End of table | 1  a| `0x0061`
a| `130` | Intel Active Management Technology information | 1  a| `0x0041`
a| `131` | Intel vPro information | 1  a| `0x0042`
a| `136` | OEM-specific | 1  a| `0x004B`
a| `219` | Intel Management Engine interface information | 1  a| `0x0060`
a| `221` | Intel firmware version information | 5  a| `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x004A`
|===
