= Honor
:toc:
:toclevels: 1

== MagicBook Art 14 2024 MRA-7211 (magicbook-art-14-2024-mra-7211.bin)

[horizontal]
File path:: `honor/magicbook-art-14-2024-mra-7211.bin`
Product name:: MRA-XXX
Product version:: M1030
Product family:: HONOR MagicBook
Firmware vendor:: HONOR
Firmware version:: 3.05
Release date:: 2025-03-07
SMBIOS version:: 3.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `9` | System slots | 5  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`
a| `11` | OEM strings | 1  a| `0x0012`
a| `13` | Firmware language information | 1  a| `0x0013`
a| `14` | Group associations | 2  a| `0x0014`, `0x0032`
a| `16` | Physical memory array | 1  a| `0x0015`
a| `17` | Memory device | 8  a| `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `19` | Memory array mapped address | 1  a| `0x001E`
a| `20` | Memory device mapped address | 8  a| `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`
a| `21` | Built-in pointing device | 1  a| `0x0027`
a| `22` | Portable battery | 1  a| `0x0028`
a| `43` | TPM device | 1  a| `0x0029`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x002A`
a| `219` | Intel Management Engine interface information | 1  a| `0x002B`
a| `221` | Intel firmware version information | 6  a| `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`
|===
