= Miscellaneous
:toc:
:toclevels: 1

== Noname [1] (noname-1.bin)

[horizontal]
File path:: `misc/noname-1.bin`
Product name:: Default string
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: 5.16
Release date:: 2024-09-05
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 14  a| `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 4  a| `0x0024`, `0x0025`, `0x0026`, `0x0027`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x002A`
a| `16` | Physical memory array | 1  a| `0x000A`
a| `17` | Memory device | 2  a| `0x0011`, `0x0014`
a| `18` | 32-bit memory error information | 3  a| `0x0009`, `0x0010`, `0x0013`
a| `19` | Memory array mapped address | 1  a| `0x000B`
a| `20` | Memory device mapped address | 2  a| `0x0012`, `0x0015`
a| `32` | System boot information | 1  a| `0x0007`
a| `41` | Onboard devices extended information | 2  a| `0x0028`, `0x0029`
a| `43` | TPM device | 1  a| `0x0008`
a| `127` | End of table | 1  a| `0x002B`
|===
== nVidia nForce (nvidia-nforce.bin)

[horizontal]
File path:: `misc/nvidia-nforce.bin`
Product name:: 
Product version:: 
Product family:: -
Firmware vendor:: Phoenix Technologies, LTD
Firmware version:: 6.00 PG
Release date:: 2004-07-29
SMBIOS version:: 2.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 3  a| `0x0006`, `0x0007`, `0x0008`
a| `7` | Cache information | 2  a| `0x0009`, `0x000A`
a| `8` | Port connector information | 9  a| `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`
a| `9` | System slots | 6  a| `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `13` | Firmware language information | 1  a| `0x001A`
a| `16` | Physical memory array | 1  a| `0x001B`
a| `17` | Memory device | 3  a| `0x001C`, `0x001D`, `0x001E`
a| `19` | Memory array mapped address | 1  a| `0x001F`
a| `20` | Memory device mapped address | 3  a| `0x0020`, `0x0021`, `0x0022`
a| `32` | System boot information | 1  a| `0x0023`
a| `127` | End of table | 1  a| `0x0024`
|===
== X99H (x99h.bin)

[horizontal]
File path:: `misc/x99h.bin`
Product name:: X99
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: 5.11
Release date:: 2023-05-09
SMBIOS version:: 3.0

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0077`
a| `7` | Cache information | 3  a| `0x0074`, `0x0075`, `0x0076`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 7  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `10` | Onboard devices information | 1  a| `0x0023`
a| `11` | OEM strings | 1  a| `0x0024`
a| `12` | System configuration options | 1  a| `0x0025`
a| `13` | Firmware language information | 1  a| `0x0078`
a| `16` | Physical memory array | 4  a| `0x0056`, `0x005D`, `0x0066`, `0x006D`
a| `17` | Memory device | 24  a| `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005F`, `0x0060`, `0x0061`, `0x0062`, `0x0064`, `0x0065`, `0x0067`, `0x0068`, `0x0069`, `0x006A`, `0x006B`, `0x006C`, `0x006E`, `0x006F`, `0x0070`, `0x0071`, `0x0072`, `0x0073`
a| `19` | Memory array mapped address | 1  a| `0x005E`
a| `20` | Memory device mapped address | 1  a| `0x0063`
a| `26` | Voltage probe | 4  a| `0x0028`, `0x0038`, `0x003B`, `0x0050`
a| `27` | Cooling device | 5  a| `0x002E`, `0x0031`, `0x0041`, `0x0047`, `0x0052`
a| `28` | Temperature probe | 4  a| `0x002B`, `0x003E`, `0x0044`, `0x0051`
a| `29` | Electrical current probe | 4  a| `0x0034`, `0x004A`, `0x004D`, `0x0053`
a| `32` | System boot information | 1  a| `0x0026`
a| `34` | Management device | 2  a| `0x0027`, `0x0037`
a| `35` | Management device component | 13  a| `0x002A`, `0x002D`, `0x0030`, `0x0033`, `0x0036`, `0x003A`, `0x003D`, `0x0040`, `0x0043`, `0x0046`, `0x0049`, `0x004C`, `0x004F`
a| `36` | Management device threshold data | 13  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`, `0x0035`, `0x0039`, `0x003C`, `0x003F`, `0x0042`, `0x0045`, `0x0048`, `0x004B`, `0x004E`
a| `39` | System power supply | 1  a| `0x0054`
a| `41` | Onboard devices extended information | 1  a| `0x0055`
a| `127` | End of table | 1  a| `0x0079`
|===
