= Apple
:toc:
:toclevels: 1

== iMac11,3 (imac11-3.bin)

[horizontal]
File path:: `apple/imac11-3.bin`
Product name:: iMac11,3
Product version:: 1.0
Product family:: iMac
Firmware vendor:: Apple Inc.
Firmware version:: 99.0.0.0.0
Release date:: 2019-06-13
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0036`
a| `1` | System information | 1  a| `0x0037`
a| `2` | Baseboard or module information | 1  a| `0x0038`
a| `3` | System enclosure or chassis | 1  a| `0x0039`
a| `4` | Processor information | 8  a| `0x0000`, `0x0005`, `0x000A`, `0x000F`, `0x0014`, `0x0019`, `0x001E`, `0x0023`
a| `7` | Cache information | 32  a| `0x0001`, `0x0002`, `0x0003`, `0x0004`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0024`, `0x0025`, `0x0026`, `0x0027`
a| `8` | Port connector information | 14  a| `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`
a| `9` | System slots | 1  a| `0x0048`
a| `10` | Onboard devices information | 4  a| `0x0049`, `0x004A`, `0x004B`, `0x004C`
a| `12` | System configuration options | 1  a| `0x004D`
a| `13` | Firmware language information | 1  a| `0x004E`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 4  a| `0x0029`, `0x002C`, `0x002F`, `0x0032`
a| `19` | Memory array mapped address | 1  a| `0x0035`
a| `20` | Memory device mapped address | 4  a| `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `32` | System boot information | 1  a| `0x004F`
a| `127` | End of table | 1  a| `0xFFFD`
a| `128` | Apple firmware volume information | 1  a| `0x0051`
a| `130` | Apple memory SPD data | 4  a| `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `131` | Apple processor type information | 1  a| `0x0050`
a| `132` | Apple processor bus speed information | 1  a| `0x0052`
|===
