= Intel
:toc:
:toclevels: 1

== NUC NUC5PPYB (nuc-nuc5ppyb.bin)

[horizontal]
File path:: `intel/nuc-nuc5ppyb.bin`
Product name:: 
Product version:: 
Product family:: 
Firmware vendor:: Intel Corp.
Firmware version:: PYBSWCEL.86A.0050.2016.0223.1234
Release date:: 2016-02-23
SMBIOS version:: 2.8

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0031`
a| `7` | Cache information | 2  a| `0x002F`, `0x0030`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 1  a| `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0032`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 1  a| `0x0026`
a| `19` | Memory array mapped address | 1  a| `0x0025`
a| `20` | Memory device mapped address | 1  a| `0x0027`
a| `32` | System boot information | 1  a| `0x0028`
a| `41` | Onboard devices extended information | 6  a| `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `126` | Inactive | 1  a| `0x0007`
a| `127` | End of table | 1  a| `0x0033`
|===
== NUC10i5FNH (nuc10i5fnh.bin)

[horizontal]
File path:: `intel/nuc10i5fnh.bin`
Product name:: NUC10i5FNH
Product version:: K61160-306
Product family:: FN
Firmware vendor:: Intel Corp.
Firmware version:: FNCML357.0050.2021.0303.2141
Release date:: 2021-03-03
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0045`
a| `7` | Cache information | 3  a| `0x0042`, `0x0043`, `0x0044`
a| `8` | Port connector information | 11  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`
a| `9` | System slots | 5  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`
a| `10` | Onboard devices information | 1  a| `0x0014`
a| `11` | OEM strings | 1  a| `0x0015`
a| `12` | System configuration options | 1  a| `0x0016`
a| `13` | Firmware language information | 1  a| `0x004D`
a| `14` | Group associations | 2  a| `0x004A`, `0x004B`
a| `15` | System event log | 1  a| `0x003A`
a| `16` | Physical memory array | 1  a| `0x0036`
a| `17` | Memory device | 2  a| `0x0037`, `0x0038`
a| `19` | Memory array mapped address | 1  a| `0x0039`
a| `20` | Memory device mapped address | 2  a| `0x003B`, `0x003C`
a| `26` | Voltage probe | 2  a| `0x0019`, `0x0028`
a| `27` | Cooling device | 3  a| `0x001F`, `0x0022`, `0x002A`
a| `28` | Temperature probe | 2  a| `0x001C`, `0x0029`
a| `29` | Electrical current probe | 2  a| `0x0025`, `0x002B`
a| `32` | System boot information | 1  a| `0x0017`
a| `34` | Management device | 1  a| `0x0018`
a| `35` | Management device component | 5  a| `0x001B`, `0x001E`, `0x0021`, `0x0024`, `0x0027`
a| `36` | Management device threshold data | 5  a| `0x001A`, `0x001D`, `0x0020`, `0x0023`, `0x0026`
a| `39` | System power supply | 1  a| `0x002C`
a| `41` | Onboard devices extended information | 8  a| `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`
a| `44` | Processor additional information | 1  a| `0x0035`
a| `127` | End of table | 1  a| `0x004E`
a| `131` | Intel vPro information | 1  a| `0x0047`
a| `136` | OEM-specific | 1  a| `0x0049`
a| `219` | Intel Management Engine interface information | 1  a| `0x004C`
a| `221` | Intel firmware version information | 6  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0048`
|===
== NUC8i3BEH (nuc8i3beh.bin)

[horizontal]
File path:: `intel/nuc8i3beh.bin`
Product name:: NUC8i3BEH
Product version:: J72753-304
Product family:: Intel NUC
Firmware vendor:: Intel Corp.
Firmware version:: BECFL357.86A.0092.2023.0214.1114
Release date:: 2023-02-14
SMBIOS version:: 3.2.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0048`
a| `7` | Cache information | 3  a| `0x0045`, `0x0046`, `0x0047`
a| `8` | Port connector information | 11  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`
a| `9` | System slots | 5  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`
a| `10` | Onboard devices information | 1  a| `0x0014`
a| `11` | OEM strings | 1  a| `0x0015`
a| `12` | System configuration options | 1  a| `0x0016`
a| `13` | Firmware language information | 1  a| `0x004C`
a| `14` | Group associations | 2  a| `0x004F`, `0x0050`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 2  a| `0x003C`, `0x003D`
a| `19` | Memory array mapped address | 1  a| `0x003E`
a| `20` | Memory device mapped address | 2  a| `0x0049`, `0x004A`
a| `26` | Voltage probe | 2  a| `0x001F`, `0x002E`
a| `27` | Cooling device | 3  a| `0x0025`, `0x0028`, `0x0030`
a| `28` | Temperature probe | 2  a| `0x0022`, `0x002F`
a| `29` | Electrical current probe | 2  a| `0x002B`, `0x0031`
a| `32` | System boot information | 1  a| `0x001D`
a| `34` | Management device | 1  a| `0x001E`
a| `35` | Management device component | 5  a| `0x0021`, `0x0024`, `0x0027`, `0x002A`, `0x002D`
a| `36` | Management device threshold data | 5  a| `0x0020`, `0x0023`, `0x0026`, `0x0029`, `0x002C`
a| `39` | System power supply | 1  a| `0x0032`
a| `41` | Onboard devices extended information | 8  a| `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `43` | TPM device | 1  a| `0x003F`
a| `127` | End of table | 1  a| `0x0052`
a| `131` | Intel vPro information | 1  a| `0x004B`
a| `136` | OEM-specific | 1  a| `0x004E`
a| `219` | Intel Management Engine interface information | 1  a| `0x0051`
a| `221` | Intel firmware version information | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x004D`
|===
== NUC8i7HVK (nuc8i7hvk.bin)

[horizontal]
File path:: `intel/nuc8i7hvk.bin`
Product name:: NUC8i7HVK
Product version:: J71485-603
Product family:: HN
Firmware vendor:: Intel Corp.
Firmware version:: HNKBLi70.86A.0070.2022.1103.1527
Release date:: 2022-11-03
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0037`
a| `7` | Cache information | 3  a| `0x0034`, `0x0035`, `0x0036`
a| `8` | Port connector information | 31  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `9` | System slots | 2  a| `0x0023`, `0x0024`
a| `11` | OEM strings | 1  a| `0x0025`
a| `12` | System configuration options | 1  a| `0x0026`
a| `13` | Firmware language information | 1  a| `0x003C`
a| `14` | Group associations | 2  a| `0x0043`, `0x0044`
a| `16` | Physical memory array | 1  a| `0x002F`
a| `17` | Memory device | 2  a| `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 2  a| `0x0038`, `0x0039`
a| `32` | System boot information | 1  a| `0x0027`
a| `41` | Onboard devices extended information | 7  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `43` | TPM device | 1  a| `0x0033`
a| `127` | End of table | 1  a| `0x0046`
a| `130` | Intel Active Management Technology information | 1  a| `0x003A`
a| `131` | Intel vPro information | 1  a| `0x003B`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `219` | Intel Management Engine interface information | 1  a| `0x0045`
a| `221` | Intel firmware version information | 5  a| `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`
|===
== S2600KP (s2600kp.bin)

[horizontal]
File path:: `intel/s2600kp.bin`
Product name:: S2600KP
Product version:: FFF
Product family:: Family
Firmware vendor:: Intel Corporation
Firmware version:: SE5C610.86B.01.01.0005.101720141054
Release date:: 2014-10-17
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x001B`, `0x001F`
a| `7` | Cache information | 6  a| `0x0018`, `0x0019`, `0x001A`, `0x001C`, `0x001D`, `0x001E`
a| `8` | Port connector information | 18  a| `0x0004`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`
a| `9` | System slots | 6  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0049`, `0x004A`
a| `10` | Onboard devices information | 1  a| `0x004B`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `13` | Firmware language information | 1  a| `0x000B`
a| `16` | Physical memory array | 4  a| `0x0020`, `0x0026`, `0x002C`, `0x0032`
a| `17` | Memory device | 8  a| `0x0022`, `0x0024`, `0x0028`, `0x002A`, `0x002E`, `0x0030`, `0x0034`, `0x0036`
a| `19` | Memory array mapped address | 4  a| `0x0021`, `0x0027`, `0x002D`, `0x0033`
a| `20` | Memory device mapped address | 8  a| `0x0023`, `0x0025`, `0x0029`, `0x002B`, `0x002F`, `0x0031`, `0x0035`, `0x0037`
a| `24` | Hardware security | 1  a| `0x0013`
a| `27` | Cooling device | 1  a| `0x000C`
a| `28` | Temperature probe | 1  a| `0x000D`
a| `32` | System boot information | 1  a| `0x000E`
a| `34` | Management device | 1  a| `0x000F`
a| `35` | Management device component | 1  a| `0x0010`
a| `36` | Management device threshold data | 1  a| `0x0011`
a| `38` | IPMI device information | 1  a| `0x0012`
a| `39` | System power supply | 1  a| `0x0017`
a| `41` | Onboard devices extended information | 4  a| `0x0014`, `0x0015`, `0x0016`, `0x004C`
a| `127` | End of table | 1  a| `0xFEFF`
|===
== S2600TP (s2600tp.bin)

[horizontal]
File path:: `intel/s2600tp.bin`
Product name:: S2600TP
Product version:: FFF
Product family:: Family
Firmware vendor:: Intel Corporation
Firmware version:: SE5C610.86B.01.01.0009.060120151350
Release date:: 2015-06-01
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x001B`, `0x001F`
a| `7` | Cache information | 6  a| `0x0018`, `0x0019`, `0x001A`, `0x001C`, `0x001D`, `0x001E`
a| `8` | Port connector information | 18  a| `0x0004`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`
a| `9` | System slots | 7  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0055`, `0x0056`, `0x0057`
a| `10` | Onboard devices information | 1  a| `0x0058`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 1  a| `0x000A`
a| `13` | Firmware language information | 1  a| `0x000B`
a| `16` | Physical memory array | 2  a| `0x0020`, `0x0032`
a| `17` | Memory device | 16  a| `0x0022`, `0x0024`, `0x0026`, `0x0028`, `0x002A`, `0x002C`, `0x002E`, `0x0030`, `0x0034`, `0x0036`, `0x0038`, `0x003A`, `0x003C`, `0x003E`, `0x0040`, `0x0042`
a| `19` | Memory array mapped address | 2  a| `0x0021`, `0x0033`
a| `20` | Memory device mapped address | 16  a| `0x0023`, `0x0025`, `0x0027`, `0x0029`, `0x002B`, `0x002D`, `0x002F`, `0x0031`, `0x0035`, `0x0037`, `0x0039`, `0x003B`, `0x003D`, `0x003F`, `0x0041`, `0x0043`
a| `24` | Hardware security | 1  a| `0x0013`
a| `27` | Cooling device | 1  a| `0x000C`
a| `28` | Temperature probe | 1  a| `0x000D`
a| `32` | System boot information | 1  a| `0x000E`
a| `34` | Management device | 1  a| `0x000F`
a| `35` | Management device component | 1  a| `0x0010`
a| `36` | Management device threshold data | 1  a| `0x0011`
a| `38` | IPMI device information | 1  a| `0x0012`
a| `39` | System power supply | 1  a| `0x0017`
a| `41` | Onboard devices extended information | 4  a| `0x0014`, `0x0015`, `0x0016`, `0x0059`
a| `127` | End of table | 1  a| `0xFEFF`
|===
== S2600WTT (s2600wtt.bin)

[horizontal]
File path:: `intel/s2600wtt.bin`
Product name:: S2600WTT
Product version:: FFF
Product family:: Family
Firmware vendor:: Intel Corporation
Firmware version:: SE5C610.86B.01.01.0014.121820151719
Release date:: 2015-12-18
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x001B`, `0x001F`
a| `7` | Cache information | 6  a| `0x0018`, `0x0019`, `0x001A`, `0x001C`, `0x001D`, `0x001E`
a| `8` | Port connector information | 19  a| `0x0004`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`, `0x0062`, `0x0063`, `0x0064`, `0x0065`, `0x0066`, `0x0067`, `0x0068`, `0x0069`
a| `9` | System slots | 7  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x006A`, `0x006B`, `0x006C`
a| `10` | Onboard devices information | 1  a| `0x006D`
a| `11` | OEM strings | 1  a| `0x0009`
a| `12` | System configuration options | 2  a| `0x000A`, `0x006E`
a| `13` | Firmware language information | 1  a| `0x000B`
a| `16` | Physical memory array | 4  a| `0x0020`, `0x002E`, `0x003C`, `0x004A`
a| `17` | Memory device | 24  a| `0x0022`, `0x0024`, `0x0026`, `0x0028`, `0x002A`, `0x002C`, `0x0030`, `0x0032`, `0x0034`, `0x0036`, `0x0038`, `0x003A`, `0x003E`, `0x0040`, `0x0042`, `0x0044`, `0x0046`, `0x0048`, `0x004C`, `0x004E`, `0x0050`, `0x0052`, `0x0054`, `0x0056`
a| `19` | Memory array mapped address | 4  a| `0x0021`, `0x002F`, `0x003D`, `0x004B`
a| `20` | Memory device mapped address | 24  a| `0x0023`, `0x0025`, `0x0027`, `0x0029`, `0x002B`, `0x002D`, `0x0031`, `0x0033`, `0x0035`, `0x0037`, `0x0039`, `0x003B`, `0x003F`, `0x0041`, `0x0043`, `0x0045`, `0x0047`, `0x0049`, `0x004D`, `0x004F`, `0x0051`, `0x0053`, `0x0055`, `0x0057`
a| `24` | Hardware security | 1  a| `0x0013`
a| `27` | Cooling device | 1  a| `0x000C`
a| `28` | Temperature probe | 1  a| `0x000D`
a| `32` | System boot information | 1  a| `0x000E`
a| `34` | Management device | 1  a| `0x000F`
a| `35` | Management device component | 1  a| `0x0010`
a| `36` | Management device threshold data | 1  a| `0x0011`
a| `38` | IPMI device information | 1  a| `0x0012`
a| `39` | System power supply | 1  a| `0x0017`
a| `41` | Onboard devices extended information | 6  a| `0x0014`, `0x0015`, `0x0016`, `0x006F`, `0x0070`, `0x0071`
a| `127` | End of table | 1  a| `0xFEFF`
a| `148` | OEM-specific | 1  a| `0x0072`
|===
