= Cisco
:toc:
:toclevels: 1

== IDS-4235 (ids-4235.bin)

[horizontal]
File path:: `cisco/ids-4235.bin`
Product name:: IDS-4235/4250
Product version:: None
Product family:: -
Firmware vendor:: Dell Computer Corporation
Firmware version:: A04
Release date:: 2002-09-30
SMBIOS version:: 2.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0100`
a| `2` | Baseboard or module information | 1  a| `0x0200`
a| `3` | System enclosure or chassis | 1  a| `0x0300`
a| `4` | Processor information | 2  a| `0x0400`, `0x0401`
a| `7` | Cache information | 2  a| `0x0700`, `0x0701`
a| `8` | Port connector information | 11  a| `0x0800`, `0x0801`, `0x0802`, `0x0803`, `0x0804`, `0x0805`, `0x0806`, `0x0807`, `0x0808`, `0x0809`, `0x080A`
a| `9` | System slots | 2  a| `0x0901`, `0x0902`
a| `10` | Onboard devices information | 1  a| `0x0A00`
a| `11` | OEM strings | 1  a| `0x0B00`
a| `12` | System configuration options | 1  a| `0x0C00`
a| `13` | Firmware language information | 1  a| `0x0D00`
a| `16` | Physical memory array | 1  a| `0x1000`
a| `17` | Memory device | 4  a| `0x1100`, `0x1101`, `0x1102`, `0x1103`
a| `19` | Memory array mapped address | 1  a| `0x1300`
a| `20` | Memory device mapped address | 2  a| `0x1400`, `0x1401`
a| `32` | System boot information | 1  a| `0x2000`
a| `38` | IPMI device information | 1  a| `0x2600`
a| `126` | Inactive | 5  a| `0x0702`, `0x0703`, `0x0900`, `0x1402`, `0x1403`
a| `127` | End of table | 1  a| `0x7F00`
a| `208` | Dell revisions and IDs | 1  a| `0xD000`
a| `210` | Dell serial port | 1  a| `0xD200`
a| `212` | Dell indexed IO | 3  a| `0xD400`, `0xD401`, `0xD402`
a| `216` | Dell video BIOS information | 1  a| `0xD800`
a| `222` | OEM-specific | 1  a| `0xDE00`
|===
