= MSI
:toc:
:toclevels: 1

== Modern 15 A10M (modern-15-a10m.bin)

[horizontal]
File path:: `msi/modern-15-a10m.bin`
Product name:: Modern 15 A10M
Product version:: REV:1.0
Product family:: Modern
Firmware vendor:: American Megatrends Inc.
Firmware version:: E1551IMS.10C
Release date:: 2019-12-12
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0001`
a| `1` | System information | 1  a| `0x0002`
a| `2` | Baseboard or module information | 1  a| `0x0003`
a| `3` | System enclosure or chassis | 1  a| `0x0004`
a| `4` | Processor information | 1  a| `0x0048`
a| `7` | Cache information | 3  a| `0x0045`, `0x0046`, `0x0047`
a| `8` | Port connector information | 24  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `9` | System slots | 5  a| `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`
a| `10` | Onboard devices information | 1  a| `0x0022`
a| `11` | OEM strings | 1  a| `0x0000`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x004A`
a| `14` | Group associations | 2  a| `0x005B`, `0x005C`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 2  a| `0x003B`, `0x003C`
a| `19` | Memory array mapped address | 1  a| `0x003D`
a| `20` | Memory device mapped address | 2  a| `0x003E`, `0x003F`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 14  a| `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`
a| `127` | End of table | 1  a| `0x005E`
a| `131` | Intel vPro information | 1  a| `0x0049`
a| `136` | OEM-specific | 1  a| `0x005A`
a| `219` | Intel Management Engine interface information | 1  a| `0x005D`
a| `221` | Intel firmware version information | 6  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0059`
|===
== MS-171F (ms-171f.bin)

[horizontal]
File path:: `msi/ms-171f.bin`
Product name:: MS-171F
Product version:: Ver 1.000
Product family:: To Be Filled By O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: A171FIZT V1.05
Release date:: 2008-12-05
SMBIOS version:: 2.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 2  a| `0x0020`, `0x0021`
a| `10` | Onboard devices information | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `15` | System event log | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 2  a| `0x0027`, `0x0029`
a| `19` | Memory array mapped address | 1  a| `0x0026`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x002A`
a| `32` | System boot information | 1  a| `0x002B`
a| `127` | End of table | 1  a| `0x002C`
|===
== MS-7210 945GM2-FI (ms-7210.bin)

[horizontal]
File path:: `msi/ms-7210.bin`
Product name:: MS-7210
Product version:: 100
Product family:: To Be Filled By O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 080012
Release date:: 2006-07-18
SMBIOS version:: 2.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0008`
a| `6` | Memory module information | 4  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `13` | Firmware language information | 1  a| `0x000D`
a| `16` | Physical memory array | 1  a| `0x000E`
a| `17` | Memory device | 4  a| `0x0010`, `0x0012`, `0x0014`, `0x0016`
a| `19` | Memory array mapped address | 1  a| `0x000F`
a| `20` | Memory device mapped address | 4  a| `0x0011`, `0x0013`, `0x0015`, `0x0017`
a| `32` | System boot information | 1  a| `0x0018`
a| `127` | End of table | 1  a| `0x0019`
|===
== MS-7816 (ms-7816.bin)

[horizontal]
File path:: `msi/ms-7816.bin`
Product name:: MS-7816
Product version:: 1.0
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: V2.14B14
Release date:: 2018-07-13
SMBIOS version:: 2.8

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x003D`
a| `7` | Cache information | 3  a| `0x003E`, `0x003F`, `0x0040`
a| `8` | Port connector information | 22  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `9` | System slots | 7  a| `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0052`
a| `16` | Physical memory array | 1  a| `0x0041`
a| `17` | Memory device | 4  a| `0x0042`, `0x0044`, `0x0046`, `0x0048`
a| `19` | Memory array mapped address | 1  a| `0x004A`
a| `20` | Memory device mapped address | 4  a| `0x0043`, `0x0045`, `0x0047`, `0x0049`
a| `24` | Hardware security | 1  a| `0x0023`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 3  a| `0x003A`, `0x003B`, `0x003C`
a| `127` | End of table | 1  a| `0x0054`
a| `130` | Intel Active Management Technology information | 1  a| `0x004F`
a| `131` | Intel vPro information | 1  a| `0x0050`
a| `136` | OEM-specific | 1  a| `0x004E`
a| `143` | OEM-specific | 1  a| `0x0051`
|===
== Pro B650-S WiFi (pro-b650-s-wifi.bin)

[horizontal]
File path:: `msi/pro-b650-s-wifi.bin`
Product name:: MS-7E26
Product version:: 1.0
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: 1.G0
Release date:: 2024-10-09
SMBIOS version:: 3.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000D`
a| `7` | Cache information | 3  a| `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 9  a| `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`
a| `9` | System slots | 4  a| `0x0026`, `0x0027`, `0x0028`, `0x0029`
a| `11` | OEM strings | 1  a| `0x0004`
a| `12` | System configuration options | 1  a| `0x0005`
a| `16` | Physical memory array | 1  a| `0x0010`
a| `17` | Memory device | 4  a| `0x0013`, `0x0015`, `0x0018`, `0x001A`
a| `18` | 32-bit memory error information | 5  a| `0x000F`, `0x0012`, `0x0014`, `0x0017`, `0x0019`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 2  a| `0x0016`, `0x001B`
a| `32` | System boot information | 1  a| `0x0006`
a| `40` | Additional information | 1  a| `0x001C`
a| `41` | Onboard devices extended information | 1  a| `0x002A`
a| `43` | TPM device | 1  a| `0x0008`
a| `44` | Processor additional information | 2  a| `0x0007`, `0x000E`
a| `45` | Firmware inventory information | 1  a| `0x0009`
a| `127` | End of table | 1  a| `0x002C`
a| `143` | OEM-specific | 1  a| `0x002B`
|===
== Wind U-100 (wind-u100.bin)

[horizontal]
File path:: `msi/wind-u100.bin`
Product name:: U-100
Product version:: Ver.001
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: 4.6.3
Release date:: 2008-10-06
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 2  a| `0x0005`, `0x0006`
a| `8` | Port connector information | 19  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`
a| `9` | System slots | 5  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `10` | Onboard devices information | 2  a| `0x0020`, `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0024`
a| `16` | Physical memory array | 1  a| `0x0025`
a| `17` | Memory device | 2  a| `0x0027`, `0x0029`
a| `19` | Memory array mapped address | 1  a| `0x0026`
a| `20` | Memory device mapped address | 2  a| `0x0028`, `0x002A`
a| `32` | System boot information | 1  a| `0x002B`
a| `126` | Inactive | 1  a| `0x0007`
a| `127` | End of table | 1  a| `0x002C`
|===
