= Gigabyte
:toc:
:toclevels: 1

== B460 AORUS PRO AC (b460-aorus-pro-ac.bin)

[horizontal]
File path:: `gigabyte/b460-aorus-pro-ac.bin`
Product name:: B460 AORUS PRO AC
Product version:: -CF
Product family:: B460 MB
Firmware vendor:: American Megatrends Inc.
Firmware version:: F9
Release date:: 2023-12-20
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004C`
a| `7` | Cache information | 3  a| `0x0049`, `0x004A`, `0x004B`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x005D`
a| `14` | Group associations | 2  a| `0x0059`, `0x005C`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 4  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x003F`
a| `20` | Memory device mapped address | 4  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 10  a| `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`
a| `127` | End of table | 1  a| `0x005E`
a| `131` | Intel vPro information | 1  a| `0x004D`
a| `136` | OEM-specific | 1  a| `0x005B`
a| `219` | Intel Management Engine interface information | 1  a| `0x005A`
a| `221` | Intel firmware version information | 6  a| `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x0058`
|===
== B550 AORUS MASTER (b550-aorus-master.bin)

[horizontal]
File path:: `gigabyte/b550-aorus-master.bin`
Product name:: B550 AORUS MASTER
Product version:: Default string
Product family:: B550 MB
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: F18g
Release date:: 2025-03-11
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0010`
a| `7` | Cache information | 3  a| `0x000D`, `0x000E`, `0x000F`
a| `8` | Port connector information | 19  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `9` | System slots | 3  a| `0x002E`, `0x002F`, `0x0030`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x0033`
a| `16` | Physical memory array | 1  a| `0x000A`
a| `17` | Memory device | 4  a| `0x0012`, `0x0014`, `0x0017`, `0x0019`
a| `18` | 32-bit memory error information | 5  a| `0x0009`, `0x0011`, `0x0013`, `0x0016`, `0x0018`
a| `19` | Memory array mapped address | 2  a| `0x000B`, `0x000C`
a| `20` | Memory device mapped address | 2  a| `0x0015`, `0x001A`
a| `32` | System boot information | 1  a| `0x0007`
a| `41` | Onboard devices extended information | 1  a| `0x0031`
a| `44` | Processor additional information | 1  a| `0x0008`
a| `127` | End of table | 1  a| `0x0034`
|===
== B550I AORUS PRO AX (b550i-aorus-pro-ax.bin)

[horizontal]
File path:: `gigabyte/b550i-aorus-pro-ax.bin`
Product name:: B550I AORUS PRO AX
Product version:: Default string
Product family:: B550 MB
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: F20d
Release date:: 2024-09-02
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0010`
a| `7` | Cache information | 3  a| `0x000D`, `0x000E`, `0x000F`
a| `8` | Port connector information | 19  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `9` | System slots | 3  a| `0x002E`, `0x002F`, `0x0030`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x0032`
a| `16` | Physical memory array | 1  a| `0x000B`
a| `17` | Memory device | 4  a| `0x0012`, `0x0014`, `0x0017`, `0x0019`
a| `18` | 32-bit memory error information | 5  a| `0x000A`, `0x0011`, `0x0013`, `0x0016`, `0x0018`
a| `19` | Memory array mapped address | 1  a| `0x000C`
a| `20` | Memory device mapped address | 2  a| `0x0015`, `0x001A`
a| `32` | System boot information | 1  a| `0x0007`
a| `41` | Onboard devices extended information | 1  a| `0x0031`
a| `43` | TPM device | 1  a| `0x0009`
a| `44` | Processor additional information | 1  a| `0x0008`
a| `127` | End of table | 1  a| `0x0033`
|===
== B560M DS3H V2 (b560m-ds3h-v2.bin)

[horizontal]
File path:: `gigabyte/b560m-ds3h-v2.bin`
Product name:: B560M DS3H V2
Product version:: None
Product family:: B560 MB
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: F5
Release date:: 2021-12-28
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0053`
a| `7` | Cache information | 4  a| `0x004F`, `0x0050`, `0x0051`, `0x0052`
a| `8` | Port connector information | 65  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x0062`, `0x0063`, `0x0064`, `0x0065`, `0x0066`, `0x0067`, `0x0068`, `0x0069`, `0x006A`, `0x006B`, `0x006C`, `0x006D`, `0x006E`, `0x006F`, `0x0070`, `0x0071`, `0x0072`, `0x0073`, `0x0074`, `0x0075`, `0x0076`, `0x0077`, `0x0078`, `0x0079`, `0x007A`, `0x007B`, `0x007C`, `0x007D`, `0x007E`, `0x007F`, `0x0080`, `0x0081`, `0x0082`, `0x0083`, `0x0084`, `0x0085`, `0x0086`, `0x0087`, `0x0088`, `0x0089`, `0x008A`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0061`
a| `14` | Group associations | 2  a| `0x008C`, `0x008F`
a| `16` | Physical memory array | 1  a| `0x003C`
a| `17` | Memory device | 4  a| `0x0042`, `0x0043`, `0x0044`, `0x0045`
a| `19` | Memory array mapped address | 1  a| `0x0041`
a| `20` | Memory device mapped address | 4  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 2  a| `0x0024`, `0x0060`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 10  a| `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`
a| `43` | TPM device | 1  a| `0x003B`
a| `44` | Processor additional information | 1  a| `0x003A`
a| `127` | End of table | 1  a| `0x0090`
a| `131` | Intel vPro information | 1  a| `0x0054`
a| `136` | OEM-specific | 2  a| `0x008B`, `0x008E`
a| `219` | Intel Management Engine interface information | 1  a| `0x008D`
a| `221` | Intel firmware version information | 6  a| `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x005F`
|===
== B760M DS3H GEN5 (b760m-ds3h-gen5.bin)

[horizontal]
File path:: `gigabyte/b760m-ds3h-gen5.bin`
Product name:: B760M DS3H GEN5
Product version:: -CF
Product family:: B760 MB
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: F4
Release date:: 2025-06-19
SMBIOS version:: 3.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0050`
a| `7` | Cache information | 8  a| `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0065`
a| `14` | Group associations | 2  a| `0x0066`, `0x0069`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 4  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `19` | Memory array mapped address | 1  a| `0x0040`
a| `20` | Memory device mapped address | 2  a| `0x0041`, `0x0042`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 16  a| `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`
a| `44` | Processor additional information | 1  a| `0x003A`
a| `127` | End of table | 1  a| `0x006A`
a| `131` | Intel vPro information | 1  a| `0x0051`
a| `133` | OEM-specific | 1  a| `0x0063`
a| `136` | OEM-specific | 2  a| `0x0064`, `0x0068`
a| `219` | Intel Management Engine interface information | 1  a| `0x0067`
a| `221` | Intel firmware version information | 6  a| `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0062`
|===
== G5 MF (g5-mf.bin)

[horizontal]
File path:: `gigabyte/g5-mf.bin`
Product name:: G5 MF
Product version:: Not Applicable
Product family:: GIGABYTE
Firmware vendor:: INSYDE Corp.
Firmware version:: FB10
Release date:: 2023-08-04
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `8` | Port connector information | 10  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`
a| `9` | System slots | 3  a| `0x0017`, `0x0018`, `0x0019`
a| `10` | Onboard devices information | 1  a| `0x001A`
a| `11` | OEM strings | 1  a| `0x001B`
a| `12` | System configuration options | 1  a| `0x001C`
a| `13` | Firmware language information | 1  a| `0x001D`
a| `14` | Group associations | 2  a| `0x001E`, `0x0034`
a| `15` | System event log | 1  a| `0x001F`
a| `16` | Physical memory array | 1  a| `0x0020`
a| `17` | Memory device | 2  a| `0x0021`, `0x0022`
a| `19` | Memory array mapped address | 1  a| `0x0023`
a| `20` | Memory device mapped address | 2  a| `0x0024`, `0x0025`
a| `32` | System boot information | 1  a| `0x0026`
a| `43` | TPM device | 1  a| `0x0027`
a| `127` | End of table | 1  a| `0xFEFF`
a| `128` | OEM-specific | 1  a| `0x0028`
a| `129` | OEM-specific | 1  a| `0x0029`
a| `131` | Intel vPro information | 1  a| `0x002A`
a| `136` | OEM-specific | 1  a| `0x002B`
a| `219` | Intel Management Engine interface information | 1  a| `0x002C`
a| `221` | Intel firmware version information | 7  a| `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`
|===
== GA-970A DS3P (ga-970a-ds3p.bin)

[horizontal]
File path:: `gigabyte/ga-970a-ds3p.bin`
Product name:: To be filled by O.E.M.
Product version:: To be filled by O.E.M.
Product family:: To be filled by O.E.M.
Firmware vendor:: American Megatrends Inc.
Firmware version:: FD
Release date:: 2016-02-26
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0008`
a| `6` | Memory module information | 4  a| `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `8` | Port connector information | 24  a| `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`
a| `9` | System slots | 4  a| `0x0025`, `0x0026`, `0x0027`, `0x0028`
a| `10` | Onboard devices information | 1  a| `0x0029`
a| `11` | OEM strings | 1  a| `0x002A`
a| `12` | System configuration options | 1  a| `0x002B`
a| `13` | Firmware language information | 1  a| `0x0038`
a| `16` | Physical memory array | 1  a| `0x002C`
a| `17` | Memory device | 4  a| `0x002E`, `0x0030`, `0x0032`, `0x0034`
a| `19` | Memory array mapped address | 1  a| `0x002D`
a| `20` | Memory device mapped address | 4  a| `0x002F`, `0x0031`, `0x0033`, `0x0035`
a| `32` | System boot information | 1  a| `0x0036`
a| `41` | Onboard devices extended information | 1  a| `0x0037`
a| `127` | End of table | 1  a| `0x003D`
|===
== GA-MA74GMT-S2 (ga-ma74gmt-s2.bin)

[horizontal]
File path:: `gigabyte/ga-ma74gmt-s2.bin`
Product name:: GA-MA74GMT-S2
Product version:: 
Product family:: 
Firmware vendor:: Award Software International, Inc.
Firmware version:: F8
Release date:: 2010-08-03
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `7` | Cache information | 4  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 17  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`
a| `9` | System slots | 4  a| `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `13` | Firmware language information | 1  a| `0x0023`
a| `16` | Physical memory array | 1  a| `0x0024`
a| `17` | Memory device | 4  a| `0x0025`, `0x0026`, `0x0027`, `0x0028`
a| `19` | Memory array mapped address | 1  a| `0x0029`
a| `20` | Memory device mapped address | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `32` | System boot information | 1  a| `0x002E`
a| `127` | End of table | 1  a| `0x0035`
a| `188` | OEM-specific | 1  a| `0x002F`
a| `190` | OEM-specific | 1  a| `0x0030`
a| `192` | OEM-specific | 1  a| `0x0031`
a| `194` | OEM-specific | 1  a| `0x0032`
a| `196` | OEM-specific | 1  a| `0x0033`
a| `198` | OEM-specific | 1  a| `0x0034`
|===
== GA-MA78GM-S2H (ga-ma78gm-s2h.bin)

[horizontal]
File path:: `gigabyte/ga-ma78gm-s2h.bin`
Product name:: GA-MA78GM-S2H
Product version:: 
Product family:: 
Firmware vendor:: Award Software International, Inc.
Firmware version:: F5
Release date:: 2008-06-18
SMBIOS version:: 2.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `7` | Cache information | 4  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 18  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 8  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`, `0x0026`, `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `16` | Physical memory array | 1  a| `0x0029`
a| `17` | Memory device | 4  a| `0x002A`, `0x002B`, `0x002C`, `0x002D`
a| `19` | Memory array mapped address | 1  a| `0x002E`
a| `20` | Memory device mapped address | 4  a| `0x002F`, `0x0030`, `0x0031`, `0x0032`
a| `32` | System boot information | 1  a| `0x0033`
a| `127` | End of table | 1  a| `0x0038`
a| `188` | OEM-specific | 1  a| `0x0034`
a| `190` | OEM-specific | 1  a| `0x0035`
a| `192` | OEM-specific | 1  a| `0x0036`
a| `194` | OEM-specific | 1  a| `0x0037`
|===
== H610M H V2 DDR4 (h610m-h-v2-ddr4.bin)

[horizontal]
File path:: `gigabyte/h610m-h-v2-ddr4.bin`
Product name:: H610M H V2 DDR4
Product version:: -CF
Product family:: H610 MB
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: F28
Release date:: 2023-10-16
SMBIOS version:: 3.6

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004E`
a| `7` | Cache information | 8  a| `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x0063`
a| `14` | Group associations | 2  a| `0x0065`, `0x0068`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 2  a| `0x003C`, `0x003D`
a| `19` | Memory array mapped address | 1  a| `0x003E`
a| `20` | Memory device mapped address | 2  a| `0x003F`, `0x0040`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 16  a| `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`, `0x005A`, `0x005B`, `0x005C`, `0x005D`, `0x005E`, `0x005F`
a| `44` | Processor additional information | 1  a| `0x003A`
a| `127` | End of table | 1  a| `0x0069`
a| `131` | Intel vPro information | 1  a| `0x004F`
a| `133` | OEM-specific | 1  a| `0x0061`
a| `136` | OEM-specific | 2  a| `0x0062`, `0x0067`
a| `219` | Intel Management Engine interface information | 1  a| `0x0066`
a| `221` | Intel firmware version information | 6  a| `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0060`
|===
== J4005N D2P-CF (j4005n-d2p-cf.bin)

[horizontal]
File path:: `gigabyte/j4005n-d2p-cf.bin`
Product name:: Default string
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: F3
Release date:: 2018-02-13
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x002F`
a| `7` | Cache information | 2  a| `0x002D`, `0x002E`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 2  a| `0x003C`, `0x003D`
a| `10` | Onboard devices information | 1  a| `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x003B`
a| `16` | Physical memory array | 1  a| `0x0023`
a| `17` | Memory device | 2  a| `0x0025`, `0x0027`
a| `19` | Memory array mapped address | 1  a| `0x0024`
a| `20` | Memory device mapped address | 1  a| `0x0028`
a| `32` | System boot information | 1  a| `0x0029`
a| `41` | Onboard devices extended information | 11  a| `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`
a| `127` | End of table | 1  a| `0x003E`
|===
== nForce (nforce.bin)

[horizontal]
File path:: `gigabyte/nforce.bin`
Product name:: 
Product version:: 
Product family:: -
Firmware vendor:: Award Software International, Inc.
Firmware version:: F7
Release date:: 2008-10-23
SMBIOS version:: 2.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x0004`, `0x0005`
a| `5` | Memory controller information | 1  a| `0x0006`
a| `6` | Memory module information | 4  a| `0x0007`, `0x0008`, `0x0009`, `0x000A`
a| `7` | Cache information | 4  a| `0x000B`, `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 9  a| `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`
a| `9` | System slots | 6  a| `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `13` | Firmware language information | 1  a| `0x001E`
a| `16` | Physical memory array | 1  a| `0x001F`
a| `17` | Memory device | 4  a| `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `19` | Memory array mapped address | 1  a| `0x0024`
a| `20` | Memory device mapped address | 4  a| `0x0025`, `0x0026`, `0x0027`, `0x0028`
a| `32` | System boot information | 1  a| `0x0029`
a| `127` | End of table | 1  a| `0x002A`
|===
== Noname server (F15) (noname-server-f15.bin)

[horizontal]
File path:: `gigabyte/noname-server-f15.bin`
Product name:: To be filled by O.E.M.
Product version:: To be filled by O.E.M.
Product family:: Server
Firmware vendor:: GIGABYTE
Firmware version:: F15
Release date:: 2022-06-06
SMBIOS version:: 3.3

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 2  a| `0x002D`, `0x002E`
a| `7` | Cache information | 3  a| `0x002A`, `0x002B`, `0x002C`
a| `8` | Port connector information | 19  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`
a| `10` | Onboard devices information | 1  a| `0x0017`
a| `13` | Firmware language information | 1  a| `0x0056`
a| `16` | Physical memory array | 1  a| `0x0032`
a| `17` | Memory device | 32  a| `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`
a| `19` | Memory array mapped address | 2  a| `0x0053`, `0x0054`
a| `38` | IPMI device information | 1  a| `0x001B`
a| `41` | Onboard devices extended information | 3  a| `0x0018`, `0x0019`, `0x001A`
a| `42` | Management controller host interface | 1  a| `0x001C`
a| `127` | End of table | 1  a| `0x006F`
a| `128` | OEM-specific | 1  a| `0x0057`
a| `129` | OEM-specific | 14  a| `0x005C`, `0x005D`, `0x005E`, `0x005F`, `0x0060`, `0x0061`, `0x0062`, `0x0063`, `0x0064`, `0x0065`, `0x0066`, `0x0067`, `0x0068`, `0x0069`
a| `130` | OEM-specific | 4  a| `0x0058`, `0x0059`, `0x005A`, `0x005B`
a| `131` | OEM-specific | 2  a| `0x006A`, `0x006B`
a| `132` | OEM-specific | 2  a| `0x006C`, `0x006D`
a| `133` | OEM-specific | 1  a| `0x006E`
|===
== X399 AORUS XTREME (x399-aorus-xtreme.bin)

[horizontal]
File path:: `gigabyte/x399-aorus-xtreme.bin`
Product name:: X399 AORUS XTREME
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: F4
Release date:: 2018-10-04
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000F`
a| `7` | Cache information | 3  a| `0x000C`, `0x000D`, `0x000E`
a| `8` | Port connector information | 24  a| `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`, `0x002E`, `0x002F`, `0x0030`, `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`
a| `9` | System slots | 10  a| `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `16` | Physical memory array | 1  a| `0x0009`
a| `17` | Memory device | 8  a| `0x0011`, `0x0014`, `0x0017`, `0x001A`, `0x001D`, `0x0020`, `0x0023`, `0x0026`
a| `18` | 32-bit memory error information | 9  a| `0x0008`, `0x0010`, `0x0013`, `0x0016`, `0x0019`, `0x001C`, `0x001F`, `0x0022`, `0x0025`
a| `19` | Memory array mapped address | 2  a| `0x000A`, `0x000B`
a| `20` | Memory device mapped address | 8  a| `0x0012`, `0x0015`, `0x0018`, `0x001B`, `0x001E`, `0x0021`, `0x0024`, `0x0027`
a| `32` | System boot information | 1  a| `0x0007`
a| `41` | Onboard devices extended information | 6  a| `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`
a| `127` | End of table | 1  a| `0x0051`
|===
== Z390 M GAMING (z390-m-gaming.bin)

[horizontal]
File path:: `gigabyte/z390-m-gaming.bin`
Product name:: Z390 M GAMING
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: F11a
Release date:: 2025-06-12
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0047`
a| `7` | Cache information | 3  a| `0x0044`, `0x0045`, `0x0046`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x004B`
a| `14` | Group associations | 2  a| `0x005A`, `0x005B`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 4  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x003F`
a| `20` | Memory device mapped address | 2  a| `0x0048`, `0x0049`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 12  a| `0x004C`, `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`
a| `127` | End of table | 1  a| `0x005D`
a| `131` | Intel vPro information | 1  a| `0x004A`
a| `136` | OEM-specific | 1  a| `0x0059`
a| `219` | Intel Management Engine interface information | 1  a| `0x005C`
a| `221` | Intel firmware version information | 5  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0058`
|===
== Z490 VISION G (z490-vision-g.bin)

[horizontal]
File path:: `gigabyte/z490-vision-g.bin`
Product name:: Z490 VISION G
Product version:: -CF
Product family:: Z490 MB
Firmware vendor:: American Megatrends Inc.
Firmware version:: F23
Release date:: 2023-12-20
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004B`
a| `7` | Cache information | 3  a| `0x0048`, `0x0049`, `0x004A`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x005C`
a| `14` | Group associations | 2  a| `0x0058`, `0x005B`
a| `16` | Physical memory array | 1  a| `0x003B`
a| `17` | Memory device | 4  a| `0x003C`, `0x003D`, `0x003E`, `0x003F`
a| `19` | Memory array mapped address | 1  a| `0x0040`
a| `20` | Memory device mapped address | 2  a| `0x0041`, `0x0042`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 10  a| `0x004D`, `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`
a| `43` | TPM device | 1  a| `0x003A`
a| `127` | End of table | 1  a| `0x005D`
a| `131` | Intel vPro information | 1  a| `0x004C`
a| `136` | OEM-specific | 1  a| `0x005A`
a| `219` | Intel Management Engine interface information | 1  a| `0x0059`
a| `221` | Intel firmware version information | 6  a| `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0057`
|===
== Z490M GAMING X (z490m-gaming-x.bin)

[horizontal]
File path:: `gigabyte/z490m-gaming-x.bin`
Product name:: Z490M GAMING X
Product version:: -CF
Product family:: Z490 MB
Firmware vendor:: American Megatrends Inc.
Firmware version:: F22
Release date:: 2023-06-07
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x004C`
a| `7` | Cache information | 3  a| `0x0049`, `0x004A`, `0x004B`
a| `8` | Port connector information | 24  a| `0x0004`, `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 5  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`
a| `10` | Onboard devices information | 1  a| `0x0021`
a| `11` | OEM strings | 1  a| `0x0022`
a| `12` | System configuration options | 1  a| `0x0023`
a| `13` | Firmware language information | 1  a| `0x005F`
a| `14` | Group associations | 2  a| `0x005B`, `0x005E`
a| `16` | Physical memory array | 1  a| `0x003A`
a| `17` | Memory device | 4  a| `0x003B`, `0x003C`, `0x003D`, `0x003E`
a| `19` | Memory array mapped address | 1  a| `0x003F`
a| `20` | Memory device mapped address | 4  a| `0x0040`, `0x0041`, `0x0042`, `0x0043`
a| `26` | Voltage probe | 2  a| `0x0026`, `0x0035`
a| `27` | Cooling device | 3  a| `0x002C`, `0x002F`, `0x0037`
a| `28` | Temperature probe | 2  a| `0x0029`, `0x0036`
a| `29` | Electrical current probe | 2  a| `0x0032`, `0x0038`
a| `32` | System boot information | 1  a| `0x0024`
a| `34` | Management device | 1  a| `0x0025`
a| `35` | Management device component | 5  a| `0x0028`, `0x002B`, `0x002E`, `0x0031`, `0x0034`
a| `36` | Management device threshold data | 5  a| `0x0027`, `0x002A`, `0x002D`, `0x0030`, `0x0033`
a| `39` | System power supply | 1  a| `0x0039`
a| `41` | Onboard devices extended information | 12  a| `0x004E`, `0x004F`, `0x0050`, `0x0051`, `0x0052`, `0x0053`, `0x0054`, `0x0055`, `0x0056`, `0x0057`, `0x0058`, `0x0059`
a| `127` | End of table | 1  a| `0x0060`
a| `131` | Intel vPro information | 1  a| `0x004D`
a| `136` | OEM-specific | 1  a| `0x005D`
a| `219` | Intel Management Engine interface information | 1  a| `0x005C`
a| `221` | Intel firmware version information | 6  a| `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x005A`
|===
