= Toshiba
:toc:
:toclevels: 1

== Satellite C850-C1K (satellite-c850-c1k.bin)

[horizontal]
File path:: `toshiba/satellite-c850-c1k.bin`
Product name:: Satellite C850-C1K
Product version:: PSKC8R-07T016RU
Product family:: Type1Family
Firmware vendor:: Insyde Corp.
Firmware version:: 1.40
Release date:: 2012-04-24
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 2  a| `0x0006`, `0x0007`
a| `7` | Cache information | 4  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`
a| `8` | Port connector information | 16  a| `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`
a| `9` | System slots | 8  a| `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `11` | OEM strings | 1  a| `0x0024`
a| `12` | System configuration options | 1  a| `0x0025`
a| `13` | Firmware language information | 1  a| `0x0026`
a| `15` | System event log | 1  a| `0x0027`
a| `16` | Physical memory array | 1  a| `0x0028`
a| `17` | Memory device | 2  a| `0x0029`, `0x002A`
a| `18` | 32-bit memory error information | 3  a| `0x002B`, `0x002C`, `0x002D`
a| `19` | Memory array mapped address | 1  a| `0x002E`
a| `20` | Memory device mapped address | 2  a| `0x002F`, `0x0030`
a| `21` | Built-in pointing device | 1  a| `0x0031`
a| `22` | Portable battery | 1  a| `0x0032`
a| `26` | Voltage probe | 1  a| `0x0033`
a| `27` | Cooling device | 1  a| `0x0034`
a| `32` | System boot information | 1  a| `0x0035`
a| `39` | System power supply | 1  a| `0x0036`
a| `40` | Additional information | 1  a| `0x0037`
a| `41` | Onboard devices extended information | 1  a| `0x0038`
a| `127` | End of table | 1  a| `0x003D`
a| `128` | OEM-specific | 1  a| `0x0039`
a| `129` | OEM-specific | 1  a| `0x003A`
a| `130` | Intel Active Management Technology information | 1  a| `0x003B`
a| `136` | OEM-specific | 1  a| `0x003C`
|===
== Satellite Pro L70-A (satellite-pro-l70-a.bin)

[horizontal]
File path:: `toshiba/satellite-pro-l70-a.bin`
Product name:: SATELLITE PRO L70-A
Product version:: PSKNFE-00300FCE
Product family:: Type1Family
Firmware vendor:: Insyde Corp.
Firmware version:: 1.60
Release date:: 2014-04-18
SMBIOS version:: 2.7

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `5` | Memory controller information | 1  a| `0x0005`
a| `6` | Memory module information | 4  a| `0x0006`, `0x0007`, `0x0008`, `0x0009`
a| `7` | Cache information | 4  a| `0x000A`, `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 16  a| `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`
a| `9` | System slots | 8  a| `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`, `0x0024`, `0x0025`
a| `11` | OEM strings | 1  a| `0x0026`
a| `12` | System configuration options | 1  a| `0x0027`
a| `13` | Firmware language information | 1  a| `0x0028`
a| `15` | System event log | 1  a| `0x0029`
a| `16` | Physical memory array | 1  a| `0x002A`
a| `17` | Memory device | 4  a| `0x002B`, `0x002C`, `0x002D`, `0x002E`
a| `18` | 32-bit memory error information | 3  a| `0x002F`, `0x0030`, `0x0031`
a| `19` | Memory array mapped address | 1  a| `0x0032`
a| `20` | Memory device mapped address | 2  a| `0x0033`, `0x0034`
a| `21` | Built-in pointing device | 1  a| `0x0035`
a| `22` | Portable battery | 1  a| `0x0036`
a| `24` | Hardware security | 1  a| `0x0037`
a| `26` | Voltage probe | 1  a| `0x0038`
a| `27` | Cooling device | 1  a| `0x0039`
a| `32` | System boot information | 1  a| `0x003A`
a| `39` | System power supply | 1  a| `0x003B`
a| `40` | Additional information | 1  a| `0x003C`
a| `41` | Onboard devices extended information | 1  a| `0x003D`
a| `127` | End of table | 1  a| `0x0044`
a| `128` | OEM-specific | 1  a| `0x003E`
a| `129` | OEM-specific | 1  a| `0x003F`
a| `130` | Intel Active Management Technology information | 1  a| `0x0040`
a| `131` | Intel vPro information | 1  a| `0x0041`
a| `136` | OEM-specific | 1  a| `0x0042`
a| `221` | Intel firmware version information | 1  a| `0x0043`
|===
