= Huawei
:toc:
:toclevels: 1

== MateBook 16s 2023 CREFG-X (matebook-16s-2023-crefg-x.bin)

[horizontal]
File path:: `huawei/matebook-16s-2023-crefg-x.bin`
Product name:: CREFG-XX
Product version:: M1010
Product family:: MateBook
Firmware vendor:: HUAWEI
Firmware version:: 1.09
Release date:: 2024-09-10
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `9` | System slots | 1  a| `0x000D`
a| `11` | OEM strings | 1  a| `0x000E`
a| `13` | Firmware language information | 1  a| `0x000F`
a| `14` | Group associations | 2  a| `0x0010`, `0x002E`
a| `16` | Physical memory array | 1  a| `0x0011`
a| `17` | Memory device | 8  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `19` | Memory array mapped address | 1  a| `0x001A`
a| `20` | Memory device mapped address | 8  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `21` | Built-in pointing device | 1  a| `0x0023`
a| `22` | Portable battery | 1  a| `0x0024`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0025`
a| `136` | OEM-specific | 1  a| `0x0026`
a| `219` | Intel Management Engine interface information | 1  a| `0x0027`
a| `221` | Intel firmware version information | 6  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`
|===
== MateBook D 14 2023 MDF-X (matebook-d14-2023-mdf-x.bin)

[horizontal]
File path:: `huawei/matebook-d14-2023-mdf-x.bin`
Product name:: MDF-XX
Product version:: M1010
Product family:: MateBook D
Firmware vendor:: HUAWEI
Firmware version:: 1.26
Release date:: 2025-03-26
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`
a| `9` | System slots | 1  a| `0x000D`
a| `11` | OEM strings | 1  a| `0x000E`
a| `13` | Firmware language information | 1  a| `0x000F`
a| `14` | Group associations | 2  a| `0x0010`, `0x002E`
a| `16` | Physical memory array | 1  a| `0x0011`
a| `17` | Memory device | 8  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `19` | Memory array mapped address | 1  a| `0x001A`
a| `20` | Memory device mapped address | 8  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `21` | Built-in pointing device | 1  a| `0x0023`
a| `22` | Portable battery | 1  a| `0x0024`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0025`
a| `136` | OEM-specific | 1  a| `0x0026`
a| `219` | Intel Management Engine interface information | 1  a| `0x0027`
a| `221` | Intel firmware version information | 6  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`
|===
== MateBook D 14 2024 MDG-X (matebook-d14-2024-mdg-x.bin)

[horizontal]
File path:: `huawei/matebook-d14-2024-mdg-x.bin`
Product name:: MDG-XX
Product version:: M1010
Product family:: MateBook D
Firmware vendor:: HUAWEI
Firmware version:: 1.25
Release date:: 2024-08-22
SMBIOS version:: 3.4

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 8  a| `0x0005`, `0x0006`, `0x0007`, `0x0008`, `0x0009`, `0x000D`, `0x000B`, `0x000C`
a| `9` | System slots | 1  a| `0x000D`
a| `11` | OEM strings | 1  a| `0x000E`
a| `13` | Firmware language information | 1  a| `0x000F`
a| `14` | Group associations | 2  a| `0x0010`, `0x002E`
a| `16` | Physical memory array | 1  a| `0x0011`
a| `17` | Memory device | 8  a| `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`
a| `19` | Memory array mapped address | 1  a| `0x001A`
a| `20` | Memory device mapped address | 8  a| `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`
a| `21` | Built-in pointing device | 1  a| `0x0023`
a| `22` | Portable battery | 1  a| `0x0024`
a| `127` | End of table | 1  a| `0xFEFF`
a| `131` | Intel vPro information | 1  a| `0x0025`
a| `136` | OEM-specific | 1  a| `0x0026`
a| `219` | Intel Management Engine interface information | 1  a| `0x0027`
a| `221` | Intel firmware version information | 6  a| `0x0028`, `0x0029`, `0x002A`, `0x002B`, `0x002C`, `0x002D`
|===
== NBLB-WAX9N (nblb-wax9n.bin)

[horizontal]
File path:: `huawei/nblb-wax9n.bin`
Product name:: NBLB-WAX9N
Product version:: M1160
Product family:: MateBook D
Firmware vendor:: HUAWEI
Firmware version:: 1.35
Release date:: 2021-06-23
SMBIOS version:: 3.2

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0004`
a| `7` | Cache information | 3  a| `0x0005`, `0x0006`, `0x0007`
a| `9` | System slots | 2  a| `0x0008`, `0x0009`
a| `11` | OEM strings | 1  a| `0x000A`
a| `13` | Firmware language information | 1  a| `0x000B`
a| `14` | Group associations | 2  a| `0x000C`, `0x000D`
a| `16` | Physical memory array | 1  a| `0x000E`
a| `17` | Memory device | 2  a| `0x000F`, `0x0010`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 2  a| `0x0012`, `0x0013`
a| `21` | Built-in pointing device | 1  a| `0x0014`
a| `22` | Portable battery | 1  a| `0x0015`
a| `43` | TPM device | 1  a| `0x0016`
a| `127` | End of table | 1  a| `0xFEFF`
a| `219` | Intel Management Engine interface information | 1  a| `0x0017`
a| `221` | Intel firmware version information | 5  a| `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`
a| `222` | Intel Silicon View Technology milestones | 1  a| `0x001D`
|===
