= dmi_file_unlock(3)
The OpenDMI contributors
OpenDMI 0.5.0

:doctype: manpage
:release-version: 0.5.0
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

== Name

dmi_file_unlock - release an advisory lock on a region of a file.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)

== Synopsis

[source, c]
----
#include <opendmi/utils/file.h>

bool dmi_file_unlock(int fd, off_t size);
----

== Description

The `dmi_file_unlock` function unlocks `size` bytes of the file starting at
the current offset using `lockf(F_ULOCK)`. It retries automatically if
interrupted by a signal (`EINTR`).

Passing `size` of `0` unlocks from the current offset to the end of the file.

=== Parameters

`fd`::
Open file descriptor.

`size`::
Number of bytes to unlock, or `0` to unlock to end of file.

== Return value

Returns `true` if the lock was released, `false` on error.

== See also

`dmi_file_lock`(3),
`lockf`(3)

== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
