ifdef::backend-manpage[]
= dmi_boot_option(3)
endif::[]
ifndef::backend-manpage[]
= dmi_boot_option
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_boot_option, dmi_boot_option_name - system reset boot options

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/system-reset.h>

typedef enum dmi_boot_option {
    DMI_BOOT_OPTION_RESERVED         = 0x00,
    DMI_BOOT_OPTION_OPERATING_SYSTEM = 0x01,
    DMI_BOOT_OPTION_SYSTEM_UTILS     = 0x02,
    DMI_BOOT_OPTION_AVOID_REBOOT     = 0x03,
} dmi_boot_option_t;

const char *dmi_boot_option_name(dmi_boot_option_t value);
----

== Description

The `dmi_boot_option_t` enumeration tells what a system does after an
automatic system reset. It is the type of the `boot_on_watchdog` and
`boot_on_limit` fields of `dmi_system_reset_t`.

The `dmi_boot_option_name` function returns the printable name of a value, as
the command line tool shows it. The name is translated to the locale set with
`dmi_set_locale`, when the library is built with ICU4C support and has a
translation of it.

=== Values

`DMI_BOOT_OPTION_RESERVED`::
Reserved by the specification, and not to be used.

`DMI_BOOT_OPTION_OPERATING_SYSTEM`::
Boot the operating system.

`DMI_BOOT_OPTION_SYSTEM_UTILS`::
Boot the system utilities.

`DMI_BOOT_OPTION_AVOID_REBOOT`::
Do not reboot.

== Return value

`dmi_boot_option_name` returns the name of the value, or `nullptr` if the
value has no name. The name is a static string, which must not be modified or
freed.

== Errors

None.

== See also

`dmi_system_reset`(3)

== Standards

DMTF SMBIOS Specification (DSP0134), version 2.2 or newer.

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
