ifdef::backend-manpage[]
= dmi_encoder_tell(3)
endif::[]
ifndef::backend-manpage[]
= dmi_encoder_tell
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_encoder_tell - get the current position of an encoder.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/encoder.h>

size_t dmi_encoder_tell(const dmi_encoder_t *encoder);
----

== Description

The `dmi_encoder_tell` function returns the position of the next byte to
write, counted from the beginning of the structure the way the specification
counts it, so that it is the offset the field written next takes.

=== Parameters

`encoder`::
Encoder to query.

== Return value

Position of the next byte to write.

== Errors

None.

== See also

`dmi_encoder_put_bytes_at`(3),
`dmi_writer_tell`(3),
`dmi_reader_tell`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
