ifdef::backend-manpage[]
= dmi_error_clear(3)
endif::[]
ifndef::backend-manpage[]
= dmi_error_clear
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_error_clear - remove all error descriptors from the error queue.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/error.h>

void dmi_error_clear(dmi_context_t *context);
----

== Description

The `dmi_error_clear` function removes all error descriptors from the error
queue of `context`, freeing any associated message strings. After the call the
queue is empty. If `context` is `nullptr`, the function does nothing.

=== Parameters

`context`::
DMI context.

== Errors

None.

== See also

`dmi_error_get_first`(3),
`dmi_error_get_last`(3),
`dmi_error_raise`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
