ifdef::backend-manpage[]
= dmi_decoder_remaining(3)
endif::[]
ifndef::backend-manpage[]
= dmi_decoder_remaining
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_decoder_remaining - get the number of the bytes of a structure left to read.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/decoder.h>

size_t dmi_decoder_remaining(const dmi_decoder_t *decoder);
----

== Description

The `dmi_decoder_remaining` function returns the number of the bytes from
the current position to the end of the body of the structure, which is how a
decoder tells how many records of a repeating group the data carries.

=== Parameters

`decoder`::
Decoder to query.

== Return value

Number of the bytes, or zero if `decoder` is `nullptr`.

== Errors

None.

== See also

`dmi_decoder_skip`(3),
`dmi_reader_remaining`(3),
`dmi_reader_has`(3),
`dmi_decoder_incomplete`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
