= dmi_decoder_stop(3)
The OpenDMI contributors
OpenDMI 0.5.0

:doctype: manpage
:release-version: 0.5.0
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

== Name

dmi_decoder_stop - stop decoding at the end of the data of a structure.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)

== Synopsis

[source, c]
----
#include <opendmi/decoder.h>

bool dmi_decoder_stop(dmi_decoder_t *decoder);
----

== Description

The `dmi_decoder_stop` function marks the structure with
`DMI_ENTITY_STATE_PARTIAL`.

It is intended for the decoders of the structures which newer versions of
the specification have extended, and is called once the data has been read
to its end while the decoder knows of more fields.

The data is required to be exhausted. A structure which ends anywhere else
is incomplete instead, see `dmi_decoder_incomplete`(3).

=== Parameters

`decoder`::
Decoder of the structure.

== Return value

Always `true`, so that it can be returned by the decoder.

== See also

`dmi_decoder_incomplete`(3),
`dmi_decoder_remaining`(3),
`dmi_reader_has`(3),
`dmi_entity_decode`(3)

== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
