ifdef::backend-manpage[]
= dmi_apple_processor_class(3)
endif::[]
ifndef::backend-manpage[]
= dmi_apple_processor_class
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_apple_processor_class, dmi_apple_processor_class_name - Classes of processors of Apple processor types

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/apple/processor-type.h>

typedef enum dmi_apple_processor_class {
    DMI_APPLE_PROCESSOR_CLASS_UNKNOWN      = 0x00,
    DMI_APPLE_PROCESSOR_CLASS_CORE         = 0x02,
    DMI_APPLE_PROCESSOR_CLASS_CORE_2       = 0x03,
    DMI_APPLE_PROCESSOR_CLASS_XEON_PENRYN  = 0x04,
    DMI_APPLE_PROCESSOR_CLASS_XEON_NEHALEM = 0x05,
    DMI_APPLE_PROCESSOR_CLASS_CORE_I5      = 0x06,
    DMI_APPLE_PROCESSOR_CLASS_CORE_I7      = 0x07,
    DMI_APPLE_PROCESSOR_CLASS_CORE_I3      = 0x09,
    DMI_APPLE_PROCESSOR_CLASS_XEON_E5      = 0x0A,
    DMI_APPLE_PROCESSOR_CLASS_CORE_M       = 0x0B,
    DMI_APPLE_PROCESSOR_CLASS_CORE_M3      = 0x0C,
    DMI_APPLE_PROCESSOR_CLASS_CORE_M5      = 0x0D,
    DMI_APPLE_PROCESSOR_CLASS_CORE_M7      = 0x0E,
    DMI_APPLE_PROCESSOR_CLASS_XEON_W       = 0x0F,
    DMI_APPLE_PROCESSOR_CLASS_CORE_I9      = 0x10
} dmi_apple_processor_class_t;

const char *dmi_apple_processor_class_name(dmi_apple_processor_class_t value);
----

== Description

The `dmi_apple_processor_class_t` enumeration tells the class of a processor,
the major type of an Apple processor type, and is the type of the
`clazz` field of `dmi_apple_processor_type_t`. Other values may be
found in the data, and are kept as they are.

The `dmi_apple_processor_class_name` function returns the name of a value, as the command line
tool shows it.

=== Values

`DMI_APPLE_PROCESSOR_CLASS_UNKNOWN`::
Unknown.

`DMI_APPLE_PROCESSOR_CLASS_CORE`::
Intel Core.

`DMI_APPLE_PROCESSOR_CLASS_CORE_2`::
Intel Core 2.

`DMI_APPLE_PROCESSOR_CLASS_XEON_PENRYN`::
Intel Xeon of the Penryn microarchitecture.

`DMI_APPLE_PROCESSOR_CLASS_XEON_NEHALEM`::
Intel Xeon of the Nehalem microarchitecture.

`DMI_APPLE_PROCESSOR_CLASS_CORE_I5`::
Intel Core i5.

`DMI_APPLE_PROCESSOR_CLASS_CORE_I7`::
Intel Core i7.

`DMI_APPLE_PROCESSOR_CLASS_CORE_I3`::
Intel Core i3.

`DMI_APPLE_PROCESSOR_CLASS_XEON_E5`::
Intel Xeon E5.

`DMI_APPLE_PROCESSOR_CLASS_CORE_M`::
Intel Core M.

`DMI_APPLE_PROCESSOR_CLASS_CORE_M3`::
Intel Core m3.

`DMI_APPLE_PROCESSOR_CLASS_CORE_M5`::
Intel Core m5.

`DMI_APPLE_PROCESSOR_CLASS_CORE_M7`::
Intel Core m7.

`DMI_APPLE_PROCESSOR_CLASS_XEON_W`::
Intel Xeon W.

`DMI_APPLE_PROCESSOR_CLASS_CORE_I9`::
Intel Core i9.

== Return value

`dmi_apple_processor_class_name` returns the name of the value, translated to the language of the
current locale when a translation is available, or `nullptr` if the value
has no name. The returned string must not be modified or freed.

== Errors

None.

== See also

`dmi_apple_processor_type`(3)

== Standards

Not part of the SMBIOS specification. Defined by the firmware of Macs, and
laid out as the `AppleSmBios.h` header of OpenCore describes it.

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
