ifdef::backend-manpage[]
= dmi_file_tell(3)
endif::[]
ifndef::backend-manpage[]
= dmi_file_tell
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_file_tell - return the current file offset.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/utils/file.h>

off_t dmi_file_tell(int fd);
----

== Description

The `dmi_file_tell` function returns the current file offset for an open file
descriptor. It is equivalent to calling `dmi_file_seek(fd, 0, SEEK_CUR)`.

=== Parameters

`fd`::
Open file descriptor.

== Return value

Returns the current byte offset from the beginning of the file, or `-1` on
error with `errno` set accordingly.

== Errors

None.

== See also

`dmi_file_seek`(3),
`dmi_file_read`(3),
`lseek`(2)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
