ifdef::backend-manpage[]
= dmi_ipow32(3)
endif::[]
ifndef::backend-manpage[]
= dmi_ipow32
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_ipow32, dmi_ipow64 - raise an unsigned integer to an integer power.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/utils.h>

uint32_t dmi_ipow32(uint32_t value, unsigned int factor);
uint64_t dmi_ipow64(uint64_t value, unsigned int factor);
----

== Description

The `dmi_ipow32` and `dmi_ipow64` functions raise `value` to the power
`factor` in unsigned integer arithmetic of 32 and 64 bits, by binary
exponentiation, e.g. to scale a value by a power of ten given in SMBIOS
data. Any value raised to the power of zero is 1, zero included.

A result which does not fit in the type wraps around, as unsigned
multiplication does: the functions return it modulo 2^32^ and 2^64^.

=== Parameters

`value`::
Base.

`factor`::
Exponent.

== Return value

The functions return `value` raised to the power `factor`, modulo 2^32^ or
2^64^.

== Errors

None.

== See also

`pow`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
