ifdef::backend-manpage[]
= dmi_file_read(3)
endif::[]
ifndef::backend-manpage[]
= dmi_file_read
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_file_read - read exactly the requested number of bytes from a file descriptor.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/utils/file.h>

ssize_t dmi_file_read(int fd, dmi_data_t *data, off_t offset, size_t size);
----

== Description

The `dmi_file_read` function performs a full read by looping until all
requested bytes are read or end-of-file is reached. It retries automatically
if interrupted by a signal (`EINTR`). Fewer than `size` bytes are returned
only if EOF is encountered before the read is complete.

=== Parameters

`fd`::
Open file descriptor to read from.

`data`::
Buffer that receives the data; must be at least `size` bytes.

`offset`::
Starting offset, or `-1` to read from the current position.

`size`::
Number of bytes to read.

== Return value

Returns the total number of bytes read (may be less than `size` at EOF), or
`-1` on error with `errno` set accordingly.

== Errors

None.

== See also

`dmi_file_load`(3),
`dmi_file_seek`(3),
`dmi_file_stat`(3),
`dmi_file_close`(3),
`read`(2)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
