ifdef::backend-manpage[]
= dmi_file_lock(3)
endif::[]
ifndef::backend-manpage[]
= dmi_file_lock
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_file_lock - acquire an advisory lock on a region of a file.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/utils/file.h>

bool dmi_file_lock(int fd, off_t size);
----

== Description

The `dmi_file_lock` function locks `size` bytes of the file starting at the
current offset using `lockf(F_LOCK)`. The call blocks until the lock is
acquired. It retries automatically if interrupted by a signal (`EINTR`).

Passing `size` of `0` locks from the current offset to the end of the file.

=== Parameters

`fd`::
Open file descriptor.

`size`::
Number of bytes to lock, or `0` to lock to end of file.

== Return value

Returns `true` if the lock was acquired, `false` on error.

== Errors

None.

== See also

`dmi_file_unlock`(3),
`lockf`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
