ifdef::backend-manpage[]
= dmi_encoder_remaining(3)
endif::[]
ifndef::backend-manpage[]
= dmi_encoder_remaining
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_encoder_remaining - get the number of the bytes of the source of an encoder left at the current position.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/encoder.h>

size_t dmi_encoder_remaining(const dmi_encoder_t *encoder);
----

== Description

The `dmi_encoder_remaining` function returns the number of the bytes the
source data holds from the current position on, which is zero in the
canonical mode.

=== Parameters

`encoder`::
Encoder to query.

== Return value

Number of the bytes.

== Errors

None.

== See also

`dmi_encoder_peek`(3),
`dmi_encoder_copy`(3),
`dmi_decoder_remaining`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
