ifdef::backend-manpage[]
= dmi_reader_rewind(3)
endif::[]
ifndef::backend-manpage[]
= dmi_reader_rewind
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_reader_rewind - reposition a reader cursor to a mark taken earlier.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/reader.h>

bool dmi_reader_rewind(dmi_reader_t *reader, dmi_reader_mark_t mark);
----

== Description

The `dmi_reader_rewind` function repositions the reader cursor to a mark
taken with `dmi_reader_mark`(3).

=== Parameters

`reader`::
Reader to reposition.

`mark`::
Mark taken from the same reader with `dmi_reader_mark`(3).

== Return value

`true` on success, `false` if the mark was taken from a reader reading
another range.

== Errors

None.

== See also

`dmi_reader_mark`(3),
`dmi_reader_skip_ex`(3),
`dmi_reader_seek`(3)

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
