= dmi_cooling_device(3)
The OpenDMI contributors
OpenDMI 0.4.0

:doctype: manpage
:release-version: 0.4.0
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

== Name

dmi_cooling_device - describes the attributes for a cooling device in the
system.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)

== Synopsis

[source, c]
----
#include <opendmi/entity/cooling-device.h>

typedef struct dmi_cooling_device {
    dmi_handle_t probe_handle;
    dmi_entity_t *probe;
    dmi_cooling_device_type_t type;
    dmi_status_t status;
    unsigned short group;
    uint32_t oem_defined;
    short nominal_speed;
    const char *description;
} dmi_cooling_device_t;
----

== Description

This structure describes the attributes for a cooling device in the system.
Each structure describes a single cooling device.

=== Fields

`probe_handle`::
Handle of the temperature probe monitoring this cooling device.

`probe`::
The temperature probe monitoring this cooling device. May be `nullptr` when the
temperature probe handle is incorrect (e.g. due to SMBIOS data errors).

`type`::
Cooling device type.

`status`::
Cooling device status.

`group`::
Cooling unit group to which this cooling device is associated. Having multiple
cooling devices in the same cooling unit implies a redundant configuration. The
value is `0` if the cooling device is not a member of a redundant cooling unit.
Non-zero values imply redundancy and that at least one other cooling device will
be enumerated with the same value.

`oem_defined`::
OEM- or firmware vendor-specific information.

`nominal_speed`::
Nominal value for the cooling device's rotational speed, in revolutions-per-minute
(rpm). If the value is unknown or the cooling device is non-rotating, the field is
set to `SHRT_MIN`.

`description`::
Additional descriptive information about the cooling device or its location. May
be `nullptr`.

=== Device types

`DMI_COOLING_DEVICE_TYPE_UNSPEC`:: Unspecified
`DMI_COOLING_DEVICE_TYPE_OTHER`:: Other
`DMI_COOLING_DEVICE_TYPE_UNKNOWN`:: Unknown
`DMI_COOLING_DEVICE_TYPE_FAN`:: Fan
`DMI_COOLING_DEVICE_TYPE_CENTRIFUGAL_BLOWER`:: Centrifugal blower
`DMI_COOLING_DEVICE_TYPE_CHIP_FAN`:: Chip fan
`DMI_COOLING_DEVICE_TYPE_CABINET_FAN`:: Cabinet fan
`DMI_COOLING_DEVICE_TYPE_POWER_SUPPLY_FAN`:: Power supply fan
`DMI_COOLING_DEVICE_TYPE_HEAT_PIPE`:: Heat pipe
`DMI_COOLING_DEVICE_TYPE_INTEGRATED_REFRIGERATION`:: Integrated refrigeration
`DMI_COOLING_DEVICE_TYPE_ACTIVE_COOLING`:: Active cooling
`DMI_COOLING_DEVICE_TYPE_PASSIVE_COOLING`:: Passive cooling

=== Statuses

`DMI_STATUS_UNSPEC`:: Unspecified
`DMI_STATUS_OTHER`:: Other
`DMI_STATUS_UNKNOWN`:: Unknown
`DMI_STATUS_OK`:: OK
`DMI_STATUS_NON_CRITICAL`:: Non-critical
`DMI_STATUS_CRITICAL`:: Critical
`DMI_STATUS_NON_RECOVERABLE`:: Non-recoverable

== Examples

[source, c]
```
dmi_entity_t *entity;
dmi_cooling_device_t *info;

info = dmi_entity_info(entity, DMI_TYPE_COOLING_DEVICE);

printf("type: %s\n", dmi_cooling_device_type_name(info->type));
printf("status: %s\n", dmi_status_name(info->status));
printf("location: %s\n", info->location ? info->location : "unspecified");
```

== Specification

[cols="1,1,1,1,3"]
|===
| Offset | Version | Name | Length | Description

| `0x00`
| 2.2+
| Type
| `BYTE`
| Cooling Device indicator.

| `0x01`
| 2.2+
| Length
| `BYTE`
| Length of the structure, at least `0x0C`.

| `0x02`
| 2.2+
| Handle
| `WORD`
| Handle associated with the structure.

| `0x04`
| 2.2+
| Temperature Probe Handle
| `WORD`
| Handle of the temperature probe monitoring this cooling device.

| `0x06`
| 2.2+
| Device Type and Status
| `BYTE`
| Cooling device type and status.

| `0x07`
| 2.2+
| Cooling Unit Group
| `BYTE`
| Cooling unit group to which this cooling device is associated. Having multiple
cooling devices in the same cooling unit implies a redundant configuration. The
value is zero if the cooling device is not a member of a redundant cooling unit.
Non-zero values imply redundancy and that at least one other cooling device will
be enumerated with the same value.

| `0x08`
| 2.2+
| OEM-defined
| `DWORD`
| OEM- or firmware vendor-specific information.

| `0Ch`
| 2.2+
| Nominal Speed
| `WORD`
| Nominal value for the cooling device's rotational speed, in revolutions-per-
minute (rpm). If the value is unknown or the cooling device is non-rotating, the
field is set to `0x8000`. This field is present in the structure only if the
structure's length is larger than `0x0C`.

| `0x0E`
| 2.7+
| Description
| `BYTE`
| Number of the string that contains additional descriptive information about
the cooling device or its location. This field is present in the structure only
if the structure's length is `0x0F` or larger.
|===

== See also

`dmi_entity_info`(3),
`dmi_cooling_device_type_name`(3),
`dmi_status_name`(3)

== Standards

DMTF SMBIOS Specification, version 2.2 or newer.

== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
