ifdef::backend-manpage[]
= dmi_pci_vendor_id(3)
endif::[]
ifndef::backend-manpage[]
= dmi_pci_vendor_id
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_pci_vendor_id - PCI vendor identifier

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/common.h>

typedef uint16_t dmi_pci_vendor_id_t;
----

== Description

The `dmi_pci_vendor_id_t` type holds a PCI vendor identifier, which the PCI-SIG
assigns to the vendors of PCI devices, as in the vendor and subsystem vendor
identifier registers of a function.

The type is shared by several structures: it is the type of the `vendor_id` and
`sub_vendor_id` fields of `dmi_intel_rsd_pcie_t`, the `vendor_id` and
`sub_vendor_id` fields of `dmi_intel_rsd_network_card_t`, and the `vendor_id`
and `sub_vendor_id` fields of `dmi_intel_rsd_storage_device_t`.

== See also

`dmi_intel_rsd_pcie`(3), `dmi_intel_rsd_network_card`(3),
`dmi_intel_rsd_storage_device`(3), `dmi_pci_addr`(3)

== Standards

Not part of the SMBIOS specification. Used by the structures defined by Intel
Rack Scale Design firmware.

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
