= dmi_entity_handle(3)
The OpenDMI contributors
OpenDMI 0.4.0

:doctype: manpage
:release-version: 0.4.0
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

== Name

dmi_entity_handle - get entity handle.

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)

== Synopsis

[source, c]
----
#include <opendmi/entity.h>

dmi_handle_t dmi_entity_handle(const dmi_entity_t *entity);
----

== Description

The `dmi_entity_handle` function returns the SMBIOS handle associated with the
given entity. Each SMBIOS structure is assigned a unique handle by the platform
firmware, which can be used to reference the structure from other structures.

=== Parameters

`entity`::
Entity descriptor.

== Return value

Returns the handle associated with the entity. If `entity` is `nullptr`, returns
`DMI_HANDLE_INVALID` (`0xFFFF`).

== See also

`dmi_entity_type`(3),
`dmi_entity_name`(3),
`dmi_entity_data`(3),
`dmi_entity_info`(3)

== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
