ifdef::backend-manpage[]
= dmi_mgmt_nhi_usb_v2(3)
endif::[]
ifndef::backend-manpage[]
= dmi_mgmt_nhi_usb_v2
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_mgmt_nhi_usb_v2 - USB network interface descriptor, second version

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/mgmt-controller.h>

typedef struct dmi_mgmt_nhi_usb_v2 {
    uint16_t vendor_id;
    uint16_t product_id;
    const char *serial_number;
    dmi_binary_t mac_address;
    uint16_t characteristics;
    dmi_handle_t credential_handle;
} dmi_mgmt_nhi_usb_v2_t;
----

== Description

The `dmi_mgmt_nhi_usb_v2_t` structure holds the second version of the
descriptor of a USB network interface (device type 0x04) through which the host
reaches the management controller. It is the type of the `usb_v2` field of
`dmi_mgmt_nhi_t`, which is valid when the `format` of it is
`DMI_MGMT_NHI_FORMAT_USB_V2`.

=== Fields

`vendor_id`::
Vendor ID of the device, as its USB device descriptor gives it (`idVendor`).

`product_id`::
Product ID of the device, as its USB device descriptor gives it (`idProduct`).

`serial_number`::
Serial number of the device, one of the strings of the SMBIOS structure, or
`nullptr` if the descriptor refers to none.

`mac_address`::
MAC address of the device, six bytes referring to the data of the structure in
place.

`characteristics`::
Device characteristics, a set of the bits `dmi_mgmt_nhi_characteristic`(3)
numbers. Zero if the descriptor is too short to hold them, as the descriptors
older than DSP0270 1.3 are.

`credential_handle`::
Handle of the interface to be used for credential bootstrapping via IPMI
commands. `DMI_HANDLE_INVALID` if bootstrapping is not supported, or if the
descriptor is too short to hold the handle, as the descriptors older than
DSP0270 1.3 are.

== See also

`dmi_mgmt_nhi`(3), `dmi_mgmt_nhi_characteristic`(3), `dmi_mgmt_nhi_usb`(3)

== Standards

DMTF Redfish Host Interface Specification (DSP0270), which defines this data of
the management controller host interface structure (type 42) of the DMTF SMBIOS
Specification (DSP0134).

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
