ifdef::backend-manpage[]
= dmi_memory_module_voltage(3)
endif::[]
ifndef::backend-manpage[]
= dmi_memory_module_voltage
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_memory_module_voltage - memory module voltages

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/memory-controller.h>

typedef union dmi_memory_module_voltage {
    dmi_byte_t __value;
    struct {
        dmi_byte_t is_5v      : 1;
        dmi_byte_t is_3v3     : 1;
        dmi_byte_t is_2v9     : 1;
        dmi_byte_t __reserved : 5;
    };
} dmi_memory_module_voltage_t;
----

== Description

The `dmi_memory_module_voltage_t` union holds the voltages the memory module
sockets of a memory controller require as a set of flags, and is the type of
the `required_voltages` field of `dmi_memory_controller_t`. Several bits set
mean that the voltage of the sockets can be configured.

=== Fields

`__value`::
Raw value of the byte, `is_5v` being bit 0.

`is_5v`::
5 V.

`is_3v3`::
3.3 V.

`is_2v9`::
2.9 V.

`__reserved`::
Reserved bits, zero.

== See also

`dmi_memory_controller`(3)

== Standards

DMTF SMBIOS Specification (DSP0134), version 2.0 or newer. The memory
controller information structure is obsolete since version 2.1.

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
