ifdef::backend-manpage[]
= dmi_tpm_device_chars(3)
endif::[]
ifndef::backend-manpage[]
= dmi_tpm_device_chars
endif::[]
:author: The OpenDMI contributors
:manmanual: OpenDMI Manual
:mansource: OpenDMI {release-version}

ifdef::backend-manpage[]
== Name

dmi_tpm_device_chars - TPM device characteristics

== Library

OpenDMI C library (`libopendmi`, `-lopendmi`)
endif::[]

== Synopsis

[source, c]
----
#include <opendmi/entity/tpm-device.h>

typedef union dmi_tpm_device_chars {
    uint64_t __value;

    struct {
        uint64_t reserved_1                  : 2;
        uint64_t is_unsupported              : 1;
        uint64_t is_update_configurable      : 1;
        uint64_t is_software_configurable    : 1;
        uint64_t is_proprietary_configurable : 1;
        uint64_t reserved_2                  : 58;
    };
} dmi_tpm_device_chars_t;
----

== Description

The `dmi_tpm_device_chars_t` union holds the characteristics of a TPM
device, and is the type of the `characteristics` field of `dmi_tpm_device_t`. The
value can be read as a whole through `__value`, or bit by bit through the
named members. The configurable characteristics tell how the TPM family of
the device, such as TPM 1.2 or TPM 2.0, can be switched.

=== Fields

`__value`::
Raw value of the characteristics.

`reserved_1`::
Reserved bits.

`is_unsupported`::
Set if the device does not report its characteristics.

`is_update_configurable`::
Set if the TPM family can be changed by a firmware update.

`is_software_configurable`::
Set if the TPM family can be changed through platform software, such as the
firmware setup.

`is_proprietary_configurable`::
Set if the TPM family can be changed through a mechanism of the OEM.

`reserved_2`::
Reserved bits.

== See also

`dmi_tpm_device`(3)

== Standards

DMTF SMBIOS Specification (DSP0134), version 3.1 or newer.

ifdef::backend-manpage[]
== Copying

Copyright (c) 2025-2026, The OpenDMI contributors. Free use of this software
is granted under the terms of the BSD 3-Clause License.
endif::[]
