= GPD
:toc:
:toclevels: 1

== MicroPC (micropc.bin)

[horizontal]
File path:: `gpd/micropc.bin`
Product name:: MicroPC
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends Inc.
Firmware version:: 4.10
Release date:: 2019-06-14
SMBIOS version:: 3.1.1

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x0030`
a| `7` | Cache information | 2  a| `0x002E`, `0x002F`
a| `8` | Port connector information | 24  a| `0x0008`, `0x0009`, `0x000A`, `0x000B`, `0x000C`, `0x000D`, `0x000E`, `0x000F`, `0x0010`, `0x0011`, `0x0012`, `0x0013`, `0x0014`, `0x0015`, `0x0016`, `0x0017`, `0x0018`, `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`
a| `9` | System slots | 2  a| `0x0051`, `0x0052`
a| `10` | Onboard devices information | 1  a| `0x0020`
a| `11` | OEM strings | 1  a| `0x0021`
a| `12` | System configuration options | 1  a| `0x0022`
a| `13` | Firmware language information | 1  a| `0x0050`
a| `16` | Physical memory array | 1  a| `0x0023`
a| `17` | Memory device | 2  a| `0x0025`, `0x0027`
a| `19` | Memory array mapped address | 1  a| `0x0024`
a| `20` | Memory device mapped address | 2  a| `0x0026`, `0x0028`
a| `32` | System boot information | 1  a| `0x0029`
a| `41` | Onboard devices extended information | 31  a| `0x0031`, `0x0032`, `0x0033`, `0x0034`, `0x0035`, `0x0036`, `0x0037`, `0x0038`, `0x0039`, `0x003A`, `0x003B`, `0x003C`, `0x003D`, `0x003E`, `0x003F`, `0x0040`, `0x0041`, `0x0042`, `0x0043`, `0x0044`, `0x0045`, `0x0046`, `0x0047`, `0x0048`, `0x0049`, `0x004A`, `0x004B`, `0x004C`, `0x004D`, `0x004E`, `0x004F`
a| `127` | End of table | 1  a| `0x0053`
|===
