= Minisforum
:toc:
:toclevels: 1

== UM790 Pro (um790-pro.bin)

[horizontal]
File path:: `minisforum/um790-pro.bin`
Product name:: Venus series
Product version:: Default string
Product family:: Default string
Firmware vendor:: American Megatrends International, LLC.
Firmware version:: 1.09
Release date:: 2023-11-20
SMBIOS version:: 3.5

=== Contents

[cols="1,3,1,2"]
|===
| Type | Description | Count | Handles

a| `0` | Platform firmware information | 1  a| `0x0000`
a| `1` | System information | 1  a| `0x0001`
a| `2` | Baseboard or module information | 1  a| `0x0002`
a| `3` | System enclosure or chassis | 1  a| `0x0003`
a| `4` | Processor information | 1  a| `0x000E`
a| `7` | Cache information | 3  a| `0x000B`, `0x000C`, `0x000D`
a| `8` | Port connector information | 11  a| `0x0019`, `0x001A`, `0x001B`, `0x001C`, `0x001D`, `0x001E`, `0x001F`, `0x0020`, `0x0021`, `0x0022`, `0x0023`
a| `9` | System slots | 5  a| `0x0024`, `0x0025`, `0x0026`, `0x0027`, `0x0028`
a| `10` | Onboard devices information | 1  a| `0x0004`
a| `11` | OEM strings | 1  a| `0x0005`
a| `12` | System configuration options | 1  a| `0x0006`
a| `13` | Firmware language information | 1  a| `0x002B`
a| `16` | Physical memory array | 1  a| `0x0010`
a| `17` | Memory device | 2  a| `0x0013`, `0x0016`
a| `18` | 32-bit memory error information | 3  a| `0x000F`, `0x0012`, `0x0015`
a| `19` | Memory array mapped address | 1  a| `0x0011`
a| `20` | Memory device mapped address | 2  a| `0x0014`, `0x0017`
a| `32` | System boot information | 1  a| `0x0007`
a| `40` | Additional information | 1  a| `0x0018`
a| `41` | Onboard devices extended information | 2  a| `0x0029`, `0x002A`
a| `43` | TPM device | 1  a| `0x0009`
a| `44` | Processor additional information | 1  a| `0x0008`
a| `45` | Firmware inventory information | 1  a| `0x000A`
a| `127` | End of table | 1  a| `0x002C`
|===
